version: "2"
run:
  concurrency: 10
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-checks:
        - ruleguard
      settings:
        ruleguard:
          rules: pkg/ruleguard.rules.go
    nakedret:
      max-func-lines: 60
    revive:
      confidence: 3
      severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: "404"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
