// Code generated by ent, DO NOT EDIT.

package tablerow

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tablerow type in the database.
	Label = "table_row"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldNanoid holds the string denoting the nanoid field in the database.
	FieldNanoid = "nanoid"
	// FieldCells holds the string denoting the cells field in the database.
	FieldCells = "cells"
	// EdgeTablemeta holds the string denoting the tablemeta edge name in mutations.
	EdgeTablemeta = "tablemeta"
	// Table holds the table name of the tablerow in the database.
	Table = "table_rows"
	// TablemetaTable is the table that holds the tablemeta relation/edge.
	TablemetaTable = "table_rows"
	// TablemetaInverseTable is the table name for the TableMeta entity.
	// It exists in this package in order to avoid circular dependency with the "tablemeta" package.
	TablemetaInverseTable = "table_meta"
	// TablemetaColumn is the table column denoting the tablemeta relation/edge.
	TablemetaColumn = "table_meta_rows"
)

// Columns holds all SQL columns for tablerow fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldNanoid,
	FieldCells,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "table_rows"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"table_meta_rows",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the TableRow queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNanoid orders the results by the nanoid field.
func ByNanoid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNanoid, opts...).ToFunc()
}

// ByTablemetaField orders the results by tablemeta field.
func ByTablemetaField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTablemetaStep(), sql.OrderByField(field, opts...))
	}
}
func newTablemetaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TablemetaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TablemetaTable, TablemetaColumn),
	)
}
