// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package client

import (
	"context"
	"sync"
)

// Ensure, that ChatClientMock does implement ChatClient.
// If this is not the case, regenerate this file with moq.
var _ ChatClient = &ChatClientMock{}

// ChatClientMock is a mock implementation of ChatClient.
//
//	func TestSomethingThatUsesChatClient(t *testing.T) {
//
//		// make and configure a mocked ChatClient
//		mockedChatClient := &ChatClientMock{
//			ChatFunc: func(ctx context.Context, request *ChatRequest) (*ChatResponse, error) {
//				panic("mock out the Chat method")
//			},
//			ImageGenFunc: func(ctx context.Context, request *ChatRequest) (*ImageGenResponse, error) {
//				panic("mock out the ImageGen method")
//			},
//		}
//
//		// use mockedChatClient in code that requires ChatClient
//		// and then make assertions.
//
//	}
type ChatClientMock struct {
	// ChatFunc mocks the Chat method.
	ChatFunc func(ctx context.Context, request *ChatRequest) (*ChatResponse, error)

	// ImageGenFunc mocks the ImageGen method.
	ImageGenFunc func(ctx context.Context, request *ChatRequest) (*ImageGenResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Chat holds details about calls to the Chat method.
		Chat []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Request is the request argument value.
			Request *ChatRequest
		}
		// ImageGen holds details about calls to the ImageGen method.
		ImageGen []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Request is the request argument value.
			Request *ChatRequest
		}
	}
	lockChat     sync.RWMutex
	lockImageGen sync.RWMutex
}

// Chat calls ChatFunc.
func (mock *ChatClientMock) Chat(ctx context.Context, request *ChatRequest) (*ChatResponse, error) {
	if mock.ChatFunc == nil {
		panic("ChatClientMock.ChatFunc: method is nil but ChatClient.Chat was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Request *ChatRequest
	}{
		Ctx:     ctx,
		Request: request,
	}
	mock.lockChat.Lock()
	mock.calls.Chat = append(mock.calls.Chat, callInfo)
	mock.lockChat.Unlock()
	return mock.ChatFunc(ctx, request)
}

// ChatCalls gets all the calls that were made to Chat.
// Check the length with:
//
//	len(mockedChatClient.ChatCalls())
func (mock *ChatClientMock) ChatCalls() []struct {
	Ctx     context.Context
	Request *ChatRequest
} {
	var calls []struct {
		Ctx     context.Context
		Request *ChatRequest
	}
	mock.lockChat.RLock()
	calls = mock.calls.Chat
	mock.lockChat.RUnlock()
	return calls
}

// ImageGen calls ImageGenFunc.
func (mock *ChatClientMock) ImageGen(ctx context.Context, request *ChatRequest) (*ImageGenResponse, error) {
	if mock.ImageGenFunc == nil {
		panic("ChatClientMock.ImageGenFunc: method is nil but ChatClient.ImageGen was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Request *ChatRequest
	}{
		Ctx:     ctx,
		Request: request,
	}
	mock.lockImageGen.Lock()
	mock.calls.ImageGen = append(mock.calls.ImageGen, callInfo)
	mock.lockImageGen.Unlock()
	return mock.ImageGenFunc(ctx, request)
}

// ImageGenCalls gets all the calls that were made to ImageGen.
// Check the length with:
//
//	len(mockedChatClient.ImageGenCalls())
func (mock *ChatClientMock) ImageGenCalls() []struct {
	Ctx     context.Context
	Request *ChatRequest
} {
	var calls []struct {
		Ctx     context.Context
		Request *ChatRequest
	}
	mock.lockImageGen.RLock()
	calls = mock.calls.ImageGen
	mock.lockImageGen.RUnlock()
	return calls
}
