// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package client

import (
	"context"
	"google.golang.org/genai"
	"sync"
)

// Ensure, that GenaiModelServiceMock does implement GenaiModelService.
// If this is not the case, regenerate this file with moq.
var _ GenaiModelService = &GenaiModelServiceMock{}

// GenaiModelServiceMock is a mock implementation of GenaiModelService.
//
//	func TestSomethingThatUsesGenaiModelService(t *testing.T) {
//
//		// make and configure a mocked GenaiModelService
//		mockedGenaiModelService := &GenaiModelServiceMock{
//			GenerateContentFunc: func(ctx context.Context, model string, contents []*genai.Content, config *genai.GenerateContentConfig) (*genai.GenerateContentResponse, error) {
//				panic("mock out the GenerateContent method")
//			},
//		}
//
//		// use mockedGenaiModelService in code that requires GenaiModelService
//		// and then make assertions.
//
//	}
type GenaiModelServiceMock struct {
	// GenerateContentFunc mocks the GenerateContent method.
	GenerateContentFunc func(ctx context.Context, model string, contents []*genai.Content, config *genai.GenerateContentConfig) (*genai.GenerateContentResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GenerateContent holds details about calls to the GenerateContent method.
		GenerateContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Model is the model argument value.
			Model string
			// Contents is the contents argument value.
			Contents []*genai.Content
			// Config is the config argument value.
			Config *genai.GenerateContentConfig
		}
	}
	lockGenerateContent sync.RWMutex
}

// GenerateContent calls GenerateContentFunc.
func (mock *GenaiModelServiceMock) GenerateContent(ctx context.Context, model string, contents []*genai.Content, config *genai.GenerateContentConfig) (*genai.GenerateContentResponse, error) {
	if mock.GenerateContentFunc == nil {
		panic("GenaiModelServiceMock.GenerateContentFunc: method is nil but GenaiModelService.GenerateContent was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Model    string
		Contents []*genai.Content
		Config   *genai.GenerateContentConfig
	}{
		Ctx:      ctx,
		Model:    model,
		Contents: contents,
		Config:   config,
	}
	mock.lockGenerateContent.Lock()
	mock.calls.GenerateContent = append(mock.calls.GenerateContent, callInfo)
	mock.lockGenerateContent.Unlock()
	return mock.GenerateContentFunc(ctx, model, contents, config)
}

// GenerateContentCalls gets all the calls that were made to GenerateContent.
// Check the length with:
//
//	len(mockedGenaiModelService.GenerateContentCalls())
func (mock *GenaiModelServiceMock) GenerateContentCalls() []struct {
	Ctx      context.Context
	Model    string
	Contents []*genai.Content
	Config   *genai.GenerateContentConfig
} {
	var calls []struct {
		Ctx      context.Context
		Model    string
		Contents []*genai.Content
		Config   *genai.GenerateContentConfig
	}
	mock.lockGenerateContent.RLock()
	calls = mock.calls.GenerateContent
	mock.lockGenerateContent.RUnlock()
	return calls
}
