// Code generated by ent, DO NOT EDIT.

package model

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Yiling-J/tablepilot/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldUpdatedAt, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldModel, v))
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldAlias, v))
}

// Rpm applies equality check predicate on the "rpm" field. It's identical to RpmEQ.
func Rpm(v int) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldRpm, v))
}

// MaxTokens applies equality check predicate on the "max_tokens" field. It's identical to MaxTokensEQ.
func MaxTokens(v int) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldMaxTokens, v))
}

// Default applies equality check predicate on the "default" field. It's identical to DefaultEQ.
func Default(v bool) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldDefault, v))
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v bool) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldImage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldUpdatedAt))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.Model {
	return predicate.Model(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.Model {
	return predicate.Model(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.Model {
	return predicate.Model(sql.FieldContainsFold(FieldModel, v))
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.Model {
	return predicate.Model(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.Model {
	return predicate.Model(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasIsNil applies the IsNil predicate on the "alias" field.
func AliasIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldAlias))
}

// AliasNotNil applies the NotNil predicate on the "alias" field.
func AliasNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldAlias))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.Model {
	return predicate.Model(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.Model {
	return predicate.Model(sql.FieldContainsFold(FieldAlias, v))
}

// RpmEQ applies the EQ predicate on the "rpm" field.
func RpmEQ(v int) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldRpm, v))
}

// RpmNEQ applies the NEQ predicate on the "rpm" field.
func RpmNEQ(v int) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldRpm, v))
}

// RpmIn applies the In predicate on the "rpm" field.
func RpmIn(vs ...int) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldRpm, vs...))
}

// RpmNotIn applies the NotIn predicate on the "rpm" field.
func RpmNotIn(vs ...int) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldRpm, vs...))
}

// RpmGT applies the GT predicate on the "rpm" field.
func RpmGT(v int) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldRpm, v))
}

// RpmGTE applies the GTE predicate on the "rpm" field.
func RpmGTE(v int) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldRpm, v))
}

// RpmLT applies the LT predicate on the "rpm" field.
func RpmLT(v int) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldRpm, v))
}

// RpmLTE applies the LTE predicate on the "rpm" field.
func RpmLTE(v int) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldRpm, v))
}

// RpmIsNil applies the IsNil predicate on the "rpm" field.
func RpmIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldRpm))
}

// RpmNotNil applies the NotNil predicate on the "rpm" field.
func RpmNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldRpm))
}

// MaxTokensEQ applies the EQ predicate on the "max_tokens" field.
func MaxTokensEQ(v int) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldMaxTokens, v))
}

// MaxTokensNEQ applies the NEQ predicate on the "max_tokens" field.
func MaxTokensNEQ(v int) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldMaxTokens, v))
}

// MaxTokensIn applies the In predicate on the "max_tokens" field.
func MaxTokensIn(vs ...int) predicate.Model {
	return predicate.Model(sql.FieldIn(FieldMaxTokens, vs...))
}

// MaxTokensNotIn applies the NotIn predicate on the "max_tokens" field.
func MaxTokensNotIn(vs ...int) predicate.Model {
	return predicate.Model(sql.FieldNotIn(FieldMaxTokens, vs...))
}

// MaxTokensGT applies the GT predicate on the "max_tokens" field.
func MaxTokensGT(v int) predicate.Model {
	return predicate.Model(sql.FieldGT(FieldMaxTokens, v))
}

// MaxTokensGTE applies the GTE predicate on the "max_tokens" field.
func MaxTokensGTE(v int) predicate.Model {
	return predicate.Model(sql.FieldGTE(FieldMaxTokens, v))
}

// MaxTokensLT applies the LT predicate on the "max_tokens" field.
func MaxTokensLT(v int) predicate.Model {
	return predicate.Model(sql.FieldLT(FieldMaxTokens, v))
}

// MaxTokensLTE applies the LTE predicate on the "max_tokens" field.
func MaxTokensLTE(v int) predicate.Model {
	return predicate.Model(sql.FieldLTE(FieldMaxTokens, v))
}

// MaxTokensIsNil applies the IsNil predicate on the "max_tokens" field.
func MaxTokensIsNil() predicate.Model {
	return predicate.Model(sql.FieldIsNull(FieldMaxTokens))
}

// MaxTokensNotNil applies the NotNil predicate on the "max_tokens" field.
func MaxTokensNotNil() predicate.Model {
	return predicate.Model(sql.FieldNotNull(FieldMaxTokens))
}

// DefaultEQ applies the EQ predicate on the "default" field.
func DefaultEQ(v bool) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldDefault, v))
}

// DefaultNEQ applies the NEQ predicate on the "default" field.
func DefaultNEQ(v bool) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldDefault, v))
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v bool) predicate.Model {
	return predicate.Model(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v bool) predicate.Model {
	return predicate.Model(sql.FieldNEQ(FieldImage, v))
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.Model {
	return predicate.Model(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.Provider) predicate.Model {
	return predicate.Model(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Model) predicate.Model {
	return predicate.Model(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Model) predicate.Model {
	return predicate.Model(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Model) predicate.Model {
	return predicate.Model(sql.NotPredicates(p))
}
