debug = false

[database]
driver = "sqlite3"
dsn = "data.db?_pragma=foreign_keys(1)"

[[clients]]
name = "gemini"
type = "openai"
key = "a"
base_url = "urla"

[[clients]]
name = "oai"
type = "openai"
key = "b"
base_url = "urlb"

[[models]]
model = "gemini-2.0-flash-001"
client = "gemini"
default = true
max_tokens = 1200
rpm = 10

[[models]]
model = "gpt-4o"
alias = "gpt4o"
client = "oai"
rpm = 5