// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ModelsColumns holds the columns for the "models" table.
	ModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "model", Type: field.TypeString, Unique: true},
		{Name: "alias", Type: field.TypeString, Nullable: true},
		{Name: "rpm", Type: field.TypeInt, Nullable: true},
		{Name: "max_tokens", Type: field.TypeInt, Nullable: true},
		{Name: "default", Type: field.TypeBool, Default: false},
		{Name: "image", Type: field.TypeBool, Default: false},
		{Name: "provider_models", Type: field.TypeInt, Nullable: true},
	}
	// ModelsTable holds the schema information for the "models" table.
	ModelsTable = &schema.Table{
		Name:       "models",
		Columns:    ModelsColumns,
		PrimaryKey: []*schema.Column{ModelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "models_providers_models",
				Columns:    []*schema.Column{ModelsColumns[9]},
				RefColumns: []*schema.Column{ProvidersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ProvidersColumns holds the columns for the "providers" table.
	ProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"openai", "gemini"}},
		{Name: "key", Type: field.TypeString, Nullable: true},
		{Name: "base_url", Type: field.TypeString, Nullable: true},
	}
	// ProvidersTable holds the schema information for the "providers" table.
	ProvidersTable = &schema.Table{
		Name:       "providers",
		Columns:    ProvidersColumns,
		PrimaryKey: []*schema.Column{ProvidersColumns[0]},
	}
	// TableColumnsColumns holds the columns for the "table_columns" table.
	TableColumnsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "nanoid", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"string", "number", "integer", "boolean", "array", "image"}},
		{Name: "fill_mode", Type: field.TypeEnum, Enums: []string{"ai", "pick"}},
		{Name: "source", Type: field.TypeString, Nullable: true},
		{Name: "context_length", Type: field.TypeInt, Default: 0},
		{Name: "random", Type: field.TypeBool, Default: false},
		{Name: "replacement", Type: field.TypeBool, Default: false},
		{Name: "repeat", Type: field.TypeInt, Default: 1},
		{Name: "linked_column", Type: field.TypeString, Default: ""},
		{Name: "linked_context_columns", Type: field.TypeJSON},
		{Name: "table_id", Type: field.TypeInt},
	}
	// TableColumnsTable holds the schema information for the "table_columns" table.
	TableColumnsTable = &schema.Table{
		Name:       "table_columns",
		Columns:    TableColumnsColumns,
		PrimaryKey: []*schema.Column{TableColumnsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "table_columns_table_meta_columns",
				Columns:    []*schema.Column{TableColumnsColumns[15]},
				RefColumns: []*schema.Column{TableMetaColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tablecolumn_name_table_id",
				Unique:  true,
				Columns: []*schema.Column{TableColumnsColumns[4], TableColumnsColumns[15]},
			},
		},
	}
	// TableMetaColumns holds the columns for the "table_meta" table.
	TableMetaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "nanoid", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "model", Type: field.TypeString, Default: ""},
		{Name: "sources", Type: field.TypeJSON, Nullable: true},
	}
	// TableMetaTable holds the schema information for the "table_meta" table.
	TableMetaTable = &schema.Table{
		Name:       "table_meta",
		Columns:    TableMetaColumns,
		PrimaryKey: []*schema.Column{TableMetaColumns[0]},
	}
	// TableRowsColumns holds the columns for the "table_rows" table.
	TableRowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "nanoid", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "cells", Type: field.TypeJSON, Nullable: true},
		{Name: "table_meta_rows", Type: field.TypeInt},
	}
	// TableRowsTable holds the schema information for the "table_rows" table.
	TableRowsTable = &schema.Table{
		Name:       "table_rows",
		Columns:    TableRowsColumns,
		PrimaryKey: []*schema.Column{TableRowsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "table_rows_table_meta_rows",
				Columns:    []*schema.Column{TableRowsColumns[5]},
				RefColumns: []*schema.Column{TableMetaColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// WorkflowsColumns holds the columns for the "workflows" table.
	WorkflowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "nanoid", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "variables", Type: field.TypeJSON},
		{Name: "steps", Type: field.TypeJSON},
	}
	// WorkflowsTable holds the schema information for the "workflows" table.
	WorkflowsTable = &schema.Table{
		Name:       "workflows",
		Columns:    WorkflowsColumns,
		PrimaryKey: []*schema.Column{WorkflowsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ModelsTable,
		ProvidersTable,
		TableColumnsTable,
		TableMetaTable,
		TableRowsTable,
		WorkflowsTable,
	}
)

func init() {
	ModelsTable.ForeignKeys[0].RefTable = ProvidersTable
	TableColumnsTable.ForeignKeys[0].RefTable = TableMetaTable
	TableRowsTable.ForeignKeys[0].RefTable = TableMetaTable
}
