// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TableColumnsColumns holds the columns for the "table_columns" table.
	TableColumnsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "nanoid", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"string", "number", "integer", "boolean", "array"}},
		{Name: "fill_mode", Type: field.TypeEnum, Enums: []string{"ai", "pick"}},
		{Name: "source", Type: field.TypeString, Nullable: true},
		{Name: "context_length", Type: field.TypeInt, Default: 0},
		{Name: "random", Type: field.TypeBool, Default: false},
		{Name: "replacement", Type: field.TypeBool, Default: false},
		{Name: "repeat", Type: field.TypeInt, Default: 1},
		{Name: "table_id", Type: field.TypeInt},
	}
	// TableColumnsTable holds the schema information for the "table_columns" table.
	TableColumnsTable = &schema.Table{
		Name:       "table_columns",
		Columns:    TableColumnsColumns,
		PrimaryKey: []*schema.Column{TableColumnsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "table_columns_table_meta_columns",
				Columns:    []*schema.Column{TableColumnsColumns[13]},
				RefColumns: []*schema.Column{TableMetaColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tablecolumn_name_table_id",
				Unique:  true,
				Columns: []*schema.Column{TableColumnsColumns[4], TableColumnsColumns[13]},
			},
		},
	}
	// TableMetaColumns holds the columns for the "table_meta" table.
	TableMetaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "nanoid", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "model", Type: field.TypeString, Default: ""},
		{Name: "sources", Type: field.TypeJSON, Nullable: true},
	}
	// TableMetaTable holds the schema information for the "table_meta" table.
	TableMetaTable = &schema.Table{
		Name:       "table_meta",
		Columns:    TableMetaColumns,
		PrimaryKey: []*schema.Column{TableMetaColumns[0]},
	}
	// TableRowsColumns holds the columns for the "table_rows" table.
	TableRowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "nanoid", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "cells", Type: field.TypeJSON, Nullable: true},
		{Name: "table_meta_rows", Type: field.TypeInt},
	}
	// TableRowsTable holds the schema information for the "table_rows" table.
	TableRowsTable = &schema.Table{
		Name:       "table_rows",
		Columns:    TableRowsColumns,
		PrimaryKey: []*schema.Column{TableRowsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "table_rows_table_meta_rows",
				Columns:    []*schema.Column{TableRowsColumns[5]},
				RefColumns: []*schema.Column{TableMetaColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TableColumnsTable,
		TableMetaTable,
		TableRowsTable,
	}
)

func init() {
	TableColumnsTable.ForeignKeys[0].RefTable = TableMetaTable
	TableRowsTable.ForeignKeys[0].RefTable = TableMetaTable
}
