// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Yiling-J/tablepilot/ent/predicate"
	"github.com/Yiling-J/tablepilot/ent/schema"
	"github.com/Yiling-J/tablepilot/ent/tablecolumn"
	"github.com/Yiling-J/tablepilot/ent/tablemeta"
	"github.com/Yiling-J/tablepilot/ent/tablerow"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeTableColumn = "TableColumn"
	TypeTableMeta   = "TableMeta"
	TypeTableRow    = "TableRow"
)

// TableColumnMutation represents an operation that mutates the TableColumn nodes in the graph.
type TableColumnMutation struct {
	config
	op                Op
	typ               string
	id                *int
	created_at        *time.Time
	updated_at        *time.Time
	nanoid            *string
	name              *string
	description       *string
	_type             *tablecolumn.Type
	fill_mode         *tablecolumn.FillMode
	source            *json.RawMessage
	appendsource      json.RawMessage
	context_length    *int
	addcontext_length *int
	clearedFields     map[string]struct{}
	tablemeta         *int
	clearedtablemeta  bool
	done              bool
	oldValue          func(context.Context) (*TableColumn, error)
	predicates        []predicate.TableColumn
}

var _ ent.Mutation = (*TableColumnMutation)(nil)

// tablecolumnOption allows management of the mutation configuration using functional options.
type tablecolumnOption func(*TableColumnMutation)

// newTableColumnMutation creates new mutation for the TableColumn entity.
func newTableColumnMutation(c config, op Op, opts ...tablecolumnOption) *TableColumnMutation {
	m := &TableColumnMutation{
		config:        c,
		op:            op,
		typ:           TypeTableColumn,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTableColumnID sets the ID field of the mutation.
func withTableColumnID(id int) tablecolumnOption {
	return func(m *TableColumnMutation) {
		var (
			err   error
			once  sync.Once
			value *TableColumn
		)
		m.oldValue = func(ctx context.Context) (*TableColumn, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TableColumn.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTableColumn sets the old TableColumn of the mutation.
func withTableColumn(node *TableColumn) tablecolumnOption {
	return func(m *TableColumnMutation) {
		m.oldValue = func(context.Context) (*TableColumn, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TableColumnMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TableColumnMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TableColumnMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TableColumnMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TableColumn.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *TableColumnMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *TableColumnMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the TableColumn entity.
// If the TableColumn object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableColumnMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ClearCreatedAt clears the value of the "created_at" field.
func (m *TableColumnMutation) ClearCreatedAt() {
	m.created_at = nil
	m.clearedFields[tablecolumn.FieldCreatedAt] = struct{}{}
}

// CreatedAtCleared returns if the "created_at" field was cleared in this mutation.
func (m *TableColumnMutation) CreatedAtCleared() bool {
	_, ok := m.clearedFields[tablecolumn.FieldCreatedAt]
	return ok
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *TableColumnMutation) ResetCreatedAt() {
	m.created_at = nil
	delete(m.clearedFields, tablecolumn.FieldCreatedAt)
}

// SetUpdatedAt sets the "updated_at" field.
func (m *TableColumnMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *TableColumnMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the TableColumn entity.
// If the TableColumn object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableColumnMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (m *TableColumnMutation) ClearUpdatedAt() {
	m.updated_at = nil
	m.clearedFields[tablecolumn.FieldUpdatedAt] = struct{}{}
}

// UpdatedAtCleared returns if the "updated_at" field was cleared in this mutation.
func (m *TableColumnMutation) UpdatedAtCleared() bool {
	_, ok := m.clearedFields[tablecolumn.FieldUpdatedAt]
	return ok
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *TableColumnMutation) ResetUpdatedAt() {
	m.updated_at = nil
	delete(m.clearedFields, tablecolumn.FieldUpdatedAt)
}

// SetNanoid sets the "nanoid" field.
func (m *TableColumnMutation) SetNanoid(s string) {
	m.nanoid = &s
}

// Nanoid returns the value of the "nanoid" field in the mutation.
func (m *TableColumnMutation) Nanoid() (r string, exists bool) {
	v := m.nanoid
	if v == nil {
		return
	}
	return *v, true
}

// OldNanoid returns the old "nanoid" field's value of the TableColumn entity.
// If the TableColumn object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableColumnMutation) OldNanoid(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNanoid is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNanoid requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNanoid: %w", err)
	}
	return oldValue.Nanoid, nil
}

// ClearNanoid clears the value of the "nanoid" field.
func (m *TableColumnMutation) ClearNanoid() {
	m.nanoid = nil
	m.clearedFields[tablecolumn.FieldNanoid] = struct{}{}
}

// NanoidCleared returns if the "nanoid" field was cleared in this mutation.
func (m *TableColumnMutation) NanoidCleared() bool {
	_, ok := m.clearedFields[tablecolumn.FieldNanoid]
	return ok
}

// ResetNanoid resets all changes to the "nanoid" field.
func (m *TableColumnMutation) ResetNanoid() {
	m.nanoid = nil
	delete(m.clearedFields, tablecolumn.FieldNanoid)
}

// SetName sets the "name" field.
func (m *TableColumnMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *TableColumnMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the TableColumn entity.
// If the TableColumn object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableColumnMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *TableColumnMutation) ResetName() {
	m.name = nil
}

// SetDescription sets the "description" field.
func (m *TableColumnMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *TableColumnMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the TableColumn entity.
// If the TableColumn object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableColumnMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *TableColumnMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[tablecolumn.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *TableColumnMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[tablecolumn.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *TableColumnMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, tablecolumn.FieldDescription)
}

// SetType sets the "type" field.
func (m *TableColumnMutation) SetType(t tablecolumn.Type) {
	m._type = &t
}

// GetType returns the value of the "type" field in the mutation.
func (m *TableColumnMutation) GetType() (r tablecolumn.Type, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the TableColumn entity.
// If the TableColumn object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableColumnMutation) OldType(ctx context.Context) (v tablecolumn.Type, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *TableColumnMutation) ResetType() {
	m._type = nil
}

// SetFillMode sets the "fill_mode" field.
func (m *TableColumnMutation) SetFillMode(tm tablecolumn.FillMode) {
	m.fill_mode = &tm
}

// FillMode returns the value of the "fill_mode" field in the mutation.
func (m *TableColumnMutation) FillMode() (r tablecolumn.FillMode, exists bool) {
	v := m.fill_mode
	if v == nil {
		return
	}
	return *v, true
}

// OldFillMode returns the old "fill_mode" field's value of the TableColumn entity.
// If the TableColumn object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableColumnMutation) OldFillMode(ctx context.Context) (v tablecolumn.FillMode, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFillMode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFillMode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFillMode: %w", err)
	}
	return oldValue.FillMode, nil
}

// ResetFillMode resets all changes to the "fill_mode" field.
func (m *TableColumnMutation) ResetFillMode() {
	m.fill_mode = nil
}

// SetSource sets the "source" field.
func (m *TableColumnMutation) SetSource(jm json.RawMessage) {
	m.source = &jm
	m.appendsource = nil
}

// Source returns the value of the "source" field in the mutation.
func (m *TableColumnMutation) Source() (r json.RawMessage, exists bool) {
	v := m.source
	if v == nil {
		return
	}
	return *v, true
}

// OldSource returns the old "source" field's value of the TableColumn entity.
// If the TableColumn object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableColumnMutation) OldSource(ctx context.Context) (v json.RawMessage, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSource is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSource requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSource: %w", err)
	}
	return oldValue.Source, nil
}

// AppendSource adds jm to the "source" field.
func (m *TableColumnMutation) AppendSource(jm json.RawMessage) {
	m.appendsource = append(m.appendsource, jm...)
}

// AppendedSource returns the list of values that were appended to the "source" field in this mutation.
func (m *TableColumnMutation) AppendedSource() (json.RawMessage, bool) {
	if len(m.appendsource) == 0 {
		return nil, false
	}
	return m.appendsource, true
}

// ClearSource clears the value of the "source" field.
func (m *TableColumnMutation) ClearSource() {
	m.source = nil
	m.appendsource = nil
	m.clearedFields[tablecolumn.FieldSource] = struct{}{}
}

// SourceCleared returns if the "source" field was cleared in this mutation.
func (m *TableColumnMutation) SourceCleared() bool {
	_, ok := m.clearedFields[tablecolumn.FieldSource]
	return ok
}

// ResetSource resets all changes to the "source" field.
func (m *TableColumnMutation) ResetSource() {
	m.source = nil
	m.appendsource = nil
	delete(m.clearedFields, tablecolumn.FieldSource)
}

// SetContextLength sets the "context_length" field.
func (m *TableColumnMutation) SetContextLength(i int) {
	m.context_length = &i
	m.addcontext_length = nil
}

// ContextLength returns the value of the "context_length" field in the mutation.
func (m *TableColumnMutation) ContextLength() (r int, exists bool) {
	v := m.context_length
	if v == nil {
		return
	}
	return *v, true
}

// OldContextLength returns the old "context_length" field's value of the TableColumn entity.
// If the TableColumn object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableColumnMutation) OldContextLength(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContextLength is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContextLength requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContextLength: %w", err)
	}
	return oldValue.ContextLength, nil
}

// AddContextLength adds i to the "context_length" field.
func (m *TableColumnMutation) AddContextLength(i int) {
	if m.addcontext_length != nil {
		*m.addcontext_length += i
	} else {
		m.addcontext_length = &i
	}
}

// AddedContextLength returns the value that was added to the "context_length" field in this mutation.
func (m *TableColumnMutation) AddedContextLength() (r int, exists bool) {
	v := m.addcontext_length
	if v == nil {
		return
	}
	return *v, true
}

// ResetContextLength resets all changes to the "context_length" field.
func (m *TableColumnMutation) ResetContextLength() {
	m.context_length = nil
	m.addcontext_length = nil
}

// SetTableID sets the "table_id" field.
func (m *TableColumnMutation) SetTableID(i int) {
	m.tablemeta = &i
}

// TableID returns the value of the "table_id" field in the mutation.
func (m *TableColumnMutation) TableID() (r int, exists bool) {
	v := m.tablemeta
	if v == nil {
		return
	}
	return *v, true
}

// OldTableID returns the old "table_id" field's value of the TableColumn entity.
// If the TableColumn object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableColumnMutation) OldTableID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTableID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTableID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTableID: %w", err)
	}
	return oldValue.TableID, nil
}

// ResetTableID resets all changes to the "table_id" field.
func (m *TableColumnMutation) ResetTableID() {
	m.tablemeta = nil
}

// SetTablemetaID sets the "tablemeta" edge to the TableMeta entity by id.
func (m *TableColumnMutation) SetTablemetaID(id int) {
	m.tablemeta = &id
}

// ClearTablemeta clears the "tablemeta" edge to the TableMeta entity.
func (m *TableColumnMutation) ClearTablemeta() {
	m.clearedtablemeta = true
	m.clearedFields[tablecolumn.FieldTableID] = struct{}{}
}

// TablemetaCleared reports if the "tablemeta" edge to the TableMeta entity was cleared.
func (m *TableColumnMutation) TablemetaCleared() bool {
	return m.clearedtablemeta
}

// TablemetaID returns the "tablemeta" edge ID in the mutation.
func (m *TableColumnMutation) TablemetaID() (id int, exists bool) {
	if m.tablemeta != nil {
		return *m.tablemeta, true
	}
	return
}

// TablemetaIDs returns the "tablemeta" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// TablemetaID instead. It exists only for internal usage by the builders.
func (m *TableColumnMutation) TablemetaIDs() (ids []int) {
	if id := m.tablemeta; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTablemeta resets all changes to the "tablemeta" edge.
func (m *TableColumnMutation) ResetTablemeta() {
	m.tablemeta = nil
	m.clearedtablemeta = false
}

// Where appends a list predicates to the TableColumnMutation builder.
func (m *TableColumnMutation) Where(ps ...predicate.TableColumn) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TableColumnMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TableColumnMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TableColumn, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TableColumnMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TableColumnMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TableColumn).
func (m *TableColumnMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TableColumnMutation) Fields() []string {
	fields := make([]string, 0, 10)
	if m.created_at != nil {
		fields = append(fields, tablecolumn.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, tablecolumn.FieldUpdatedAt)
	}
	if m.nanoid != nil {
		fields = append(fields, tablecolumn.FieldNanoid)
	}
	if m.name != nil {
		fields = append(fields, tablecolumn.FieldName)
	}
	if m.description != nil {
		fields = append(fields, tablecolumn.FieldDescription)
	}
	if m._type != nil {
		fields = append(fields, tablecolumn.FieldType)
	}
	if m.fill_mode != nil {
		fields = append(fields, tablecolumn.FieldFillMode)
	}
	if m.source != nil {
		fields = append(fields, tablecolumn.FieldSource)
	}
	if m.context_length != nil {
		fields = append(fields, tablecolumn.FieldContextLength)
	}
	if m.tablemeta != nil {
		fields = append(fields, tablecolumn.FieldTableID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TableColumnMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tablecolumn.FieldCreatedAt:
		return m.CreatedAt()
	case tablecolumn.FieldUpdatedAt:
		return m.UpdatedAt()
	case tablecolumn.FieldNanoid:
		return m.Nanoid()
	case tablecolumn.FieldName:
		return m.Name()
	case tablecolumn.FieldDescription:
		return m.Description()
	case tablecolumn.FieldType:
		return m.GetType()
	case tablecolumn.FieldFillMode:
		return m.FillMode()
	case tablecolumn.FieldSource:
		return m.Source()
	case tablecolumn.FieldContextLength:
		return m.ContextLength()
	case tablecolumn.FieldTableID:
		return m.TableID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TableColumnMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tablecolumn.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case tablecolumn.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case tablecolumn.FieldNanoid:
		return m.OldNanoid(ctx)
	case tablecolumn.FieldName:
		return m.OldName(ctx)
	case tablecolumn.FieldDescription:
		return m.OldDescription(ctx)
	case tablecolumn.FieldType:
		return m.OldType(ctx)
	case tablecolumn.FieldFillMode:
		return m.OldFillMode(ctx)
	case tablecolumn.FieldSource:
		return m.OldSource(ctx)
	case tablecolumn.FieldContextLength:
		return m.OldContextLength(ctx)
	case tablecolumn.FieldTableID:
		return m.OldTableID(ctx)
	}
	return nil, fmt.Errorf("unknown TableColumn field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TableColumnMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tablecolumn.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case tablecolumn.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case tablecolumn.FieldNanoid:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNanoid(v)
		return nil
	case tablecolumn.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case tablecolumn.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case tablecolumn.FieldType:
		v, ok := value.(tablecolumn.Type)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case tablecolumn.FieldFillMode:
		v, ok := value.(tablecolumn.FillMode)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFillMode(v)
		return nil
	case tablecolumn.FieldSource:
		v, ok := value.(json.RawMessage)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSource(v)
		return nil
	case tablecolumn.FieldContextLength:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContextLength(v)
		return nil
	case tablecolumn.FieldTableID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTableID(v)
		return nil
	}
	return fmt.Errorf("unknown TableColumn field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TableColumnMutation) AddedFields() []string {
	var fields []string
	if m.addcontext_length != nil {
		fields = append(fields, tablecolumn.FieldContextLength)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TableColumnMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case tablecolumn.FieldContextLength:
		return m.AddedContextLength()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TableColumnMutation) AddField(name string, value ent.Value) error {
	switch name {
	case tablecolumn.FieldContextLength:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddContextLength(v)
		return nil
	}
	return fmt.Errorf("unknown TableColumn numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TableColumnMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(tablecolumn.FieldCreatedAt) {
		fields = append(fields, tablecolumn.FieldCreatedAt)
	}
	if m.FieldCleared(tablecolumn.FieldUpdatedAt) {
		fields = append(fields, tablecolumn.FieldUpdatedAt)
	}
	if m.FieldCleared(tablecolumn.FieldNanoid) {
		fields = append(fields, tablecolumn.FieldNanoid)
	}
	if m.FieldCleared(tablecolumn.FieldDescription) {
		fields = append(fields, tablecolumn.FieldDescription)
	}
	if m.FieldCleared(tablecolumn.FieldSource) {
		fields = append(fields, tablecolumn.FieldSource)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TableColumnMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TableColumnMutation) ClearField(name string) error {
	switch name {
	case tablecolumn.FieldCreatedAt:
		m.ClearCreatedAt()
		return nil
	case tablecolumn.FieldUpdatedAt:
		m.ClearUpdatedAt()
		return nil
	case tablecolumn.FieldNanoid:
		m.ClearNanoid()
		return nil
	case tablecolumn.FieldDescription:
		m.ClearDescription()
		return nil
	case tablecolumn.FieldSource:
		m.ClearSource()
		return nil
	}
	return fmt.Errorf("unknown TableColumn nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TableColumnMutation) ResetField(name string) error {
	switch name {
	case tablecolumn.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case tablecolumn.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case tablecolumn.FieldNanoid:
		m.ResetNanoid()
		return nil
	case tablecolumn.FieldName:
		m.ResetName()
		return nil
	case tablecolumn.FieldDescription:
		m.ResetDescription()
		return nil
	case tablecolumn.FieldType:
		m.ResetType()
		return nil
	case tablecolumn.FieldFillMode:
		m.ResetFillMode()
		return nil
	case tablecolumn.FieldSource:
		m.ResetSource()
		return nil
	case tablecolumn.FieldContextLength:
		m.ResetContextLength()
		return nil
	case tablecolumn.FieldTableID:
		m.ResetTableID()
		return nil
	}
	return fmt.Errorf("unknown TableColumn field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TableColumnMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.tablemeta != nil {
		edges = append(edges, tablecolumn.EdgeTablemeta)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TableColumnMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case tablecolumn.EdgeTablemeta:
		if id := m.tablemeta; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TableColumnMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TableColumnMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TableColumnMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedtablemeta {
		edges = append(edges, tablecolumn.EdgeTablemeta)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TableColumnMutation) EdgeCleared(name string) bool {
	switch name {
	case tablecolumn.EdgeTablemeta:
		return m.clearedtablemeta
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TableColumnMutation) ClearEdge(name string) error {
	switch name {
	case tablecolumn.EdgeTablemeta:
		m.ClearTablemeta()
		return nil
	}
	return fmt.Errorf("unknown TableColumn unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TableColumnMutation) ResetEdge(name string) error {
	switch name {
	case tablecolumn.EdgeTablemeta:
		m.ResetTablemeta()
		return nil
	}
	return fmt.Errorf("unknown TableColumn edge %s", name)
}

// TableMetaMutation represents an operation that mutates the TableMeta nodes in the graph.
type TableMetaMutation struct {
	config
	op             Op
	typ            string
	id             *int
	created_at     *time.Time
	updated_at     *time.Time
	nanoid         *string
	name           *string
	description    *string
	model          *string
	clearedFields  map[string]struct{}
	columns        map[int]struct{}
	removedcolumns map[int]struct{}
	clearedcolumns bool
	rows           map[int]struct{}
	removedrows    map[int]struct{}
	clearedrows    bool
	done           bool
	oldValue       func(context.Context) (*TableMeta, error)
	predicates     []predicate.TableMeta
}

var _ ent.Mutation = (*TableMetaMutation)(nil)

// tablemetaOption allows management of the mutation configuration using functional options.
type tablemetaOption func(*TableMetaMutation)

// newTableMetaMutation creates new mutation for the TableMeta entity.
func newTableMetaMutation(c config, op Op, opts ...tablemetaOption) *TableMetaMutation {
	m := &TableMetaMutation{
		config:        c,
		op:            op,
		typ:           TypeTableMeta,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTableMetaID sets the ID field of the mutation.
func withTableMetaID(id int) tablemetaOption {
	return func(m *TableMetaMutation) {
		var (
			err   error
			once  sync.Once
			value *TableMeta
		)
		m.oldValue = func(ctx context.Context) (*TableMeta, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TableMeta.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTableMeta sets the old TableMeta of the mutation.
func withTableMeta(node *TableMeta) tablemetaOption {
	return func(m *TableMetaMutation) {
		m.oldValue = func(context.Context) (*TableMeta, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TableMetaMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TableMetaMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TableMetaMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TableMetaMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TableMeta.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *TableMetaMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *TableMetaMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the TableMeta entity.
// If the TableMeta object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableMetaMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ClearCreatedAt clears the value of the "created_at" field.
func (m *TableMetaMutation) ClearCreatedAt() {
	m.created_at = nil
	m.clearedFields[tablemeta.FieldCreatedAt] = struct{}{}
}

// CreatedAtCleared returns if the "created_at" field was cleared in this mutation.
func (m *TableMetaMutation) CreatedAtCleared() bool {
	_, ok := m.clearedFields[tablemeta.FieldCreatedAt]
	return ok
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *TableMetaMutation) ResetCreatedAt() {
	m.created_at = nil
	delete(m.clearedFields, tablemeta.FieldCreatedAt)
}

// SetUpdatedAt sets the "updated_at" field.
func (m *TableMetaMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *TableMetaMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the TableMeta entity.
// If the TableMeta object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableMetaMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (m *TableMetaMutation) ClearUpdatedAt() {
	m.updated_at = nil
	m.clearedFields[tablemeta.FieldUpdatedAt] = struct{}{}
}

// UpdatedAtCleared returns if the "updated_at" field was cleared in this mutation.
func (m *TableMetaMutation) UpdatedAtCleared() bool {
	_, ok := m.clearedFields[tablemeta.FieldUpdatedAt]
	return ok
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *TableMetaMutation) ResetUpdatedAt() {
	m.updated_at = nil
	delete(m.clearedFields, tablemeta.FieldUpdatedAt)
}

// SetNanoid sets the "nanoid" field.
func (m *TableMetaMutation) SetNanoid(s string) {
	m.nanoid = &s
}

// Nanoid returns the value of the "nanoid" field in the mutation.
func (m *TableMetaMutation) Nanoid() (r string, exists bool) {
	v := m.nanoid
	if v == nil {
		return
	}
	return *v, true
}

// OldNanoid returns the old "nanoid" field's value of the TableMeta entity.
// If the TableMeta object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableMetaMutation) OldNanoid(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNanoid is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNanoid requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNanoid: %w", err)
	}
	return oldValue.Nanoid, nil
}

// ClearNanoid clears the value of the "nanoid" field.
func (m *TableMetaMutation) ClearNanoid() {
	m.nanoid = nil
	m.clearedFields[tablemeta.FieldNanoid] = struct{}{}
}

// NanoidCleared returns if the "nanoid" field was cleared in this mutation.
func (m *TableMetaMutation) NanoidCleared() bool {
	_, ok := m.clearedFields[tablemeta.FieldNanoid]
	return ok
}

// ResetNanoid resets all changes to the "nanoid" field.
func (m *TableMetaMutation) ResetNanoid() {
	m.nanoid = nil
	delete(m.clearedFields, tablemeta.FieldNanoid)
}

// SetName sets the "name" field.
func (m *TableMetaMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *TableMetaMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the TableMeta entity.
// If the TableMeta object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableMetaMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *TableMetaMutation) ResetName() {
	m.name = nil
}

// SetDescription sets the "description" field.
func (m *TableMetaMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *TableMetaMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the TableMeta entity.
// If the TableMeta object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableMetaMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *TableMetaMutation) ResetDescription() {
	m.description = nil
}

// SetModel sets the "model" field.
func (m *TableMetaMutation) SetModel(s string) {
	m.model = &s
}

// Model returns the value of the "model" field in the mutation.
func (m *TableMetaMutation) Model() (r string, exists bool) {
	v := m.model
	if v == nil {
		return
	}
	return *v, true
}

// OldModel returns the old "model" field's value of the TableMeta entity.
// If the TableMeta object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableMetaMutation) OldModel(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldModel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldModel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldModel: %w", err)
	}
	return oldValue.Model, nil
}

// ResetModel resets all changes to the "model" field.
func (m *TableMetaMutation) ResetModel() {
	m.model = nil
}

// AddColumnIDs adds the "columns" edge to the TableColumn entity by ids.
func (m *TableMetaMutation) AddColumnIDs(ids ...int) {
	if m.columns == nil {
		m.columns = make(map[int]struct{})
	}
	for i := range ids {
		m.columns[ids[i]] = struct{}{}
	}
}

// ClearColumns clears the "columns" edge to the TableColumn entity.
func (m *TableMetaMutation) ClearColumns() {
	m.clearedcolumns = true
}

// ColumnsCleared reports if the "columns" edge to the TableColumn entity was cleared.
func (m *TableMetaMutation) ColumnsCleared() bool {
	return m.clearedcolumns
}

// RemoveColumnIDs removes the "columns" edge to the TableColumn entity by IDs.
func (m *TableMetaMutation) RemoveColumnIDs(ids ...int) {
	if m.removedcolumns == nil {
		m.removedcolumns = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.columns, ids[i])
		m.removedcolumns[ids[i]] = struct{}{}
	}
}

// RemovedColumns returns the removed IDs of the "columns" edge to the TableColumn entity.
func (m *TableMetaMutation) RemovedColumnsIDs() (ids []int) {
	for id := range m.removedcolumns {
		ids = append(ids, id)
	}
	return
}

// ColumnsIDs returns the "columns" edge IDs in the mutation.
func (m *TableMetaMutation) ColumnsIDs() (ids []int) {
	for id := range m.columns {
		ids = append(ids, id)
	}
	return
}

// ResetColumns resets all changes to the "columns" edge.
func (m *TableMetaMutation) ResetColumns() {
	m.columns = nil
	m.clearedcolumns = false
	m.removedcolumns = nil
}

// AddRowIDs adds the "rows" edge to the TableRow entity by ids.
func (m *TableMetaMutation) AddRowIDs(ids ...int) {
	if m.rows == nil {
		m.rows = make(map[int]struct{})
	}
	for i := range ids {
		m.rows[ids[i]] = struct{}{}
	}
}

// ClearRows clears the "rows" edge to the TableRow entity.
func (m *TableMetaMutation) ClearRows() {
	m.clearedrows = true
}

// RowsCleared reports if the "rows" edge to the TableRow entity was cleared.
func (m *TableMetaMutation) RowsCleared() bool {
	return m.clearedrows
}

// RemoveRowIDs removes the "rows" edge to the TableRow entity by IDs.
func (m *TableMetaMutation) RemoveRowIDs(ids ...int) {
	if m.removedrows == nil {
		m.removedrows = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.rows, ids[i])
		m.removedrows[ids[i]] = struct{}{}
	}
}

// RemovedRows returns the removed IDs of the "rows" edge to the TableRow entity.
func (m *TableMetaMutation) RemovedRowsIDs() (ids []int) {
	for id := range m.removedrows {
		ids = append(ids, id)
	}
	return
}

// RowsIDs returns the "rows" edge IDs in the mutation.
func (m *TableMetaMutation) RowsIDs() (ids []int) {
	for id := range m.rows {
		ids = append(ids, id)
	}
	return
}

// ResetRows resets all changes to the "rows" edge.
func (m *TableMetaMutation) ResetRows() {
	m.rows = nil
	m.clearedrows = false
	m.removedrows = nil
}

// Where appends a list predicates to the TableMetaMutation builder.
func (m *TableMetaMutation) Where(ps ...predicate.TableMeta) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TableMetaMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TableMetaMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TableMeta, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TableMetaMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TableMetaMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TableMeta).
func (m *TableMetaMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TableMetaMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.created_at != nil {
		fields = append(fields, tablemeta.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, tablemeta.FieldUpdatedAt)
	}
	if m.nanoid != nil {
		fields = append(fields, tablemeta.FieldNanoid)
	}
	if m.name != nil {
		fields = append(fields, tablemeta.FieldName)
	}
	if m.description != nil {
		fields = append(fields, tablemeta.FieldDescription)
	}
	if m.model != nil {
		fields = append(fields, tablemeta.FieldModel)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TableMetaMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tablemeta.FieldCreatedAt:
		return m.CreatedAt()
	case tablemeta.FieldUpdatedAt:
		return m.UpdatedAt()
	case tablemeta.FieldNanoid:
		return m.Nanoid()
	case tablemeta.FieldName:
		return m.Name()
	case tablemeta.FieldDescription:
		return m.Description()
	case tablemeta.FieldModel:
		return m.Model()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TableMetaMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tablemeta.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case tablemeta.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case tablemeta.FieldNanoid:
		return m.OldNanoid(ctx)
	case tablemeta.FieldName:
		return m.OldName(ctx)
	case tablemeta.FieldDescription:
		return m.OldDescription(ctx)
	case tablemeta.FieldModel:
		return m.OldModel(ctx)
	}
	return nil, fmt.Errorf("unknown TableMeta field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TableMetaMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tablemeta.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case tablemeta.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case tablemeta.FieldNanoid:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNanoid(v)
		return nil
	case tablemeta.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case tablemeta.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case tablemeta.FieldModel:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetModel(v)
		return nil
	}
	return fmt.Errorf("unknown TableMeta field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TableMetaMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TableMetaMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TableMetaMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TableMeta numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TableMetaMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(tablemeta.FieldCreatedAt) {
		fields = append(fields, tablemeta.FieldCreatedAt)
	}
	if m.FieldCleared(tablemeta.FieldUpdatedAt) {
		fields = append(fields, tablemeta.FieldUpdatedAt)
	}
	if m.FieldCleared(tablemeta.FieldNanoid) {
		fields = append(fields, tablemeta.FieldNanoid)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TableMetaMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TableMetaMutation) ClearField(name string) error {
	switch name {
	case tablemeta.FieldCreatedAt:
		m.ClearCreatedAt()
		return nil
	case tablemeta.FieldUpdatedAt:
		m.ClearUpdatedAt()
		return nil
	case tablemeta.FieldNanoid:
		m.ClearNanoid()
		return nil
	}
	return fmt.Errorf("unknown TableMeta nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TableMetaMutation) ResetField(name string) error {
	switch name {
	case tablemeta.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case tablemeta.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case tablemeta.FieldNanoid:
		m.ResetNanoid()
		return nil
	case tablemeta.FieldName:
		m.ResetName()
		return nil
	case tablemeta.FieldDescription:
		m.ResetDescription()
		return nil
	case tablemeta.FieldModel:
		m.ResetModel()
		return nil
	}
	return fmt.Errorf("unknown TableMeta field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TableMetaMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.columns != nil {
		edges = append(edges, tablemeta.EdgeColumns)
	}
	if m.rows != nil {
		edges = append(edges, tablemeta.EdgeRows)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TableMetaMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case tablemeta.EdgeColumns:
		ids := make([]ent.Value, 0, len(m.columns))
		for id := range m.columns {
			ids = append(ids, id)
		}
		return ids
	case tablemeta.EdgeRows:
		ids := make([]ent.Value, 0, len(m.rows))
		for id := range m.rows {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TableMetaMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedcolumns != nil {
		edges = append(edges, tablemeta.EdgeColumns)
	}
	if m.removedrows != nil {
		edges = append(edges, tablemeta.EdgeRows)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TableMetaMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case tablemeta.EdgeColumns:
		ids := make([]ent.Value, 0, len(m.removedcolumns))
		for id := range m.removedcolumns {
			ids = append(ids, id)
		}
		return ids
	case tablemeta.EdgeRows:
		ids := make([]ent.Value, 0, len(m.removedrows))
		for id := range m.removedrows {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TableMetaMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedcolumns {
		edges = append(edges, tablemeta.EdgeColumns)
	}
	if m.clearedrows {
		edges = append(edges, tablemeta.EdgeRows)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TableMetaMutation) EdgeCleared(name string) bool {
	switch name {
	case tablemeta.EdgeColumns:
		return m.clearedcolumns
	case tablemeta.EdgeRows:
		return m.clearedrows
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TableMetaMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown TableMeta unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TableMetaMutation) ResetEdge(name string) error {
	switch name {
	case tablemeta.EdgeColumns:
		m.ResetColumns()
		return nil
	case tablemeta.EdgeRows:
		m.ResetRows()
		return nil
	}
	return fmt.Errorf("unknown TableMeta edge %s", name)
}

// TableRowMutation represents an operation that mutates the TableRow nodes in the graph.
type TableRowMutation struct {
	config
	op               Op
	typ              string
	id               *int
	created_at       *time.Time
	updated_at       *time.Time
	nanoid           *string
	cells            *[]*schema.CellValue
	appendcells      []*schema.CellValue
	clearedFields    map[string]struct{}
	tablemeta        *int
	clearedtablemeta bool
	done             bool
	oldValue         func(context.Context) (*TableRow, error)
	predicates       []predicate.TableRow
}

var _ ent.Mutation = (*TableRowMutation)(nil)

// tablerowOption allows management of the mutation configuration using functional options.
type tablerowOption func(*TableRowMutation)

// newTableRowMutation creates new mutation for the TableRow entity.
func newTableRowMutation(c config, op Op, opts ...tablerowOption) *TableRowMutation {
	m := &TableRowMutation{
		config:        c,
		op:            op,
		typ:           TypeTableRow,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTableRowID sets the ID field of the mutation.
func withTableRowID(id int) tablerowOption {
	return func(m *TableRowMutation) {
		var (
			err   error
			once  sync.Once
			value *TableRow
		)
		m.oldValue = func(ctx context.Context) (*TableRow, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TableRow.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTableRow sets the old TableRow of the mutation.
func withTableRow(node *TableRow) tablerowOption {
	return func(m *TableRowMutation) {
		m.oldValue = func(context.Context) (*TableRow, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TableRowMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TableRowMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TableRowMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TableRowMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TableRow.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *TableRowMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *TableRowMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the TableRow entity.
// If the TableRow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableRowMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ClearCreatedAt clears the value of the "created_at" field.
func (m *TableRowMutation) ClearCreatedAt() {
	m.created_at = nil
	m.clearedFields[tablerow.FieldCreatedAt] = struct{}{}
}

// CreatedAtCleared returns if the "created_at" field was cleared in this mutation.
func (m *TableRowMutation) CreatedAtCleared() bool {
	_, ok := m.clearedFields[tablerow.FieldCreatedAt]
	return ok
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *TableRowMutation) ResetCreatedAt() {
	m.created_at = nil
	delete(m.clearedFields, tablerow.FieldCreatedAt)
}

// SetUpdatedAt sets the "updated_at" field.
func (m *TableRowMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *TableRowMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the TableRow entity.
// If the TableRow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableRowMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (m *TableRowMutation) ClearUpdatedAt() {
	m.updated_at = nil
	m.clearedFields[tablerow.FieldUpdatedAt] = struct{}{}
}

// UpdatedAtCleared returns if the "updated_at" field was cleared in this mutation.
func (m *TableRowMutation) UpdatedAtCleared() bool {
	_, ok := m.clearedFields[tablerow.FieldUpdatedAt]
	return ok
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *TableRowMutation) ResetUpdatedAt() {
	m.updated_at = nil
	delete(m.clearedFields, tablerow.FieldUpdatedAt)
}

// SetNanoid sets the "nanoid" field.
func (m *TableRowMutation) SetNanoid(s string) {
	m.nanoid = &s
}

// Nanoid returns the value of the "nanoid" field in the mutation.
func (m *TableRowMutation) Nanoid() (r string, exists bool) {
	v := m.nanoid
	if v == nil {
		return
	}
	return *v, true
}

// OldNanoid returns the old "nanoid" field's value of the TableRow entity.
// If the TableRow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableRowMutation) OldNanoid(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNanoid is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNanoid requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNanoid: %w", err)
	}
	return oldValue.Nanoid, nil
}

// ClearNanoid clears the value of the "nanoid" field.
func (m *TableRowMutation) ClearNanoid() {
	m.nanoid = nil
	m.clearedFields[tablerow.FieldNanoid] = struct{}{}
}

// NanoidCleared returns if the "nanoid" field was cleared in this mutation.
func (m *TableRowMutation) NanoidCleared() bool {
	_, ok := m.clearedFields[tablerow.FieldNanoid]
	return ok
}

// ResetNanoid resets all changes to the "nanoid" field.
func (m *TableRowMutation) ResetNanoid() {
	m.nanoid = nil
	delete(m.clearedFields, tablerow.FieldNanoid)
}

// SetCells sets the "cells" field.
func (m *TableRowMutation) SetCells(sv []*schema.CellValue) {
	m.cells = &sv
	m.appendcells = nil
}

// Cells returns the value of the "cells" field in the mutation.
func (m *TableRowMutation) Cells() (r []*schema.CellValue, exists bool) {
	v := m.cells
	if v == nil {
		return
	}
	return *v, true
}

// OldCells returns the old "cells" field's value of the TableRow entity.
// If the TableRow object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TableRowMutation) OldCells(ctx context.Context) (v []*schema.CellValue, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCells is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCells requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCells: %w", err)
	}
	return oldValue.Cells, nil
}

// AppendCells adds sv to the "cells" field.
func (m *TableRowMutation) AppendCells(sv []*schema.CellValue) {
	m.appendcells = append(m.appendcells, sv...)
}

// AppendedCells returns the list of values that were appended to the "cells" field in this mutation.
func (m *TableRowMutation) AppendedCells() ([]*schema.CellValue, bool) {
	if len(m.appendcells) == 0 {
		return nil, false
	}
	return m.appendcells, true
}

// ClearCells clears the value of the "cells" field.
func (m *TableRowMutation) ClearCells() {
	m.cells = nil
	m.appendcells = nil
	m.clearedFields[tablerow.FieldCells] = struct{}{}
}

// CellsCleared returns if the "cells" field was cleared in this mutation.
func (m *TableRowMutation) CellsCleared() bool {
	_, ok := m.clearedFields[tablerow.FieldCells]
	return ok
}

// ResetCells resets all changes to the "cells" field.
func (m *TableRowMutation) ResetCells() {
	m.cells = nil
	m.appendcells = nil
	delete(m.clearedFields, tablerow.FieldCells)
}

// SetTablemetaID sets the "tablemeta" edge to the TableMeta entity by id.
func (m *TableRowMutation) SetTablemetaID(id int) {
	m.tablemeta = &id
}

// ClearTablemeta clears the "tablemeta" edge to the TableMeta entity.
func (m *TableRowMutation) ClearTablemeta() {
	m.clearedtablemeta = true
}

// TablemetaCleared reports if the "tablemeta" edge to the TableMeta entity was cleared.
func (m *TableRowMutation) TablemetaCleared() bool {
	return m.clearedtablemeta
}

// TablemetaID returns the "tablemeta" edge ID in the mutation.
func (m *TableRowMutation) TablemetaID() (id int, exists bool) {
	if m.tablemeta != nil {
		return *m.tablemeta, true
	}
	return
}

// TablemetaIDs returns the "tablemeta" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// TablemetaID instead. It exists only for internal usage by the builders.
func (m *TableRowMutation) TablemetaIDs() (ids []int) {
	if id := m.tablemeta; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTablemeta resets all changes to the "tablemeta" edge.
func (m *TableRowMutation) ResetTablemeta() {
	m.tablemeta = nil
	m.clearedtablemeta = false
}

// Where appends a list predicates to the TableRowMutation builder.
func (m *TableRowMutation) Where(ps ...predicate.TableRow) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TableRowMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TableRowMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.TableRow, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TableRowMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TableRowMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (TableRow).
func (m *TableRowMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TableRowMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.created_at != nil {
		fields = append(fields, tablerow.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, tablerow.FieldUpdatedAt)
	}
	if m.nanoid != nil {
		fields = append(fields, tablerow.FieldNanoid)
	}
	if m.cells != nil {
		fields = append(fields, tablerow.FieldCells)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TableRowMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case tablerow.FieldCreatedAt:
		return m.CreatedAt()
	case tablerow.FieldUpdatedAt:
		return m.UpdatedAt()
	case tablerow.FieldNanoid:
		return m.Nanoid()
	case tablerow.FieldCells:
		return m.Cells()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TableRowMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case tablerow.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case tablerow.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case tablerow.FieldNanoid:
		return m.OldNanoid(ctx)
	case tablerow.FieldCells:
		return m.OldCells(ctx)
	}
	return nil, fmt.Errorf("unknown TableRow field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TableRowMutation) SetField(name string, value ent.Value) error {
	switch name {
	case tablerow.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case tablerow.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case tablerow.FieldNanoid:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNanoid(v)
		return nil
	case tablerow.FieldCells:
		v, ok := value.([]*schema.CellValue)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCells(v)
		return nil
	}
	return fmt.Errorf("unknown TableRow field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TableRowMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TableRowMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TableRowMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TableRow numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TableRowMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(tablerow.FieldCreatedAt) {
		fields = append(fields, tablerow.FieldCreatedAt)
	}
	if m.FieldCleared(tablerow.FieldUpdatedAt) {
		fields = append(fields, tablerow.FieldUpdatedAt)
	}
	if m.FieldCleared(tablerow.FieldNanoid) {
		fields = append(fields, tablerow.FieldNanoid)
	}
	if m.FieldCleared(tablerow.FieldCells) {
		fields = append(fields, tablerow.FieldCells)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TableRowMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TableRowMutation) ClearField(name string) error {
	switch name {
	case tablerow.FieldCreatedAt:
		m.ClearCreatedAt()
		return nil
	case tablerow.FieldUpdatedAt:
		m.ClearUpdatedAt()
		return nil
	case tablerow.FieldNanoid:
		m.ClearNanoid()
		return nil
	case tablerow.FieldCells:
		m.ClearCells()
		return nil
	}
	return fmt.Errorf("unknown TableRow nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TableRowMutation) ResetField(name string) error {
	switch name {
	case tablerow.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case tablerow.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case tablerow.FieldNanoid:
		m.ResetNanoid()
		return nil
	case tablerow.FieldCells:
		m.ResetCells()
		return nil
	}
	return fmt.Errorf("unknown TableRow field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TableRowMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.tablemeta != nil {
		edges = append(edges, tablerow.EdgeTablemeta)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TableRowMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case tablerow.EdgeTablemeta:
		if id := m.tablemeta; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TableRowMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TableRowMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TableRowMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedtablemeta {
		edges = append(edges, tablerow.EdgeTablemeta)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TableRowMutation) EdgeCleared(name string) bool {
	switch name {
	case tablerow.EdgeTablemeta:
		return m.clearedtablemeta
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TableRowMutation) ClearEdge(name string) error {
	switch name {
	case tablerow.EdgeTablemeta:
		m.ClearTablemeta()
		return nil
	}
	return fmt.Errorf("unknown TableRow unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TableRowMutation) ResetEdge(name string) error {
	switch name {
	case tablerow.EdgeTablemeta:
		m.ResetTablemeta()
		return nil
	}
	return fmt.Errorf("unknown TableRow edge %s", name)
}
