// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Yiling-J/tablepilot/ent/model"
	"github.com/Yiling-J/tablepilot/ent/provider"
	"github.com/Yiling-J/tablepilot/ent/schema"
	"github.com/Yiling-J/tablepilot/ent/tablecolumn"
	"github.com/Yiling-J/tablepilot/ent/tablemeta"
	"github.com/Yiling-J/tablepilot/ent/tablerow"
	"github.com/Yiling-J/tablepilot/ent/workflow"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	modelMixin := schema.Model{}.Mixin()
	modelMixinFields0 := modelMixin[0].Fields()
	_ = modelMixinFields0
	modelFields := schema.Model{}.Fields()
	_ = modelFields
	// modelDescCreatedAt is the schema descriptor for created_at field.
	modelDescCreatedAt := modelMixinFields0[0].Descriptor()
	// model.DefaultCreatedAt holds the default value on creation for the created_at field.
	model.DefaultCreatedAt = modelDescCreatedAt.Default.(func() time.Time)
	// modelDescUpdatedAt is the schema descriptor for updated_at field.
	modelDescUpdatedAt := modelMixinFields0[1].Descriptor()
	// model.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	model.DefaultUpdatedAt = modelDescUpdatedAt.Default.(func() time.Time)
	// model.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	model.UpdateDefaultUpdatedAt = modelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// modelDescModel is the schema descriptor for model field.
	modelDescModel := modelFields[0].Descriptor()
	// model.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	model.ModelValidator = modelDescModel.Validators[0].(func(string) error)
	// modelDescDefault is the schema descriptor for default field.
	modelDescDefault := modelFields[4].Descriptor()
	// model.DefaultDefault holds the default value on creation for the default field.
	model.DefaultDefault = modelDescDefault.Default.(bool)
	// modelDescImage is the schema descriptor for image field.
	modelDescImage := modelFields[5].Descriptor()
	// model.DefaultImage holds the default value on creation for the image field.
	model.DefaultImage = modelDescImage.Default.(bool)
	providerMixin := schema.Provider{}.Mixin()
	providerMixinFields0 := providerMixin[0].Fields()
	_ = providerMixinFields0
	providerFields := schema.Provider{}.Fields()
	_ = providerFields
	// providerDescCreatedAt is the schema descriptor for created_at field.
	providerDescCreatedAt := providerMixinFields0[0].Descriptor()
	// provider.DefaultCreatedAt holds the default value on creation for the created_at field.
	provider.DefaultCreatedAt = providerDescCreatedAt.Default.(func() time.Time)
	// providerDescUpdatedAt is the schema descriptor for updated_at field.
	providerDescUpdatedAt := providerMixinFields0[1].Descriptor()
	// provider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	provider.DefaultUpdatedAt = providerDescUpdatedAt.Default.(func() time.Time)
	// provider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	provider.UpdateDefaultUpdatedAt = providerDescUpdatedAt.UpdateDefault.(func() time.Time)
	tablecolumnMixin := schema.TableColumn{}.Mixin()
	tablecolumnMixinFields0 := tablecolumnMixin[0].Fields()
	_ = tablecolumnMixinFields0
	tablecolumnFields := schema.TableColumn{}.Fields()
	_ = tablecolumnFields
	// tablecolumnDescCreatedAt is the schema descriptor for created_at field.
	tablecolumnDescCreatedAt := tablecolumnMixinFields0[0].Descriptor()
	// tablecolumn.DefaultCreatedAt holds the default value on creation for the created_at field.
	tablecolumn.DefaultCreatedAt = tablecolumnDescCreatedAt.Default.(func() time.Time)
	// tablecolumnDescUpdatedAt is the schema descriptor for updated_at field.
	tablecolumnDescUpdatedAt := tablecolumnMixinFields0[1].Descriptor()
	// tablecolumn.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tablecolumn.DefaultUpdatedAt = tablecolumnDescUpdatedAt.Default.(func() time.Time)
	// tablecolumn.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tablecolumn.UpdateDefaultUpdatedAt = tablecolumnDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tablecolumnDescName is the schema descriptor for name field.
	tablecolumnDescName := tablecolumnFields[0].Descriptor()
	// tablecolumn.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tablecolumn.NameValidator = tablecolumnDescName.Validators[0].(func(string) error)
	// tablecolumnDescContextLength is the schema descriptor for context_length field.
	tablecolumnDescContextLength := tablecolumnFields[5].Descriptor()
	// tablecolumn.DefaultContextLength holds the default value on creation for the context_length field.
	tablecolumn.DefaultContextLength = tablecolumnDescContextLength.Default.(int)
	// tablecolumnDescRandom is the schema descriptor for random field.
	tablecolumnDescRandom := tablecolumnFields[7].Descriptor()
	// tablecolumn.DefaultRandom holds the default value on creation for the random field.
	tablecolumn.DefaultRandom = tablecolumnDescRandom.Default.(bool)
	// tablecolumnDescReplacement is the schema descriptor for replacement field.
	tablecolumnDescReplacement := tablecolumnFields[8].Descriptor()
	// tablecolumn.DefaultReplacement holds the default value on creation for the replacement field.
	tablecolumn.DefaultReplacement = tablecolumnDescReplacement.Default.(bool)
	// tablecolumnDescRepeat is the schema descriptor for repeat field.
	tablecolumnDescRepeat := tablecolumnFields[9].Descriptor()
	// tablecolumn.DefaultRepeat holds the default value on creation for the repeat field.
	tablecolumn.DefaultRepeat = tablecolumnDescRepeat.Default.(int)
	// tablecolumnDescLinkedColumn is the schema descriptor for linked_column field.
	tablecolumnDescLinkedColumn := tablecolumnFields[10].Descriptor()
	// tablecolumn.DefaultLinkedColumn holds the default value on creation for the linked_column field.
	tablecolumn.DefaultLinkedColumn = tablecolumnDescLinkedColumn.Default.(string)
	// tablecolumnDescLinkedContextColumns is the schema descriptor for linked_context_columns field.
	tablecolumnDescLinkedContextColumns := tablecolumnFields[11].Descriptor()
	// tablecolumn.DefaultLinkedContextColumns holds the default value on creation for the linked_context_columns field.
	tablecolumn.DefaultLinkedContextColumns = tablecolumnDescLinkedContextColumns.Default.([]string)
	tablemetaMixin := schema.TableMeta{}.Mixin()
	tablemetaMixinFields0 := tablemetaMixin[0].Fields()
	_ = tablemetaMixinFields0
	tablemetaFields := schema.TableMeta{}.Fields()
	_ = tablemetaFields
	// tablemetaDescCreatedAt is the schema descriptor for created_at field.
	tablemetaDescCreatedAt := tablemetaMixinFields0[0].Descriptor()
	// tablemeta.DefaultCreatedAt holds the default value on creation for the created_at field.
	tablemeta.DefaultCreatedAt = tablemetaDescCreatedAt.Default.(func() time.Time)
	// tablemetaDescUpdatedAt is the schema descriptor for updated_at field.
	tablemetaDescUpdatedAt := tablemetaMixinFields0[1].Descriptor()
	// tablemeta.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tablemeta.DefaultUpdatedAt = tablemetaDescUpdatedAt.Default.(func() time.Time)
	// tablemeta.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tablemeta.UpdateDefaultUpdatedAt = tablemetaDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tablemetaDescName is the schema descriptor for name field.
	tablemetaDescName := tablemetaFields[0].Descriptor()
	// tablemeta.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tablemeta.NameValidator = func() func(string) error {
		validators := tablemetaDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tablemetaDescDescription is the schema descriptor for description field.
	tablemetaDescDescription := tablemetaFields[1].Descriptor()
	// tablemeta.DefaultDescription holds the default value on creation for the description field.
	tablemeta.DefaultDescription = tablemetaDescDescription.Default.(string)
	// tablemetaDescModel is the schema descriptor for model field.
	tablemetaDescModel := tablemetaFields[2].Descriptor()
	// tablemeta.DefaultModel holds the default value on creation for the model field.
	tablemeta.DefaultModel = tablemetaDescModel.Default.(string)
	tablerowMixin := schema.TableRow{}.Mixin()
	tablerowMixinFields0 := tablerowMixin[0].Fields()
	_ = tablerowMixinFields0
	tablerowFields := schema.TableRow{}.Fields()
	_ = tablerowFields
	// tablerowDescCreatedAt is the schema descriptor for created_at field.
	tablerowDescCreatedAt := tablerowMixinFields0[0].Descriptor()
	// tablerow.DefaultCreatedAt holds the default value on creation for the created_at field.
	tablerow.DefaultCreatedAt = tablerowDescCreatedAt.Default.(func() time.Time)
	// tablerowDescUpdatedAt is the schema descriptor for updated_at field.
	tablerowDescUpdatedAt := tablerowMixinFields0[1].Descriptor()
	// tablerow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tablerow.DefaultUpdatedAt = tablerowDescUpdatedAt.Default.(func() time.Time)
	// tablerow.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tablerow.UpdateDefaultUpdatedAt = tablerowDescUpdatedAt.UpdateDefault.(func() time.Time)
	workflowMixin := schema.Workflow{}.Mixin()
	workflowMixinFields0 := workflowMixin[0].Fields()
	_ = workflowMixinFields0
	workflowFields := schema.Workflow{}.Fields()
	_ = workflowFields
	// workflowDescCreatedAt is the schema descriptor for created_at field.
	workflowDescCreatedAt := workflowMixinFields0[0].Descriptor()
	// workflow.DefaultCreatedAt holds the default value on creation for the created_at field.
	workflow.DefaultCreatedAt = workflowDescCreatedAt.Default.(func() time.Time)
	// workflowDescUpdatedAt is the schema descriptor for updated_at field.
	workflowDescUpdatedAt := workflowMixinFields0[1].Descriptor()
	// workflow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workflow.DefaultUpdatedAt = workflowDescUpdatedAt.Default.(func() time.Time)
	// workflow.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workflow.UpdateDefaultUpdatedAt = workflowDescUpdatedAt.UpdateDefault.(func() time.Time)
	// workflowDescName is the schema descriptor for name field.
	workflowDescName := workflowFields[0].Descriptor()
	// workflow.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workflow.NameValidator = workflowDescName.Validators[0].(func(string) error)
}
