// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Yiling-J/tablepilot/ent/schema"
	"github.com/Yiling-J/tablepilot/ent/tablemeta"
	"github.com/Yiling-J/tablepilot/ent/tablerow"
)

// TableRow is the model entity for the TableRow schema.
type TableRow struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Nanoid holds the value of the "nanoid" field.
	Nanoid string `json:"nanoid,omitempty"`
	// Cells holds the value of the "cells" field.
	Cells []*schema.CellValue `json:"cells,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TableRowQuery when eager-loading is set.
	Edges           TableRowEdges `json:"edges"`
	table_meta_rows *int
	selectValues    sql.SelectValues
}

// TableRowEdges holds the relations/edges for other nodes in the graph.
type TableRowEdges struct {
	// Tablemeta holds the value of the tablemeta edge.
	Tablemeta *TableMeta `json:"tablemeta,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TablemetaOrErr returns the Tablemeta value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TableRowEdges) TablemetaOrErr() (*TableMeta, error) {
	if e.Tablemeta != nil {
		return e.Tablemeta, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tablemeta.Label}
	}
	return nil, &NotLoadedError{edge: "tablemeta"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TableRow) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tablerow.FieldCells:
			values[i] = new([]byte)
		case tablerow.FieldID:
			values[i] = new(sql.NullInt64)
		case tablerow.FieldNanoid:
			values[i] = new(sql.NullString)
		case tablerow.FieldCreatedAt, tablerow.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case tablerow.ForeignKeys[0]: // table_meta_rows
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TableRow fields.
func (tr *TableRow) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tablerow.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tr.ID = int(value.Int64)
		case tablerow.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tr.CreatedAt = value.Time
			}
		case tablerow.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				tr.UpdatedAt = value.Time
			}
		case tablerow.FieldNanoid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nanoid", values[i])
			} else if value.Valid {
				tr.Nanoid = value.String
			}
		case tablerow.FieldCells:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field cells", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tr.Cells); err != nil {
					return fmt.Errorf("unmarshal field cells: %w", err)
				}
			}
		case tablerow.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field table_meta_rows", value)
			} else if value.Valid {
				tr.table_meta_rows = new(int)
				*tr.table_meta_rows = int(value.Int64)
			}
		default:
			tr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TableRow.
// This includes values selected through modifiers, order, etc.
func (tr *TableRow) Value(name string) (ent.Value, error) {
	return tr.selectValues.Get(name)
}

// QueryTablemeta queries the "tablemeta" edge of the TableRow entity.
func (tr *TableRow) QueryTablemeta() *TableMetaQuery {
	return NewTableRowClient(tr.config).QueryTablemeta(tr)
}

// Update returns a builder for updating this TableRow.
// Note that you need to call TableRow.Unwrap() before calling this method if this TableRow
// was returned from a transaction, and the transaction was committed or rolled back.
func (tr *TableRow) Update() *TableRowUpdateOne {
	return NewTableRowClient(tr.config).UpdateOne(tr)
}

// Unwrap unwraps the TableRow entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tr *TableRow) Unwrap() *TableRow {
	_tx, ok := tr.config.driver.(*txDriver)
	if !ok {
		panic("ent: TableRow is not a transactional entity")
	}
	tr.config.driver = _tx.drv
	return tr
}

// String implements the fmt.Stringer.
func (tr *TableRow) String() string {
	var builder strings.Builder
	builder.WriteString("TableRow(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tr.ID))
	builder.WriteString("created_at=")
	builder.WriteString(tr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(tr.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("nanoid=")
	builder.WriteString(tr.Nanoid)
	builder.WriteString(", ")
	builder.WriteString("cells=")
	builder.WriteString(fmt.Sprintf("%v", tr.Cells))
	builder.WriteByte(')')
	return builder.String()
}

// TableRows is a parsable slice of TableRow.
type TableRows []*TableRow
