// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Yiling-J/tablepilot/ent/predicate"
	"github.com/Yiling-J/tablepilot/ent/schema"
	"github.com/Yiling-J/tablepilot/ent/tablemeta"
	"github.com/Yiling-J/tablepilot/ent/tablerow"
)

// TableRowUpdate is the builder for updating TableRow entities.
type TableRowUpdate struct {
	config
	hooks     []Hook
	mutation  *TableRowMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TableRowUpdate builder.
func (tru *TableRowUpdate) Where(ps ...predicate.TableRow) *TableRowUpdate {
	tru.mutation.Where(ps...)
	return tru
}

// SetUpdatedAt sets the "updated_at" field.
func (tru *TableRowUpdate) SetUpdatedAt(t time.Time) *TableRowUpdate {
	tru.mutation.SetUpdatedAt(t)
	return tru
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (tru *TableRowUpdate) ClearUpdatedAt() *TableRowUpdate {
	tru.mutation.ClearUpdatedAt()
	return tru
}

// SetNanoid sets the "nanoid" field.
func (tru *TableRowUpdate) SetNanoid(s string) *TableRowUpdate {
	tru.mutation.SetNanoid(s)
	return tru
}

// SetNillableNanoid sets the "nanoid" field if the given value is not nil.
func (tru *TableRowUpdate) SetNillableNanoid(s *string) *TableRowUpdate {
	if s != nil {
		tru.SetNanoid(*s)
	}
	return tru
}

// ClearNanoid clears the value of the "nanoid" field.
func (tru *TableRowUpdate) ClearNanoid() *TableRowUpdate {
	tru.mutation.ClearNanoid()
	return tru
}

// SetCells sets the "cells" field.
func (tru *TableRowUpdate) SetCells(sv []*schema.CellValue) *TableRowUpdate {
	tru.mutation.SetCells(sv)
	return tru
}

// AppendCells appends sv to the "cells" field.
func (tru *TableRowUpdate) AppendCells(sv []*schema.CellValue) *TableRowUpdate {
	tru.mutation.AppendCells(sv)
	return tru
}

// ClearCells clears the value of the "cells" field.
func (tru *TableRowUpdate) ClearCells() *TableRowUpdate {
	tru.mutation.ClearCells()
	return tru
}

// SetTablemetaID sets the "tablemeta" edge to the TableMeta entity by ID.
func (tru *TableRowUpdate) SetTablemetaID(id int) *TableRowUpdate {
	tru.mutation.SetTablemetaID(id)
	return tru
}

// SetTablemeta sets the "tablemeta" edge to the TableMeta entity.
func (tru *TableRowUpdate) SetTablemeta(t *TableMeta) *TableRowUpdate {
	return tru.SetTablemetaID(t.ID)
}

// Mutation returns the TableRowMutation object of the builder.
func (tru *TableRowUpdate) Mutation() *TableRowMutation {
	return tru.mutation
}

// ClearTablemeta clears the "tablemeta" edge to the TableMeta entity.
func (tru *TableRowUpdate) ClearTablemeta() *TableRowUpdate {
	tru.mutation.ClearTablemeta()
	return tru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tru *TableRowUpdate) Save(ctx context.Context) (int, error) {
	tru.defaults()
	return withHooks(ctx, tru.sqlSave, tru.mutation, tru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tru *TableRowUpdate) SaveX(ctx context.Context) int {
	affected, err := tru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tru *TableRowUpdate) Exec(ctx context.Context) error {
	_, err := tru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tru *TableRowUpdate) ExecX(ctx context.Context) {
	if err := tru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tru *TableRowUpdate) defaults() {
	if _, ok := tru.mutation.UpdatedAt(); !ok && !tru.mutation.UpdatedAtCleared() {
		v := tablerow.UpdateDefaultUpdatedAt()
		tru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tru *TableRowUpdate) check() error {
	if tru.mutation.TablemetaCleared() && len(tru.mutation.TablemetaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TableRow.tablemeta"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tru *TableRowUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TableRowUpdate {
	tru.modifiers = append(tru.modifiers, modifiers...)
	return tru
}

func (tru *TableRowUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tablerow.Table, tablerow.Columns, sqlgraph.NewFieldSpec(tablerow.FieldID, field.TypeInt))
	if ps := tru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if tru.mutation.CreatedAtCleared() {
		_spec.ClearField(tablerow.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := tru.mutation.UpdatedAt(); ok {
		_spec.SetField(tablerow.FieldUpdatedAt, field.TypeTime, value)
	}
	if tru.mutation.UpdatedAtCleared() {
		_spec.ClearField(tablerow.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := tru.mutation.Nanoid(); ok {
		_spec.SetField(tablerow.FieldNanoid, field.TypeString, value)
	}
	if tru.mutation.NanoidCleared() {
		_spec.ClearField(tablerow.FieldNanoid, field.TypeString)
	}
	if value, ok := tru.mutation.Cells(); ok {
		_spec.SetField(tablerow.FieldCells, field.TypeJSON, value)
	}
	if value, ok := tru.mutation.AppendedCells(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tablerow.FieldCells, value)
		})
	}
	if tru.mutation.CellsCleared() {
		_spec.ClearField(tablerow.FieldCells, field.TypeJSON)
	}
	if tru.mutation.TablemetaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tablerow.TablemetaTable,
			Columns: []string{tablerow.TablemetaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablemeta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tru.mutation.TablemetaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tablerow.TablemetaTable,
			Columns: []string{tablerow.TablemetaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablemeta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tru.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, tru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tablerow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tru.mutation.done = true
	return n, nil
}

// TableRowUpdateOne is the builder for updating a single TableRow entity.
type TableRowUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TableRowMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (truo *TableRowUpdateOne) SetUpdatedAt(t time.Time) *TableRowUpdateOne {
	truo.mutation.SetUpdatedAt(t)
	return truo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (truo *TableRowUpdateOne) ClearUpdatedAt() *TableRowUpdateOne {
	truo.mutation.ClearUpdatedAt()
	return truo
}

// SetNanoid sets the "nanoid" field.
func (truo *TableRowUpdateOne) SetNanoid(s string) *TableRowUpdateOne {
	truo.mutation.SetNanoid(s)
	return truo
}

// SetNillableNanoid sets the "nanoid" field if the given value is not nil.
func (truo *TableRowUpdateOne) SetNillableNanoid(s *string) *TableRowUpdateOne {
	if s != nil {
		truo.SetNanoid(*s)
	}
	return truo
}

// ClearNanoid clears the value of the "nanoid" field.
func (truo *TableRowUpdateOne) ClearNanoid() *TableRowUpdateOne {
	truo.mutation.ClearNanoid()
	return truo
}

// SetCells sets the "cells" field.
func (truo *TableRowUpdateOne) SetCells(sv []*schema.CellValue) *TableRowUpdateOne {
	truo.mutation.SetCells(sv)
	return truo
}

// AppendCells appends sv to the "cells" field.
func (truo *TableRowUpdateOne) AppendCells(sv []*schema.CellValue) *TableRowUpdateOne {
	truo.mutation.AppendCells(sv)
	return truo
}

// ClearCells clears the value of the "cells" field.
func (truo *TableRowUpdateOne) ClearCells() *TableRowUpdateOne {
	truo.mutation.ClearCells()
	return truo
}

// SetTablemetaID sets the "tablemeta" edge to the TableMeta entity by ID.
func (truo *TableRowUpdateOne) SetTablemetaID(id int) *TableRowUpdateOne {
	truo.mutation.SetTablemetaID(id)
	return truo
}

// SetTablemeta sets the "tablemeta" edge to the TableMeta entity.
func (truo *TableRowUpdateOne) SetTablemeta(t *TableMeta) *TableRowUpdateOne {
	return truo.SetTablemetaID(t.ID)
}

// Mutation returns the TableRowMutation object of the builder.
func (truo *TableRowUpdateOne) Mutation() *TableRowMutation {
	return truo.mutation
}

// ClearTablemeta clears the "tablemeta" edge to the TableMeta entity.
func (truo *TableRowUpdateOne) ClearTablemeta() *TableRowUpdateOne {
	truo.mutation.ClearTablemeta()
	return truo
}

// Where appends a list predicates to the TableRowUpdate builder.
func (truo *TableRowUpdateOne) Where(ps ...predicate.TableRow) *TableRowUpdateOne {
	truo.mutation.Where(ps...)
	return truo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (truo *TableRowUpdateOne) Select(field string, fields ...string) *TableRowUpdateOne {
	truo.fields = append([]string{field}, fields...)
	return truo
}

// Save executes the query and returns the updated TableRow entity.
func (truo *TableRowUpdateOne) Save(ctx context.Context) (*TableRow, error) {
	truo.defaults()
	return withHooks(ctx, truo.sqlSave, truo.mutation, truo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (truo *TableRowUpdateOne) SaveX(ctx context.Context) *TableRow {
	node, err := truo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (truo *TableRowUpdateOne) Exec(ctx context.Context) error {
	_, err := truo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (truo *TableRowUpdateOne) ExecX(ctx context.Context) {
	if err := truo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (truo *TableRowUpdateOne) defaults() {
	if _, ok := truo.mutation.UpdatedAt(); !ok && !truo.mutation.UpdatedAtCleared() {
		v := tablerow.UpdateDefaultUpdatedAt()
		truo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (truo *TableRowUpdateOne) check() error {
	if truo.mutation.TablemetaCleared() && len(truo.mutation.TablemetaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TableRow.tablemeta"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (truo *TableRowUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TableRowUpdateOne {
	truo.modifiers = append(truo.modifiers, modifiers...)
	return truo
}

func (truo *TableRowUpdateOne) sqlSave(ctx context.Context) (_node *TableRow, err error) {
	if err := truo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tablerow.Table, tablerow.Columns, sqlgraph.NewFieldSpec(tablerow.FieldID, field.TypeInt))
	id, ok := truo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TableRow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := truo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tablerow.FieldID)
		for _, f := range fields {
			if !tablerow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tablerow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := truo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if truo.mutation.CreatedAtCleared() {
		_spec.ClearField(tablerow.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := truo.mutation.UpdatedAt(); ok {
		_spec.SetField(tablerow.FieldUpdatedAt, field.TypeTime, value)
	}
	if truo.mutation.UpdatedAtCleared() {
		_spec.ClearField(tablerow.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := truo.mutation.Nanoid(); ok {
		_spec.SetField(tablerow.FieldNanoid, field.TypeString, value)
	}
	if truo.mutation.NanoidCleared() {
		_spec.ClearField(tablerow.FieldNanoid, field.TypeString)
	}
	if value, ok := truo.mutation.Cells(); ok {
		_spec.SetField(tablerow.FieldCells, field.TypeJSON, value)
	}
	if value, ok := truo.mutation.AppendedCells(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tablerow.FieldCells, value)
		})
	}
	if truo.mutation.CellsCleared() {
		_spec.ClearField(tablerow.FieldCells, field.TypeJSON)
	}
	if truo.mutation.TablemetaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tablerow.TablemetaTable,
			Columns: []string{tablerow.TablemetaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablemeta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := truo.mutation.TablemetaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tablerow.TablemetaTable,
			Columns: []string{tablerow.TablemetaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablemeta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(truo.modifiers...)
	_node = &TableRow{config: truo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, truo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tablerow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	truo.mutation.done = true
	return _node, nil
}
