// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Yiling-J/tablepilot/ent/predicate"
	"github.com/Yiling-J/tablepilot/ent/tablecolumn"
	"github.com/Yiling-J/tablepilot/ent/tablemeta"
)

// TableColumnUpdate is the builder for updating TableColumn entities.
type TableColumnUpdate struct {
	config
	hooks     []Hook
	mutation  *TableColumnMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TableColumnUpdate builder.
func (tcu *TableColumnUpdate) Where(ps ...predicate.TableColumn) *TableColumnUpdate {
	tcu.mutation.Where(ps...)
	return tcu
}

// SetUpdatedAt sets the "updated_at" field.
func (tcu *TableColumnUpdate) SetUpdatedAt(t time.Time) *TableColumnUpdate {
	tcu.mutation.SetUpdatedAt(t)
	return tcu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (tcu *TableColumnUpdate) ClearUpdatedAt() *TableColumnUpdate {
	tcu.mutation.ClearUpdatedAt()
	return tcu
}

// SetNanoid sets the "nanoid" field.
func (tcu *TableColumnUpdate) SetNanoid(s string) *TableColumnUpdate {
	tcu.mutation.SetNanoid(s)
	return tcu
}

// SetNillableNanoid sets the "nanoid" field if the given value is not nil.
func (tcu *TableColumnUpdate) SetNillableNanoid(s *string) *TableColumnUpdate {
	if s != nil {
		tcu.SetNanoid(*s)
	}
	return tcu
}

// ClearNanoid clears the value of the "nanoid" field.
func (tcu *TableColumnUpdate) ClearNanoid() *TableColumnUpdate {
	tcu.mutation.ClearNanoid()
	return tcu
}

// SetName sets the "name" field.
func (tcu *TableColumnUpdate) SetName(s string) *TableColumnUpdate {
	tcu.mutation.SetName(s)
	return tcu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tcu *TableColumnUpdate) SetNillableName(s *string) *TableColumnUpdate {
	if s != nil {
		tcu.SetName(*s)
	}
	return tcu
}

// SetDescription sets the "description" field.
func (tcu *TableColumnUpdate) SetDescription(s string) *TableColumnUpdate {
	tcu.mutation.SetDescription(s)
	return tcu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tcu *TableColumnUpdate) SetNillableDescription(s *string) *TableColumnUpdate {
	if s != nil {
		tcu.SetDescription(*s)
	}
	return tcu
}

// ClearDescription clears the value of the "description" field.
func (tcu *TableColumnUpdate) ClearDescription() *TableColumnUpdate {
	tcu.mutation.ClearDescription()
	return tcu
}

// SetType sets the "type" field.
func (tcu *TableColumnUpdate) SetType(t tablecolumn.Type) *TableColumnUpdate {
	tcu.mutation.SetType(t)
	return tcu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tcu *TableColumnUpdate) SetNillableType(t *tablecolumn.Type) *TableColumnUpdate {
	if t != nil {
		tcu.SetType(*t)
	}
	return tcu
}

// SetFillMode sets the "fill_mode" field.
func (tcu *TableColumnUpdate) SetFillMode(tm tablecolumn.FillMode) *TableColumnUpdate {
	tcu.mutation.SetFillMode(tm)
	return tcu
}

// SetNillableFillMode sets the "fill_mode" field if the given value is not nil.
func (tcu *TableColumnUpdate) SetNillableFillMode(tm *tablecolumn.FillMode) *TableColumnUpdate {
	if tm != nil {
		tcu.SetFillMode(*tm)
	}
	return tcu
}

// SetSource sets the "source" field.
func (tcu *TableColumnUpdate) SetSource(jm json.RawMessage) *TableColumnUpdate {
	tcu.mutation.SetSource(jm)
	return tcu
}

// AppendSource appends jm to the "source" field.
func (tcu *TableColumnUpdate) AppendSource(jm json.RawMessage) *TableColumnUpdate {
	tcu.mutation.AppendSource(jm)
	return tcu
}

// ClearSource clears the value of the "source" field.
func (tcu *TableColumnUpdate) ClearSource() *TableColumnUpdate {
	tcu.mutation.ClearSource()
	return tcu
}

// SetContextLength sets the "context_length" field.
func (tcu *TableColumnUpdate) SetContextLength(i int) *TableColumnUpdate {
	tcu.mutation.ResetContextLength()
	tcu.mutation.SetContextLength(i)
	return tcu
}

// SetNillableContextLength sets the "context_length" field if the given value is not nil.
func (tcu *TableColumnUpdate) SetNillableContextLength(i *int) *TableColumnUpdate {
	if i != nil {
		tcu.SetContextLength(*i)
	}
	return tcu
}

// AddContextLength adds i to the "context_length" field.
func (tcu *TableColumnUpdate) AddContextLength(i int) *TableColumnUpdate {
	tcu.mutation.AddContextLength(i)
	return tcu
}

// SetTableID sets the "table_id" field.
func (tcu *TableColumnUpdate) SetTableID(i int) *TableColumnUpdate {
	tcu.mutation.SetTableID(i)
	return tcu
}

// SetNillableTableID sets the "table_id" field if the given value is not nil.
func (tcu *TableColumnUpdate) SetNillableTableID(i *int) *TableColumnUpdate {
	if i != nil {
		tcu.SetTableID(*i)
	}
	return tcu
}

// SetTablemetaID sets the "tablemeta" edge to the TableMeta entity by ID.
func (tcu *TableColumnUpdate) SetTablemetaID(id int) *TableColumnUpdate {
	tcu.mutation.SetTablemetaID(id)
	return tcu
}

// SetTablemeta sets the "tablemeta" edge to the TableMeta entity.
func (tcu *TableColumnUpdate) SetTablemeta(t *TableMeta) *TableColumnUpdate {
	return tcu.SetTablemetaID(t.ID)
}

// Mutation returns the TableColumnMutation object of the builder.
func (tcu *TableColumnUpdate) Mutation() *TableColumnMutation {
	return tcu.mutation
}

// ClearTablemeta clears the "tablemeta" edge to the TableMeta entity.
func (tcu *TableColumnUpdate) ClearTablemeta() *TableColumnUpdate {
	tcu.mutation.ClearTablemeta()
	return tcu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tcu *TableColumnUpdate) Save(ctx context.Context) (int, error) {
	tcu.defaults()
	return withHooks(ctx, tcu.sqlSave, tcu.mutation, tcu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tcu *TableColumnUpdate) SaveX(ctx context.Context) int {
	affected, err := tcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tcu *TableColumnUpdate) Exec(ctx context.Context) error {
	_, err := tcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcu *TableColumnUpdate) ExecX(ctx context.Context) {
	if err := tcu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tcu *TableColumnUpdate) defaults() {
	if _, ok := tcu.mutation.UpdatedAt(); !ok && !tcu.mutation.UpdatedAtCleared() {
		v := tablecolumn.UpdateDefaultUpdatedAt()
		tcu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tcu *TableColumnUpdate) check() error {
	if v, ok := tcu.mutation.Name(); ok {
		if err := tablecolumn.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TableColumn.name": %w`, err)}
		}
	}
	if v, ok := tcu.mutation.GetType(); ok {
		if err := tablecolumn.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TableColumn.type": %w`, err)}
		}
	}
	if v, ok := tcu.mutation.FillMode(); ok {
		if err := tablecolumn.FillModeValidator(v); err != nil {
			return &ValidationError{Name: "fill_mode", err: fmt.Errorf(`ent: validator failed for field "TableColumn.fill_mode": %w`, err)}
		}
	}
	if tcu.mutation.TablemetaCleared() && len(tcu.mutation.TablemetaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TableColumn.tablemeta"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tcu *TableColumnUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TableColumnUpdate {
	tcu.modifiers = append(tcu.modifiers, modifiers...)
	return tcu
}

func (tcu *TableColumnUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tcu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tablecolumn.Table, tablecolumn.Columns, sqlgraph.NewFieldSpec(tablecolumn.FieldID, field.TypeInt))
	if ps := tcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if tcu.mutation.CreatedAtCleared() {
		_spec.ClearField(tablecolumn.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := tcu.mutation.UpdatedAt(); ok {
		_spec.SetField(tablecolumn.FieldUpdatedAt, field.TypeTime, value)
	}
	if tcu.mutation.UpdatedAtCleared() {
		_spec.ClearField(tablecolumn.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := tcu.mutation.Nanoid(); ok {
		_spec.SetField(tablecolumn.FieldNanoid, field.TypeString, value)
	}
	if tcu.mutation.NanoidCleared() {
		_spec.ClearField(tablecolumn.FieldNanoid, field.TypeString)
	}
	if value, ok := tcu.mutation.Name(); ok {
		_spec.SetField(tablecolumn.FieldName, field.TypeString, value)
	}
	if value, ok := tcu.mutation.Description(); ok {
		_spec.SetField(tablecolumn.FieldDescription, field.TypeString, value)
	}
	if tcu.mutation.DescriptionCleared() {
		_spec.ClearField(tablecolumn.FieldDescription, field.TypeString)
	}
	if value, ok := tcu.mutation.GetType(); ok {
		_spec.SetField(tablecolumn.FieldType, field.TypeEnum, value)
	}
	if value, ok := tcu.mutation.FillMode(); ok {
		_spec.SetField(tablecolumn.FieldFillMode, field.TypeEnum, value)
	}
	if value, ok := tcu.mutation.Source(); ok {
		_spec.SetField(tablecolumn.FieldSource, field.TypeJSON, value)
	}
	if value, ok := tcu.mutation.AppendedSource(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tablecolumn.FieldSource, value)
		})
	}
	if tcu.mutation.SourceCleared() {
		_spec.ClearField(tablecolumn.FieldSource, field.TypeJSON)
	}
	if value, ok := tcu.mutation.ContextLength(); ok {
		_spec.SetField(tablecolumn.FieldContextLength, field.TypeInt, value)
	}
	if value, ok := tcu.mutation.AddedContextLength(); ok {
		_spec.AddField(tablecolumn.FieldContextLength, field.TypeInt, value)
	}
	if tcu.mutation.TablemetaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tablecolumn.TablemetaTable,
			Columns: []string{tablecolumn.TablemetaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablemeta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tcu.mutation.TablemetaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tablecolumn.TablemetaTable,
			Columns: []string{tablecolumn.TablemetaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablemeta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tcu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, tcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tablecolumn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tcu.mutation.done = true
	return n, nil
}

// TableColumnUpdateOne is the builder for updating a single TableColumn entity.
type TableColumnUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TableColumnMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (tcuo *TableColumnUpdateOne) SetUpdatedAt(t time.Time) *TableColumnUpdateOne {
	tcuo.mutation.SetUpdatedAt(t)
	return tcuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (tcuo *TableColumnUpdateOne) ClearUpdatedAt() *TableColumnUpdateOne {
	tcuo.mutation.ClearUpdatedAt()
	return tcuo
}

// SetNanoid sets the "nanoid" field.
func (tcuo *TableColumnUpdateOne) SetNanoid(s string) *TableColumnUpdateOne {
	tcuo.mutation.SetNanoid(s)
	return tcuo
}

// SetNillableNanoid sets the "nanoid" field if the given value is not nil.
func (tcuo *TableColumnUpdateOne) SetNillableNanoid(s *string) *TableColumnUpdateOne {
	if s != nil {
		tcuo.SetNanoid(*s)
	}
	return tcuo
}

// ClearNanoid clears the value of the "nanoid" field.
func (tcuo *TableColumnUpdateOne) ClearNanoid() *TableColumnUpdateOne {
	tcuo.mutation.ClearNanoid()
	return tcuo
}

// SetName sets the "name" field.
func (tcuo *TableColumnUpdateOne) SetName(s string) *TableColumnUpdateOne {
	tcuo.mutation.SetName(s)
	return tcuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tcuo *TableColumnUpdateOne) SetNillableName(s *string) *TableColumnUpdateOne {
	if s != nil {
		tcuo.SetName(*s)
	}
	return tcuo
}

// SetDescription sets the "description" field.
func (tcuo *TableColumnUpdateOne) SetDescription(s string) *TableColumnUpdateOne {
	tcuo.mutation.SetDescription(s)
	return tcuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tcuo *TableColumnUpdateOne) SetNillableDescription(s *string) *TableColumnUpdateOne {
	if s != nil {
		tcuo.SetDescription(*s)
	}
	return tcuo
}

// ClearDescription clears the value of the "description" field.
func (tcuo *TableColumnUpdateOne) ClearDescription() *TableColumnUpdateOne {
	tcuo.mutation.ClearDescription()
	return tcuo
}

// SetType sets the "type" field.
func (tcuo *TableColumnUpdateOne) SetType(t tablecolumn.Type) *TableColumnUpdateOne {
	tcuo.mutation.SetType(t)
	return tcuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tcuo *TableColumnUpdateOne) SetNillableType(t *tablecolumn.Type) *TableColumnUpdateOne {
	if t != nil {
		tcuo.SetType(*t)
	}
	return tcuo
}

// SetFillMode sets the "fill_mode" field.
func (tcuo *TableColumnUpdateOne) SetFillMode(tm tablecolumn.FillMode) *TableColumnUpdateOne {
	tcuo.mutation.SetFillMode(tm)
	return tcuo
}

// SetNillableFillMode sets the "fill_mode" field if the given value is not nil.
func (tcuo *TableColumnUpdateOne) SetNillableFillMode(tm *tablecolumn.FillMode) *TableColumnUpdateOne {
	if tm != nil {
		tcuo.SetFillMode(*tm)
	}
	return tcuo
}

// SetSource sets the "source" field.
func (tcuo *TableColumnUpdateOne) SetSource(jm json.RawMessage) *TableColumnUpdateOne {
	tcuo.mutation.SetSource(jm)
	return tcuo
}

// AppendSource appends jm to the "source" field.
func (tcuo *TableColumnUpdateOne) AppendSource(jm json.RawMessage) *TableColumnUpdateOne {
	tcuo.mutation.AppendSource(jm)
	return tcuo
}

// ClearSource clears the value of the "source" field.
func (tcuo *TableColumnUpdateOne) ClearSource() *TableColumnUpdateOne {
	tcuo.mutation.ClearSource()
	return tcuo
}

// SetContextLength sets the "context_length" field.
func (tcuo *TableColumnUpdateOne) SetContextLength(i int) *TableColumnUpdateOne {
	tcuo.mutation.ResetContextLength()
	tcuo.mutation.SetContextLength(i)
	return tcuo
}

// SetNillableContextLength sets the "context_length" field if the given value is not nil.
func (tcuo *TableColumnUpdateOne) SetNillableContextLength(i *int) *TableColumnUpdateOne {
	if i != nil {
		tcuo.SetContextLength(*i)
	}
	return tcuo
}

// AddContextLength adds i to the "context_length" field.
func (tcuo *TableColumnUpdateOne) AddContextLength(i int) *TableColumnUpdateOne {
	tcuo.mutation.AddContextLength(i)
	return tcuo
}

// SetTableID sets the "table_id" field.
func (tcuo *TableColumnUpdateOne) SetTableID(i int) *TableColumnUpdateOne {
	tcuo.mutation.SetTableID(i)
	return tcuo
}

// SetNillableTableID sets the "table_id" field if the given value is not nil.
func (tcuo *TableColumnUpdateOne) SetNillableTableID(i *int) *TableColumnUpdateOne {
	if i != nil {
		tcuo.SetTableID(*i)
	}
	return tcuo
}

// SetTablemetaID sets the "tablemeta" edge to the TableMeta entity by ID.
func (tcuo *TableColumnUpdateOne) SetTablemetaID(id int) *TableColumnUpdateOne {
	tcuo.mutation.SetTablemetaID(id)
	return tcuo
}

// SetTablemeta sets the "tablemeta" edge to the TableMeta entity.
func (tcuo *TableColumnUpdateOne) SetTablemeta(t *TableMeta) *TableColumnUpdateOne {
	return tcuo.SetTablemetaID(t.ID)
}

// Mutation returns the TableColumnMutation object of the builder.
func (tcuo *TableColumnUpdateOne) Mutation() *TableColumnMutation {
	return tcuo.mutation
}

// ClearTablemeta clears the "tablemeta" edge to the TableMeta entity.
func (tcuo *TableColumnUpdateOne) ClearTablemeta() *TableColumnUpdateOne {
	tcuo.mutation.ClearTablemeta()
	return tcuo
}

// Where appends a list predicates to the TableColumnUpdate builder.
func (tcuo *TableColumnUpdateOne) Where(ps ...predicate.TableColumn) *TableColumnUpdateOne {
	tcuo.mutation.Where(ps...)
	return tcuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tcuo *TableColumnUpdateOne) Select(field string, fields ...string) *TableColumnUpdateOne {
	tcuo.fields = append([]string{field}, fields...)
	return tcuo
}

// Save executes the query and returns the updated TableColumn entity.
func (tcuo *TableColumnUpdateOne) Save(ctx context.Context) (*TableColumn, error) {
	tcuo.defaults()
	return withHooks(ctx, tcuo.sqlSave, tcuo.mutation, tcuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tcuo *TableColumnUpdateOne) SaveX(ctx context.Context) *TableColumn {
	node, err := tcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tcuo *TableColumnUpdateOne) Exec(ctx context.Context) error {
	_, err := tcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcuo *TableColumnUpdateOne) ExecX(ctx context.Context) {
	if err := tcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tcuo *TableColumnUpdateOne) defaults() {
	if _, ok := tcuo.mutation.UpdatedAt(); !ok && !tcuo.mutation.UpdatedAtCleared() {
		v := tablecolumn.UpdateDefaultUpdatedAt()
		tcuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tcuo *TableColumnUpdateOne) check() error {
	if v, ok := tcuo.mutation.Name(); ok {
		if err := tablecolumn.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TableColumn.name": %w`, err)}
		}
	}
	if v, ok := tcuo.mutation.GetType(); ok {
		if err := tablecolumn.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TableColumn.type": %w`, err)}
		}
	}
	if v, ok := tcuo.mutation.FillMode(); ok {
		if err := tablecolumn.FillModeValidator(v); err != nil {
			return &ValidationError{Name: "fill_mode", err: fmt.Errorf(`ent: validator failed for field "TableColumn.fill_mode": %w`, err)}
		}
	}
	if tcuo.mutation.TablemetaCleared() && len(tcuo.mutation.TablemetaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TableColumn.tablemeta"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tcuo *TableColumnUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TableColumnUpdateOne {
	tcuo.modifiers = append(tcuo.modifiers, modifiers...)
	return tcuo
}

func (tcuo *TableColumnUpdateOne) sqlSave(ctx context.Context) (_node *TableColumn, err error) {
	if err := tcuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tablecolumn.Table, tablecolumn.Columns, sqlgraph.NewFieldSpec(tablecolumn.FieldID, field.TypeInt))
	id, ok := tcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TableColumn.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tablecolumn.FieldID)
		for _, f := range fields {
			if !tablecolumn.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tablecolumn.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if tcuo.mutation.CreatedAtCleared() {
		_spec.ClearField(tablecolumn.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := tcuo.mutation.UpdatedAt(); ok {
		_spec.SetField(tablecolumn.FieldUpdatedAt, field.TypeTime, value)
	}
	if tcuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(tablecolumn.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := tcuo.mutation.Nanoid(); ok {
		_spec.SetField(tablecolumn.FieldNanoid, field.TypeString, value)
	}
	if tcuo.mutation.NanoidCleared() {
		_spec.ClearField(tablecolumn.FieldNanoid, field.TypeString)
	}
	if value, ok := tcuo.mutation.Name(); ok {
		_spec.SetField(tablecolumn.FieldName, field.TypeString, value)
	}
	if value, ok := tcuo.mutation.Description(); ok {
		_spec.SetField(tablecolumn.FieldDescription, field.TypeString, value)
	}
	if tcuo.mutation.DescriptionCleared() {
		_spec.ClearField(tablecolumn.FieldDescription, field.TypeString)
	}
	if value, ok := tcuo.mutation.GetType(); ok {
		_spec.SetField(tablecolumn.FieldType, field.TypeEnum, value)
	}
	if value, ok := tcuo.mutation.FillMode(); ok {
		_spec.SetField(tablecolumn.FieldFillMode, field.TypeEnum, value)
	}
	if value, ok := tcuo.mutation.Source(); ok {
		_spec.SetField(tablecolumn.FieldSource, field.TypeJSON, value)
	}
	if value, ok := tcuo.mutation.AppendedSource(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tablecolumn.FieldSource, value)
		})
	}
	if tcuo.mutation.SourceCleared() {
		_spec.ClearField(tablecolumn.FieldSource, field.TypeJSON)
	}
	if value, ok := tcuo.mutation.ContextLength(); ok {
		_spec.SetField(tablecolumn.FieldContextLength, field.TypeInt, value)
	}
	if value, ok := tcuo.mutation.AddedContextLength(); ok {
		_spec.AddField(tablecolumn.FieldContextLength, field.TypeInt, value)
	}
	if tcuo.mutation.TablemetaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tablecolumn.TablemetaTable,
			Columns: []string{tablecolumn.TablemetaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablemeta.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tcuo.mutation.TablemetaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tablecolumn.TablemetaTable,
			Columns: []string{tablecolumn.TablemetaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablemeta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tcuo.modifiers...)
	_node = &TableColumn{config: tcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tablecolumn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tcuo.mutation.done = true
	return _node, nil
}
