// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Yiling-J/tablepilot/ent/tablecolumn"
	"github.com/Yiling-J/tablepilot/ent/tablemeta"
	"github.com/Yiling-J/tablepilot/ent/tablerow"
)

// TableMetaCreate is the builder for creating a TableMeta entity.
type TableMetaCreate struct {
	config
	mutation *TableMetaMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (tmc *TableMetaCreate) SetCreatedAt(t time.Time) *TableMetaCreate {
	tmc.mutation.SetCreatedAt(t)
	return tmc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tmc *TableMetaCreate) SetNillableCreatedAt(t *time.Time) *TableMetaCreate {
	if t != nil {
		tmc.SetCreatedAt(*t)
	}
	return tmc
}

// SetUpdatedAt sets the "updated_at" field.
func (tmc *TableMetaCreate) SetUpdatedAt(t time.Time) *TableMetaCreate {
	tmc.mutation.SetUpdatedAt(t)
	return tmc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tmc *TableMetaCreate) SetNillableUpdatedAt(t *time.Time) *TableMetaCreate {
	if t != nil {
		tmc.SetUpdatedAt(*t)
	}
	return tmc
}

// SetNanoid sets the "nanoid" field.
func (tmc *TableMetaCreate) SetNanoid(s string) *TableMetaCreate {
	tmc.mutation.SetNanoid(s)
	return tmc
}

// SetNillableNanoid sets the "nanoid" field if the given value is not nil.
func (tmc *TableMetaCreate) SetNillableNanoid(s *string) *TableMetaCreate {
	if s != nil {
		tmc.SetNanoid(*s)
	}
	return tmc
}

// SetMaxRows sets the "max_rows" field.
func (tmc *TableMetaCreate) SetMaxRows(i int) *TableMetaCreate {
	tmc.mutation.SetMaxRows(i)
	return tmc
}

// SetNillableMaxRows sets the "max_rows" field if the given value is not nil.
func (tmc *TableMetaCreate) SetNillableMaxRows(i *int) *TableMetaCreate {
	if i != nil {
		tmc.SetMaxRows(*i)
	}
	return tmc
}

// SetPromptRaw sets the "prompt_raw" field.
func (tmc *TableMetaCreate) SetPromptRaw(s string) *TableMetaCreate {
	tmc.mutation.SetPromptRaw(s)
	return tmc
}

// SetNillablePromptRaw sets the "prompt_raw" field if the given value is not nil.
func (tmc *TableMetaCreate) SetNillablePromptRaw(s *string) *TableMetaCreate {
	if s != nil {
		tmc.SetPromptRaw(*s)
	}
	return tmc
}

// SetPromptGen sets the "prompt_gen" field.
func (tmc *TableMetaCreate) SetPromptGen(s string) *TableMetaCreate {
	tmc.mutation.SetPromptGen(s)
	return tmc
}

// SetNillablePromptGen sets the "prompt_gen" field if the given value is not nil.
func (tmc *TableMetaCreate) SetNillablePromptGen(s *string) *TableMetaCreate {
	if s != nil {
		tmc.SetPromptGen(*s)
	}
	return tmc
}

// SetName sets the "name" field.
func (tmc *TableMetaCreate) SetName(s string) *TableMetaCreate {
	tmc.mutation.SetName(s)
	return tmc
}

// SetDescription sets the "description" field.
func (tmc *TableMetaCreate) SetDescription(s string) *TableMetaCreate {
	tmc.mutation.SetDescription(s)
	return tmc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tmc *TableMetaCreate) SetNillableDescription(s *string) *TableMetaCreate {
	if s != nil {
		tmc.SetDescription(*s)
	}
	return tmc
}

// SetBuildStatus sets the "build_status" field.
func (tmc *TableMetaCreate) SetBuildStatus(ts tablemeta.BuildStatus) *TableMetaCreate {
	tmc.mutation.SetBuildStatus(ts)
	return tmc
}

// SetNillableBuildStatus sets the "build_status" field if the given value is not nil.
func (tmc *TableMetaCreate) SetNillableBuildStatus(ts *tablemeta.BuildStatus) *TableMetaCreate {
	if ts != nil {
		tmc.SetBuildStatus(*ts)
	}
	return tmc
}

// SetModel sets the "model" field.
func (tmc *TableMetaCreate) SetModel(s string) *TableMetaCreate {
	tmc.mutation.SetModel(s)
	return tmc
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (tmc *TableMetaCreate) SetNillableModel(s *string) *TableMetaCreate {
	if s != nil {
		tmc.SetModel(*s)
	}
	return tmc
}

// AddColumnIDs adds the "columns" edge to the TableColumn entity by IDs.
func (tmc *TableMetaCreate) AddColumnIDs(ids ...int) *TableMetaCreate {
	tmc.mutation.AddColumnIDs(ids...)
	return tmc
}

// AddColumns adds the "columns" edges to the TableColumn entity.
func (tmc *TableMetaCreate) AddColumns(t ...*TableColumn) *TableMetaCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tmc.AddColumnIDs(ids...)
}

// AddRowIDs adds the "rows" edge to the TableRow entity by IDs.
func (tmc *TableMetaCreate) AddRowIDs(ids ...int) *TableMetaCreate {
	tmc.mutation.AddRowIDs(ids...)
	return tmc
}

// AddRows adds the "rows" edges to the TableRow entity.
func (tmc *TableMetaCreate) AddRows(t ...*TableRow) *TableMetaCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tmc.AddRowIDs(ids...)
}

// Mutation returns the TableMetaMutation object of the builder.
func (tmc *TableMetaCreate) Mutation() *TableMetaMutation {
	return tmc.mutation
}

// Save creates the TableMeta in the database.
func (tmc *TableMetaCreate) Save(ctx context.Context) (*TableMeta, error) {
	tmc.defaults()
	return withHooks(ctx, tmc.sqlSave, tmc.mutation, tmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tmc *TableMetaCreate) SaveX(ctx context.Context) *TableMeta {
	v, err := tmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tmc *TableMetaCreate) Exec(ctx context.Context) error {
	_, err := tmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tmc *TableMetaCreate) ExecX(ctx context.Context) {
	if err := tmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tmc *TableMetaCreate) defaults() {
	if _, ok := tmc.mutation.CreatedAt(); !ok {
		v := tablemeta.DefaultCreatedAt()
		tmc.mutation.SetCreatedAt(v)
	}
	if _, ok := tmc.mutation.UpdatedAt(); !ok {
		v := tablemeta.DefaultUpdatedAt()
		tmc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tmc.mutation.MaxRows(); !ok {
		v := tablemeta.DefaultMaxRows
		tmc.mutation.SetMaxRows(v)
	}
	if _, ok := tmc.mutation.PromptRaw(); !ok {
		v := tablemeta.DefaultPromptRaw
		tmc.mutation.SetPromptRaw(v)
	}
	if _, ok := tmc.mutation.PromptGen(); !ok {
		v := tablemeta.DefaultPromptGen
		tmc.mutation.SetPromptGen(v)
	}
	if _, ok := tmc.mutation.Description(); !ok {
		v := tablemeta.DefaultDescription
		tmc.mutation.SetDescription(v)
	}
	if _, ok := tmc.mutation.BuildStatus(); !ok {
		v := tablemeta.DefaultBuildStatus
		tmc.mutation.SetBuildStatus(v)
	}
	if _, ok := tmc.mutation.Model(); !ok {
		v := tablemeta.DefaultModel
		tmc.mutation.SetModel(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tmc *TableMetaCreate) check() error {
	if _, ok := tmc.mutation.MaxRows(); !ok {
		return &ValidationError{Name: "max_rows", err: errors.New(`ent: missing required field "TableMeta.max_rows"`)}
	}
	if _, ok := tmc.mutation.PromptRaw(); !ok {
		return &ValidationError{Name: "prompt_raw", err: errors.New(`ent: missing required field "TableMeta.prompt_raw"`)}
	}
	if _, ok := tmc.mutation.PromptGen(); !ok {
		return &ValidationError{Name: "prompt_gen", err: errors.New(`ent: missing required field "TableMeta.prompt_gen"`)}
	}
	if _, ok := tmc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TableMeta.name"`)}
	}
	if v, ok := tmc.mutation.Name(); ok {
		if err := tablemeta.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TableMeta.name": %w`, err)}
		}
	}
	if _, ok := tmc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "TableMeta.description"`)}
	}
	if _, ok := tmc.mutation.BuildStatus(); !ok {
		return &ValidationError{Name: "build_status", err: errors.New(`ent: missing required field "TableMeta.build_status"`)}
	}
	if v, ok := tmc.mutation.BuildStatus(); ok {
		if err := tablemeta.BuildStatusValidator(v); err != nil {
			return &ValidationError{Name: "build_status", err: fmt.Errorf(`ent: validator failed for field "TableMeta.build_status": %w`, err)}
		}
	}
	if _, ok := tmc.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "TableMeta.model"`)}
	}
	return nil
}

func (tmc *TableMetaCreate) sqlSave(ctx context.Context) (*TableMeta, error) {
	if err := tmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tmc.mutation.id = &_node.ID
	tmc.mutation.done = true
	return _node, nil
}

func (tmc *TableMetaCreate) createSpec() (*TableMeta, *sqlgraph.CreateSpec) {
	var (
		_node = &TableMeta{config: tmc.config}
		_spec = sqlgraph.NewCreateSpec(tablemeta.Table, sqlgraph.NewFieldSpec(tablemeta.FieldID, field.TypeInt))
	)
	_spec.OnConflict = tmc.conflict
	if value, ok := tmc.mutation.CreatedAt(); ok {
		_spec.SetField(tablemeta.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tmc.mutation.UpdatedAt(); ok {
		_spec.SetField(tablemeta.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := tmc.mutation.Nanoid(); ok {
		_spec.SetField(tablemeta.FieldNanoid, field.TypeString, value)
		_node.Nanoid = value
	}
	if value, ok := tmc.mutation.MaxRows(); ok {
		_spec.SetField(tablemeta.FieldMaxRows, field.TypeInt, value)
		_node.MaxRows = value
	}
	if value, ok := tmc.mutation.PromptRaw(); ok {
		_spec.SetField(tablemeta.FieldPromptRaw, field.TypeString, value)
		_node.PromptRaw = value
	}
	if value, ok := tmc.mutation.PromptGen(); ok {
		_spec.SetField(tablemeta.FieldPromptGen, field.TypeString, value)
		_node.PromptGen = value
	}
	if value, ok := tmc.mutation.Name(); ok {
		_spec.SetField(tablemeta.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tmc.mutation.Description(); ok {
		_spec.SetField(tablemeta.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := tmc.mutation.BuildStatus(); ok {
		_spec.SetField(tablemeta.FieldBuildStatus, field.TypeEnum, value)
		_node.BuildStatus = value
	}
	if value, ok := tmc.mutation.Model(); ok {
		_spec.SetField(tablemeta.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if nodes := tmc.mutation.ColumnsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tablemeta.ColumnsTable,
			Columns: []string{tablemeta.ColumnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablecolumn.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tmc.mutation.RowsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tablemeta.RowsTable,
			Columns: []string{tablemeta.RowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablerow.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TableMeta.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TableMetaUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (tmc *TableMetaCreate) OnConflict(opts ...sql.ConflictOption) *TableMetaUpsertOne {
	tmc.conflict = opts
	return &TableMetaUpsertOne{
		create: tmc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TableMeta.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tmc *TableMetaCreate) OnConflictColumns(columns ...string) *TableMetaUpsertOne {
	tmc.conflict = append(tmc.conflict, sql.ConflictColumns(columns...))
	return &TableMetaUpsertOne{
		create: tmc,
	}
}

type (
	// TableMetaUpsertOne is the builder for "upsert"-ing
	//  one TableMeta node.
	TableMetaUpsertOne struct {
		create *TableMetaCreate
	}

	// TableMetaUpsert is the "OnConflict" setter.
	TableMetaUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TableMetaUpsert) SetUpdatedAt(v time.Time) *TableMetaUpsert {
	u.Set(tablemeta.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TableMetaUpsert) UpdateUpdatedAt() *TableMetaUpsert {
	u.SetExcluded(tablemeta.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TableMetaUpsert) ClearUpdatedAt() *TableMetaUpsert {
	u.SetNull(tablemeta.FieldUpdatedAt)
	return u
}

// SetNanoid sets the "nanoid" field.
func (u *TableMetaUpsert) SetNanoid(v string) *TableMetaUpsert {
	u.Set(tablemeta.FieldNanoid, v)
	return u
}

// UpdateNanoid sets the "nanoid" field to the value that was provided on create.
func (u *TableMetaUpsert) UpdateNanoid() *TableMetaUpsert {
	u.SetExcluded(tablemeta.FieldNanoid)
	return u
}

// ClearNanoid clears the value of the "nanoid" field.
func (u *TableMetaUpsert) ClearNanoid() *TableMetaUpsert {
	u.SetNull(tablemeta.FieldNanoid)
	return u
}

// SetMaxRows sets the "max_rows" field.
func (u *TableMetaUpsert) SetMaxRows(v int) *TableMetaUpsert {
	u.Set(tablemeta.FieldMaxRows, v)
	return u
}

// UpdateMaxRows sets the "max_rows" field to the value that was provided on create.
func (u *TableMetaUpsert) UpdateMaxRows() *TableMetaUpsert {
	u.SetExcluded(tablemeta.FieldMaxRows)
	return u
}

// AddMaxRows adds v to the "max_rows" field.
func (u *TableMetaUpsert) AddMaxRows(v int) *TableMetaUpsert {
	u.Add(tablemeta.FieldMaxRows, v)
	return u
}

// SetPromptRaw sets the "prompt_raw" field.
func (u *TableMetaUpsert) SetPromptRaw(v string) *TableMetaUpsert {
	u.Set(tablemeta.FieldPromptRaw, v)
	return u
}

// UpdatePromptRaw sets the "prompt_raw" field to the value that was provided on create.
func (u *TableMetaUpsert) UpdatePromptRaw() *TableMetaUpsert {
	u.SetExcluded(tablemeta.FieldPromptRaw)
	return u
}

// SetPromptGen sets the "prompt_gen" field.
func (u *TableMetaUpsert) SetPromptGen(v string) *TableMetaUpsert {
	u.Set(tablemeta.FieldPromptGen, v)
	return u
}

// UpdatePromptGen sets the "prompt_gen" field to the value that was provided on create.
func (u *TableMetaUpsert) UpdatePromptGen() *TableMetaUpsert {
	u.SetExcluded(tablemeta.FieldPromptGen)
	return u
}

// SetName sets the "name" field.
func (u *TableMetaUpsert) SetName(v string) *TableMetaUpsert {
	u.Set(tablemeta.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TableMetaUpsert) UpdateName() *TableMetaUpsert {
	u.SetExcluded(tablemeta.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *TableMetaUpsert) SetDescription(v string) *TableMetaUpsert {
	u.Set(tablemeta.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TableMetaUpsert) UpdateDescription() *TableMetaUpsert {
	u.SetExcluded(tablemeta.FieldDescription)
	return u
}

// SetBuildStatus sets the "build_status" field.
func (u *TableMetaUpsert) SetBuildStatus(v tablemeta.BuildStatus) *TableMetaUpsert {
	u.Set(tablemeta.FieldBuildStatus, v)
	return u
}

// UpdateBuildStatus sets the "build_status" field to the value that was provided on create.
func (u *TableMetaUpsert) UpdateBuildStatus() *TableMetaUpsert {
	u.SetExcluded(tablemeta.FieldBuildStatus)
	return u
}

// SetModel sets the "model" field.
func (u *TableMetaUpsert) SetModel(v string) *TableMetaUpsert {
	u.Set(tablemeta.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *TableMetaUpsert) UpdateModel() *TableMetaUpsert {
	u.SetExcluded(tablemeta.FieldModel)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TableMeta.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TableMetaUpsertOne) UpdateNewValues() *TableMetaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(tablemeta.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TableMeta.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TableMetaUpsertOne) Ignore() *TableMetaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TableMetaUpsertOne) DoNothing() *TableMetaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TableMetaCreate.OnConflict
// documentation for more info.
func (u *TableMetaUpsertOne) Update(set func(*TableMetaUpsert)) *TableMetaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TableMetaUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TableMetaUpsertOne) SetUpdatedAt(v time.Time) *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TableMetaUpsertOne) UpdateUpdatedAt() *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TableMetaUpsertOne) ClearUpdatedAt() *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetNanoid sets the "nanoid" field.
func (u *TableMetaUpsertOne) SetNanoid(v string) *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetNanoid(v)
	})
}

// UpdateNanoid sets the "nanoid" field to the value that was provided on create.
func (u *TableMetaUpsertOne) UpdateNanoid() *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateNanoid()
	})
}

// ClearNanoid clears the value of the "nanoid" field.
func (u *TableMetaUpsertOne) ClearNanoid() *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.ClearNanoid()
	})
}

// SetMaxRows sets the "max_rows" field.
func (u *TableMetaUpsertOne) SetMaxRows(v int) *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetMaxRows(v)
	})
}

// AddMaxRows adds v to the "max_rows" field.
func (u *TableMetaUpsertOne) AddMaxRows(v int) *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.AddMaxRows(v)
	})
}

// UpdateMaxRows sets the "max_rows" field to the value that was provided on create.
func (u *TableMetaUpsertOne) UpdateMaxRows() *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateMaxRows()
	})
}

// SetPromptRaw sets the "prompt_raw" field.
func (u *TableMetaUpsertOne) SetPromptRaw(v string) *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetPromptRaw(v)
	})
}

// UpdatePromptRaw sets the "prompt_raw" field to the value that was provided on create.
func (u *TableMetaUpsertOne) UpdatePromptRaw() *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdatePromptRaw()
	})
}

// SetPromptGen sets the "prompt_gen" field.
func (u *TableMetaUpsertOne) SetPromptGen(v string) *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetPromptGen(v)
	})
}

// UpdatePromptGen sets the "prompt_gen" field to the value that was provided on create.
func (u *TableMetaUpsertOne) UpdatePromptGen() *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdatePromptGen()
	})
}

// SetName sets the "name" field.
func (u *TableMetaUpsertOne) SetName(v string) *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TableMetaUpsertOne) UpdateName() *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *TableMetaUpsertOne) SetDescription(v string) *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TableMetaUpsertOne) UpdateDescription() *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateDescription()
	})
}

// SetBuildStatus sets the "build_status" field.
func (u *TableMetaUpsertOne) SetBuildStatus(v tablemeta.BuildStatus) *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetBuildStatus(v)
	})
}

// UpdateBuildStatus sets the "build_status" field to the value that was provided on create.
func (u *TableMetaUpsertOne) UpdateBuildStatus() *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateBuildStatus()
	})
}

// SetModel sets the "model" field.
func (u *TableMetaUpsertOne) SetModel(v string) *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *TableMetaUpsertOne) UpdateModel() *TableMetaUpsertOne {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateModel()
	})
}

// Exec executes the query.
func (u *TableMetaUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TableMetaCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TableMetaUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TableMetaUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TableMetaUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TableMetaCreateBulk is the builder for creating many TableMeta entities in bulk.
type TableMetaCreateBulk struct {
	config
	err      error
	builders []*TableMetaCreate
	conflict []sql.ConflictOption
}

// Save creates the TableMeta entities in the database.
func (tmcb *TableMetaCreateBulk) Save(ctx context.Context) ([]*TableMeta, error) {
	if tmcb.err != nil {
		return nil, tmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tmcb.builders))
	nodes := make([]*TableMeta, len(tmcb.builders))
	mutators := make([]Mutator, len(tmcb.builders))
	for i := range tmcb.builders {
		func(i int, root context.Context) {
			builder := tmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TableMetaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tmcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tmcb *TableMetaCreateBulk) SaveX(ctx context.Context) []*TableMeta {
	v, err := tmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tmcb *TableMetaCreateBulk) Exec(ctx context.Context) error {
	_, err := tmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tmcb *TableMetaCreateBulk) ExecX(ctx context.Context) {
	if err := tmcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TableMeta.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TableMetaUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (tmcb *TableMetaCreateBulk) OnConflict(opts ...sql.ConflictOption) *TableMetaUpsertBulk {
	tmcb.conflict = opts
	return &TableMetaUpsertBulk{
		create: tmcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TableMeta.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tmcb *TableMetaCreateBulk) OnConflictColumns(columns ...string) *TableMetaUpsertBulk {
	tmcb.conflict = append(tmcb.conflict, sql.ConflictColumns(columns...))
	return &TableMetaUpsertBulk{
		create: tmcb,
	}
}

// TableMetaUpsertBulk is the builder for "upsert"-ing
// a bulk of TableMeta nodes.
type TableMetaUpsertBulk struct {
	create *TableMetaCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TableMeta.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TableMetaUpsertBulk) UpdateNewValues() *TableMetaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(tablemeta.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TableMeta.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TableMetaUpsertBulk) Ignore() *TableMetaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TableMetaUpsertBulk) DoNothing() *TableMetaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TableMetaCreateBulk.OnConflict
// documentation for more info.
func (u *TableMetaUpsertBulk) Update(set func(*TableMetaUpsert)) *TableMetaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TableMetaUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TableMetaUpsertBulk) SetUpdatedAt(v time.Time) *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TableMetaUpsertBulk) UpdateUpdatedAt() *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TableMetaUpsertBulk) ClearUpdatedAt() *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetNanoid sets the "nanoid" field.
func (u *TableMetaUpsertBulk) SetNanoid(v string) *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetNanoid(v)
	})
}

// UpdateNanoid sets the "nanoid" field to the value that was provided on create.
func (u *TableMetaUpsertBulk) UpdateNanoid() *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateNanoid()
	})
}

// ClearNanoid clears the value of the "nanoid" field.
func (u *TableMetaUpsertBulk) ClearNanoid() *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.ClearNanoid()
	})
}

// SetMaxRows sets the "max_rows" field.
func (u *TableMetaUpsertBulk) SetMaxRows(v int) *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetMaxRows(v)
	})
}

// AddMaxRows adds v to the "max_rows" field.
func (u *TableMetaUpsertBulk) AddMaxRows(v int) *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.AddMaxRows(v)
	})
}

// UpdateMaxRows sets the "max_rows" field to the value that was provided on create.
func (u *TableMetaUpsertBulk) UpdateMaxRows() *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateMaxRows()
	})
}

// SetPromptRaw sets the "prompt_raw" field.
func (u *TableMetaUpsertBulk) SetPromptRaw(v string) *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetPromptRaw(v)
	})
}

// UpdatePromptRaw sets the "prompt_raw" field to the value that was provided on create.
func (u *TableMetaUpsertBulk) UpdatePromptRaw() *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdatePromptRaw()
	})
}

// SetPromptGen sets the "prompt_gen" field.
func (u *TableMetaUpsertBulk) SetPromptGen(v string) *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetPromptGen(v)
	})
}

// UpdatePromptGen sets the "prompt_gen" field to the value that was provided on create.
func (u *TableMetaUpsertBulk) UpdatePromptGen() *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdatePromptGen()
	})
}

// SetName sets the "name" field.
func (u *TableMetaUpsertBulk) SetName(v string) *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TableMetaUpsertBulk) UpdateName() *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *TableMetaUpsertBulk) SetDescription(v string) *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TableMetaUpsertBulk) UpdateDescription() *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateDescription()
	})
}

// SetBuildStatus sets the "build_status" field.
func (u *TableMetaUpsertBulk) SetBuildStatus(v tablemeta.BuildStatus) *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetBuildStatus(v)
	})
}

// UpdateBuildStatus sets the "build_status" field to the value that was provided on create.
func (u *TableMetaUpsertBulk) UpdateBuildStatus() *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateBuildStatus()
	})
}

// SetModel sets the "model" field.
func (u *TableMetaUpsertBulk) SetModel(v string) *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *TableMetaUpsertBulk) UpdateModel() *TableMetaUpsertBulk {
	return u.Update(func(s *TableMetaUpsert) {
		s.UpdateModel()
	})
}

// Exec executes the query.
func (u *TableMetaUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TableMetaCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TableMetaCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TableMetaUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
