// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Yiling-J/tablepilot/ent/tablecolumn"
	"github.com/Yiling-J/tablepilot/ent/tablemeta"
)

// TableColumn is the model entity for the TableColumn schema.
type TableColumn struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Nanoid holds the value of the "nanoid" field.
	Nanoid string `json:"nanoid,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Type holds the value of the "type" field.
	Type tablecolumn.Type `json:"type,omitempty"`
	// FillMode holds the value of the "fill_mode" field.
	FillMode tablecolumn.FillMode `json:"fill_mode,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID string `json:"source_id,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType tablecolumn.SourceType `json:"source_type,omitempty"`
	// ContextLength holds the value of the "context_length" field.
	ContextLength int `json:"context_length,omitempty"`
	// TableID holds the value of the "table_id" field.
	TableID int `json:"table_id,omitempty"`
	// Random holds the value of the "random" field.
	Random bool `json:"random,omitempty"`
	// Replacement holds the value of the "replacement" field.
	Replacement bool `json:"replacement,omitempty"`
	// Repeat holds the value of the "repeat" field.
	Repeat int `json:"repeat,omitempty"`
	// LinkedColumn holds the value of the "linked_column" field.
	LinkedColumn string `json:"linked_column,omitempty"`
	// LinkedContextColumns holds the value of the "linked_context_columns" field.
	LinkedContextColumns []string `json:"linked_context_columns,omitempty"`
	// Options holds the value of the "options" field.
	Options []string `json:"options,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TableColumnQuery when eager-loading is set.
	Edges        TableColumnEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TableColumnEdges holds the relations/edges for other nodes in the graph.
type TableColumnEdges struct {
	// Tablemeta holds the value of the tablemeta edge.
	Tablemeta *TableMeta `json:"tablemeta,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TablemetaOrErr returns the Tablemeta value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TableColumnEdges) TablemetaOrErr() (*TableMeta, error) {
	if e.Tablemeta != nil {
		return e.Tablemeta, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tablemeta.Label}
	}
	return nil, &NotLoadedError{edge: "tablemeta"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TableColumn) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tablecolumn.FieldLinkedContextColumns, tablecolumn.FieldOptions:
			values[i] = new([]byte)
		case tablecolumn.FieldRandom, tablecolumn.FieldReplacement:
			values[i] = new(sql.NullBool)
		case tablecolumn.FieldID, tablecolumn.FieldContextLength, tablecolumn.FieldTableID, tablecolumn.FieldRepeat:
			values[i] = new(sql.NullInt64)
		case tablecolumn.FieldNanoid, tablecolumn.FieldName, tablecolumn.FieldDescription, tablecolumn.FieldType, tablecolumn.FieldFillMode, tablecolumn.FieldSource, tablecolumn.FieldSourceID, tablecolumn.FieldSourceType, tablecolumn.FieldLinkedColumn:
			values[i] = new(sql.NullString)
		case tablecolumn.FieldCreatedAt, tablecolumn.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TableColumn fields.
func (tc *TableColumn) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tablecolumn.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tc.ID = int(value.Int64)
		case tablecolumn.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tc.CreatedAt = value.Time
			}
		case tablecolumn.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				tc.UpdatedAt = value.Time
			}
		case tablecolumn.FieldNanoid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nanoid", values[i])
			} else if value.Valid {
				tc.Nanoid = value.String
			}
		case tablecolumn.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				tc.Name = value.String
			}
		case tablecolumn.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				tc.Description = value.String
			}
		case tablecolumn.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				tc.Type = tablecolumn.Type(value.String)
			}
		case tablecolumn.FieldFillMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fill_mode", values[i])
			} else if value.Valid {
				tc.FillMode = tablecolumn.FillMode(value.String)
			}
		case tablecolumn.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				tc.Source = value.String
			}
		case tablecolumn.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				tc.SourceID = value.String
			}
		case tablecolumn.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				tc.SourceType = tablecolumn.SourceType(value.String)
			}
		case tablecolumn.FieldContextLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field context_length", values[i])
			} else if value.Valid {
				tc.ContextLength = int(value.Int64)
			}
		case tablecolumn.FieldTableID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field table_id", values[i])
			} else if value.Valid {
				tc.TableID = int(value.Int64)
			}
		case tablecolumn.FieldRandom:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field random", values[i])
			} else if value.Valid {
				tc.Random = value.Bool
			}
		case tablecolumn.FieldReplacement:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field replacement", values[i])
			} else if value.Valid {
				tc.Replacement = value.Bool
			}
		case tablecolumn.FieldRepeat:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field repeat", values[i])
			} else if value.Valid {
				tc.Repeat = int(value.Int64)
			}
		case tablecolumn.FieldLinkedColumn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field linked_column", values[i])
			} else if value.Valid {
				tc.LinkedColumn = value.String
			}
		case tablecolumn.FieldLinkedContextColumns:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field linked_context_columns", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tc.LinkedContextColumns); err != nil {
					return fmt.Errorf("unmarshal field linked_context_columns: %w", err)
				}
			}
		case tablecolumn.FieldOptions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field options", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tc.Options); err != nil {
					return fmt.Errorf("unmarshal field options: %w", err)
				}
			}
		default:
			tc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TableColumn.
// This includes values selected through modifiers, order, etc.
func (tc *TableColumn) Value(name string) (ent.Value, error) {
	return tc.selectValues.Get(name)
}

// QueryTablemeta queries the "tablemeta" edge of the TableColumn entity.
func (tc *TableColumn) QueryTablemeta() *TableMetaQuery {
	return NewTableColumnClient(tc.config).QueryTablemeta(tc)
}

// Update returns a builder for updating this TableColumn.
// Note that you need to call TableColumn.Unwrap() before calling this method if this TableColumn
// was returned from a transaction, and the transaction was committed or rolled back.
func (tc *TableColumn) Update() *TableColumnUpdateOne {
	return NewTableColumnClient(tc.config).UpdateOne(tc)
}

// Unwrap unwraps the TableColumn entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tc *TableColumn) Unwrap() *TableColumn {
	_tx, ok := tc.config.driver.(*txDriver)
	if !ok {
		panic("ent: TableColumn is not a transactional entity")
	}
	tc.config.driver = _tx.drv
	return tc
}

// String implements the fmt.Stringer.
func (tc *TableColumn) String() string {
	var builder strings.Builder
	builder.WriteString("TableColumn(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tc.ID))
	builder.WriteString("created_at=")
	builder.WriteString(tc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(tc.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("nanoid=")
	builder.WriteString(tc.Nanoid)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(tc.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(tc.Description)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", tc.Type))
	builder.WriteString(", ")
	builder.WriteString("fill_mode=")
	builder.WriteString(fmt.Sprintf("%v", tc.FillMode))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(tc.Source)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(tc.SourceID)
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(fmt.Sprintf("%v", tc.SourceType))
	builder.WriteString(", ")
	builder.WriteString("context_length=")
	builder.WriteString(fmt.Sprintf("%v", tc.ContextLength))
	builder.WriteString(", ")
	builder.WriteString("table_id=")
	builder.WriteString(fmt.Sprintf("%v", tc.TableID))
	builder.WriteString(", ")
	builder.WriteString("random=")
	builder.WriteString(fmt.Sprintf("%v", tc.Random))
	builder.WriteString(", ")
	builder.WriteString("replacement=")
	builder.WriteString(fmt.Sprintf("%v", tc.Replacement))
	builder.WriteString(", ")
	builder.WriteString("repeat=")
	builder.WriteString(fmt.Sprintf("%v", tc.Repeat))
	builder.WriteString(", ")
	builder.WriteString("linked_column=")
	builder.WriteString(tc.LinkedColumn)
	builder.WriteString(", ")
	builder.WriteString("linked_context_columns=")
	builder.WriteString(fmt.Sprintf("%v", tc.LinkedContextColumns))
	builder.WriteString(", ")
	builder.WriteString("options=")
	builder.WriteString(fmt.Sprintf("%v", tc.Options))
	builder.WriteByte(')')
	return builder.String()
}

// TableColumns is a parsable slice of TableColumn.
type TableColumns []*TableColumn
