// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"tablepilot/ent/predicate"
	"tablepilot/ent/tablerow"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TableRowDelete is the builder for deleting a TableRow entity.
type TableRowDelete struct {
	config
	hooks    []Hook
	mutation *TableRowMutation
}

// Where appends a list predicates to the TableRowDelete builder.
func (trd *TableRowDelete) Where(ps ...predicate.TableRow) *TableRowDelete {
	trd.mutation.Where(ps...)
	return trd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (trd *TableRowDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, trd.sqlExec, trd.mutation, trd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (trd *TableRowDelete) ExecX(ctx context.Context) int {
	n, err := trd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (trd *TableRowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tablerow.Table, sqlgraph.NewFieldSpec(tablerow.FieldID, field.TypeInt))
	if ps := trd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, trd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	trd.mutation.done = true
	return affected, err
}

// TableRowDeleteOne is the builder for deleting a single TableRow entity.
type TableRowDeleteOne struct {
	trd *TableRowDelete
}

// Where appends a list predicates to the TableRowDelete builder.
func (trdo *TableRowDeleteOne) Where(ps ...predicate.TableRow) *TableRowDeleteOne {
	trdo.trd.mutation.Where(ps...)
	return trdo
}

// Exec executes the deletion query.
func (trdo *TableRowDeleteOne) Exec(ctx context.Context) error {
	n, err := trdo.trd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tablerow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (trdo *TableRowDeleteOne) ExecX(ctx context.Context) {
	if err := trdo.Exec(ctx); err != nil {
		panic(err)
	}
}
