// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Yiling-J/tablepilot/ent/tablemeta"
)

// TableMeta is the model entity for the TableMeta schema.
type TableMeta struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Nanoid holds the value of the "nanoid" field.
	Nanoid string `json:"nanoid,omitempty"`
	// MaxRows holds the value of the "max_rows" field.
	MaxRows int `json:"max_rows,omitempty"`
	// PromptRaw holds the value of the "prompt_raw" field.
	PromptRaw string `json:"prompt_raw,omitempty"`
	// PromptGen holds the value of the "prompt_gen" field.
	PromptGen string `json:"prompt_gen,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// BuildStatus holds the value of the "build_status" field.
	BuildStatus tablemeta.BuildStatus `json:"build_status,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TableMetaQuery when eager-loading is set.
	Edges        TableMetaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TableMetaEdges holds the relations/edges for other nodes in the graph.
type TableMetaEdges struct {
	// Columns holds the value of the columns edge.
	Columns []*TableColumn `json:"columns,omitempty"`
	// Rows holds the value of the rows edge.
	Rows []*TableRow `json:"rows,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ColumnsOrErr returns the Columns value or an error if the edge
// was not loaded in eager-loading.
func (e TableMetaEdges) ColumnsOrErr() ([]*TableColumn, error) {
	if e.loadedTypes[0] {
		return e.Columns, nil
	}
	return nil, &NotLoadedError{edge: "columns"}
}

// RowsOrErr returns the Rows value or an error if the edge
// was not loaded in eager-loading.
func (e TableMetaEdges) RowsOrErr() ([]*TableRow, error) {
	if e.loadedTypes[1] {
		return e.Rows, nil
	}
	return nil, &NotLoadedError{edge: "rows"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TableMeta) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tablemeta.FieldID, tablemeta.FieldMaxRows:
			values[i] = new(sql.NullInt64)
		case tablemeta.FieldNanoid, tablemeta.FieldPromptRaw, tablemeta.FieldPromptGen, tablemeta.FieldName, tablemeta.FieldDescription, tablemeta.FieldBuildStatus, tablemeta.FieldModel:
			values[i] = new(sql.NullString)
		case tablemeta.FieldCreatedAt, tablemeta.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TableMeta fields.
func (tm *TableMeta) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tablemeta.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tm.ID = int(value.Int64)
		case tablemeta.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tm.CreatedAt = value.Time
			}
		case tablemeta.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				tm.UpdatedAt = value.Time
			}
		case tablemeta.FieldNanoid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nanoid", values[i])
			} else if value.Valid {
				tm.Nanoid = value.String
			}
		case tablemeta.FieldMaxRows:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_rows", values[i])
			} else if value.Valid {
				tm.MaxRows = int(value.Int64)
			}
		case tablemeta.FieldPromptRaw:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_raw", values[i])
			} else if value.Valid {
				tm.PromptRaw = value.String
			}
		case tablemeta.FieldPromptGen:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_gen", values[i])
			} else if value.Valid {
				tm.PromptGen = value.String
			}
		case tablemeta.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				tm.Name = value.String
			}
		case tablemeta.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				tm.Description = value.String
			}
		case tablemeta.FieldBuildStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field build_status", values[i])
			} else if value.Valid {
				tm.BuildStatus = tablemeta.BuildStatus(value.String)
			}
		case tablemeta.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				tm.Model = value.String
			}
		default:
			tm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TableMeta.
// This includes values selected through modifiers, order, etc.
func (tm *TableMeta) Value(name string) (ent.Value, error) {
	return tm.selectValues.Get(name)
}

// QueryColumns queries the "columns" edge of the TableMeta entity.
func (tm *TableMeta) QueryColumns() *TableColumnQuery {
	return NewTableMetaClient(tm.config).QueryColumns(tm)
}

// QueryRows queries the "rows" edge of the TableMeta entity.
func (tm *TableMeta) QueryRows() *TableRowQuery {
	return NewTableMetaClient(tm.config).QueryRows(tm)
}

// Update returns a builder for updating this TableMeta.
// Note that you need to call TableMeta.Unwrap() before calling this method if this TableMeta
// was returned from a transaction, and the transaction was committed or rolled back.
func (tm *TableMeta) Update() *TableMetaUpdateOne {
	return NewTableMetaClient(tm.config).UpdateOne(tm)
}

// Unwrap unwraps the TableMeta entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tm *TableMeta) Unwrap() *TableMeta {
	_tx, ok := tm.config.driver.(*txDriver)
	if !ok {
		panic("ent: TableMeta is not a transactional entity")
	}
	tm.config.driver = _tx.drv
	return tm
}

// String implements the fmt.Stringer.
func (tm *TableMeta) String() string {
	var builder strings.Builder
	builder.WriteString("TableMeta(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tm.ID))
	builder.WriteString("created_at=")
	builder.WriteString(tm.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(tm.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("nanoid=")
	builder.WriteString(tm.Nanoid)
	builder.WriteString(", ")
	builder.WriteString("max_rows=")
	builder.WriteString(fmt.Sprintf("%v", tm.MaxRows))
	builder.WriteString(", ")
	builder.WriteString("prompt_raw=")
	builder.WriteString(tm.PromptRaw)
	builder.WriteString(", ")
	builder.WriteString("prompt_gen=")
	builder.WriteString(tm.PromptGen)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(tm.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(tm.Description)
	builder.WriteString(", ")
	builder.WriteString("build_status=")
	builder.WriteString(fmt.Sprintf("%v", tm.BuildStatus))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(tm.Model)
	builder.WriteByte(')')
	return builder.String()
}

// TableMetaSlice is a parsable slice of TableMeta.
type TableMetaSlice []*TableMeta
