// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Yiling-J/tablepilot/ent/predicate"
	"github.com/Yiling-J/tablepilot/ent/tablemeta"
)

// TableMetaDelete is the builder for deleting a TableMeta entity.
type TableMetaDelete struct {
	config
	hooks    []Hook
	mutation *TableMetaMutation
}

// Where appends a list predicates to the TableMetaDelete builder.
func (tmd *TableMetaDelete) Where(ps ...predicate.TableMeta) *TableMetaDelete {
	tmd.mutation.Where(ps...)
	return tmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tmd *TableMetaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tmd.sqlExec, tmd.mutation, tmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tmd *TableMetaDelete) ExecX(ctx context.Context) int {
	n, err := tmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tmd *TableMetaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tablemeta.Table, sqlgraph.NewFieldSpec(tablemeta.FieldID, field.TypeInt))
	if ps := tmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tmd.mutation.done = true
	return affected, err
}

// TableMetaDeleteOne is the builder for deleting a single TableMeta entity.
type TableMetaDeleteOne struct {
	tmd *TableMetaDelete
}

// Where appends a list predicates to the TableMetaDelete builder.
func (tmdo *TableMetaDeleteOne) Where(ps ...predicate.TableMeta) *TableMetaDeleteOne {
	tmdo.tmd.mutation.Where(ps...)
	return tmdo
}

// Exec executes the deletion query.
func (tmdo *TableMetaDeleteOne) Exec(ctx context.Context) error {
	n, err := tmdo.tmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tablemeta.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tmdo *TableMetaDeleteOne) ExecX(ctx context.Context) {
	if err := tmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
