// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Yiling-J/tablepilot/ent/tablecolumn"
	"github.com/Yiling-J/tablepilot/ent/tablemeta"
)

// TableColumnCreate is the builder for creating a TableColumn entity.
type TableColumnCreate struct {
	config
	mutation *TableColumnMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (tcc *TableColumnCreate) SetCreatedAt(t time.Time) *TableColumnCreate {
	tcc.mutation.SetCreatedAt(t)
	return tcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tcc *TableColumnCreate) SetNillableCreatedAt(t *time.Time) *TableColumnCreate {
	if t != nil {
		tcc.SetCreatedAt(*t)
	}
	return tcc
}

// SetUpdatedAt sets the "updated_at" field.
func (tcc *TableColumnCreate) SetUpdatedAt(t time.Time) *TableColumnCreate {
	tcc.mutation.SetUpdatedAt(t)
	return tcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tcc *TableColumnCreate) SetNillableUpdatedAt(t *time.Time) *TableColumnCreate {
	if t != nil {
		tcc.SetUpdatedAt(*t)
	}
	return tcc
}

// SetNanoid sets the "nanoid" field.
func (tcc *TableColumnCreate) SetNanoid(s string) *TableColumnCreate {
	tcc.mutation.SetNanoid(s)
	return tcc
}

// SetNillableNanoid sets the "nanoid" field if the given value is not nil.
func (tcc *TableColumnCreate) SetNillableNanoid(s *string) *TableColumnCreate {
	if s != nil {
		tcc.SetNanoid(*s)
	}
	return tcc
}

// SetName sets the "name" field.
func (tcc *TableColumnCreate) SetName(s string) *TableColumnCreate {
	tcc.mutation.SetName(s)
	return tcc
}

// SetDescription sets the "description" field.
func (tcc *TableColumnCreate) SetDescription(s string) *TableColumnCreate {
	tcc.mutation.SetDescription(s)
	return tcc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tcc *TableColumnCreate) SetNillableDescription(s *string) *TableColumnCreate {
	if s != nil {
		tcc.SetDescription(*s)
	}
	return tcc
}

// SetType sets the "type" field.
func (tcc *TableColumnCreate) SetType(t tablecolumn.Type) *TableColumnCreate {
	tcc.mutation.SetType(t)
	return tcc
}

// SetFillMode sets the "fill_mode" field.
func (tcc *TableColumnCreate) SetFillMode(tm tablecolumn.FillMode) *TableColumnCreate {
	tcc.mutation.SetFillMode(tm)
	return tcc
}

// SetSource sets the "source" field.
func (tcc *TableColumnCreate) SetSource(jm json.RawMessage) *TableColumnCreate {
	tcc.mutation.SetSource(jm)
	return tcc
}

// SetContextLength sets the "context_length" field.
func (tcc *TableColumnCreate) SetContextLength(i int) *TableColumnCreate {
	tcc.mutation.SetContextLength(i)
	return tcc
}

// SetNillableContextLength sets the "context_length" field if the given value is not nil.
func (tcc *TableColumnCreate) SetNillableContextLength(i *int) *TableColumnCreate {
	if i != nil {
		tcc.SetContextLength(*i)
	}
	return tcc
}

// SetTableID sets the "table_id" field.
func (tcc *TableColumnCreate) SetTableID(i int) *TableColumnCreate {
	tcc.mutation.SetTableID(i)
	return tcc
}

// SetTablemetaID sets the "tablemeta" edge to the TableMeta entity by ID.
func (tcc *TableColumnCreate) SetTablemetaID(id int) *TableColumnCreate {
	tcc.mutation.SetTablemetaID(id)
	return tcc
}

// SetTablemeta sets the "tablemeta" edge to the TableMeta entity.
func (tcc *TableColumnCreate) SetTablemeta(t *TableMeta) *TableColumnCreate {
	return tcc.SetTablemetaID(t.ID)
}

// Mutation returns the TableColumnMutation object of the builder.
func (tcc *TableColumnCreate) Mutation() *TableColumnMutation {
	return tcc.mutation
}

// Save creates the TableColumn in the database.
func (tcc *TableColumnCreate) Save(ctx context.Context) (*TableColumn, error) {
	tcc.defaults()
	return withHooks(ctx, tcc.sqlSave, tcc.mutation, tcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tcc *TableColumnCreate) SaveX(ctx context.Context) *TableColumn {
	v, err := tcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcc *TableColumnCreate) Exec(ctx context.Context) error {
	_, err := tcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcc *TableColumnCreate) ExecX(ctx context.Context) {
	if err := tcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tcc *TableColumnCreate) defaults() {
	if _, ok := tcc.mutation.CreatedAt(); !ok {
		v := tablecolumn.DefaultCreatedAt()
		tcc.mutation.SetCreatedAt(v)
	}
	if _, ok := tcc.mutation.UpdatedAt(); !ok {
		v := tablecolumn.DefaultUpdatedAt()
		tcc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tcc.mutation.ContextLength(); !ok {
		v := tablecolumn.DefaultContextLength
		tcc.mutation.SetContextLength(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tcc *TableColumnCreate) check() error {
	if _, ok := tcc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TableColumn.name"`)}
	}
	if v, ok := tcc.mutation.Name(); ok {
		if err := tablecolumn.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TableColumn.name": %w`, err)}
		}
	}
	if _, ok := tcc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "TableColumn.type"`)}
	}
	if v, ok := tcc.mutation.GetType(); ok {
		if err := tablecolumn.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "TableColumn.type": %w`, err)}
		}
	}
	if _, ok := tcc.mutation.FillMode(); !ok {
		return &ValidationError{Name: "fill_mode", err: errors.New(`ent: missing required field "TableColumn.fill_mode"`)}
	}
	if v, ok := tcc.mutation.FillMode(); ok {
		if err := tablecolumn.FillModeValidator(v); err != nil {
			return &ValidationError{Name: "fill_mode", err: fmt.Errorf(`ent: validator failed for field "TableColumn.fill_mode": %w`, err)}
		}
	}
	if _, ok := tcc.mutation.ContextLength(); !ok {
		return &ValidationError{Name: "context_length", err: errors.New(`ent: missing required field "TableColumn.context_length"`)}
	}
	if _, ok := tcc.mutation.TableID(); !ok {
		return &ValidationError{Name: "table_id", err: errors.New(`ent: missing required field "TableColumn.table_id"`)}
	}
	if len(tcc.mutation.TablemetaIDs()) == 0 {
		return &ValidationError{Name: "tablemeta", err: errors.New(`ent: missing required edge "TableColumn.tablemeta"`)}
	}
	return nil
}

func (tcc *TableColumnCreate) sqlSave(ctx context.Context) (*TableColumn, error) {
	if err := tcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tcc.mutation.id = &_node.ID
	tcc.mutation.done = true
	return _node, nil
}

func (tcc *TableColumnCreate) createSpec() (*TableColumn, *sqlgraph.CreateSpec) {
	var (
		_node = &TableColumn{config: tcc.config}
		_spec = sqlgraph.NewCreateSpec(tablecolumn.Table, sqlgraph.NewFieldSpec(tablecolumn.FieldID, field.TypeInt))
	)
	_spec.OnConflict = tcc.conflict
	if value, ok := tcc.mutation.CreatedAt(); ok {
		_spec.SetField(tablecolumn.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tcc.mutation.UpdatedAt(); ok {
		_spec.SetField(tablecolumn.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := tcc.mutation.Nanoid(); ok {
		_spec.SetField(tablecolumn.FieldNanoid, field.TypeString, value)
		_node.Nanoid = value
	}
	if value, ok := tcc.mutation.Name(); ok {
		_spec.SetField(tablecolumn.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tcc.mutation.Description(); ok {
		_spec.SetField(tablecolumn.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := tcc.mutation.GetType(); ok {
		_spec.SetField(tablecolumn.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := tcc.mutation.FillMode(); ok {
		_spec.SetField(tablecolumn.FieldFillMode, field.TypeEnum, value)
		_node.FillMode = value
	}
	if value, ok := tcc.mutation.Source(); ok {
		_spec.SetField(tablecolumn.FieldSource, field.TypeJSON, value)
		_node.Source = value
	}
	if value, ok := tcc.mutation.ContextLength(); ok {
		_spec.SetField(tablecolumn.FieldContextLength, field.TypeInt, value)
		_node.ContextLength = value
	}
	if nodes := tcc.mutation.TablemetaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tablecolumn.TablemetaTable,
			Columns: []string{tablecolumn.TablemetaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tablemeta.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TableID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TableColumn.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TableColumnUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (tcc *TableColumnCreate) OnConflict(opts ...sql.ConflictOption) *TableColumnUpsertOne {
	tcc.conflict = opts
	return &TableColumnUpsertOne{
		create: tcc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TableColumn.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tcc *TableColumnCreate) OnConflictColumns(columns ...string) *TableColumnUpsertOne {
	tcc.conflict = append(tcc.conflict, sql.ConflictColumns(columns...))
	return &TableColumnUpsertOne{
		create: tcc,
	}
}

type (
	// TableColumnUpsertOne is the builder for "upsert"-ing
	//  one TableColumn node.
	TableColumnUpsertOne struct {
		create *TableColumnCreate
	}

	// TableColumnUpsert is the "OnConflict" setter.
	TableColumnUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TableColumnUpsert) SetUpdatedAt(v time.Time) *TableColumnUpsert {
	u.Set(tablecolumn.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TableColumnUpsert) UpdateUpdatedAt() *TableColumnUpsert {
	u.SetExcluded(tablecolumn.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TableColumnUpsert) ClearUpdatedAt() *TableColumnUpsert {
	u.SetNull(tablecolumn.FieldUpdatedAt)
	return u
}

// SetNanoid sets the "nanoid" field.
func (u *TableColumnUpsert) SetNanoid(v string) *TableColumnUpsert {
	u.Set(tablecolumn.FieldNanoid, v)
	return u
}

// UpdateNanoid sets the "nanoid" field to the value that was provided on create.
func (u *TableColumnUpsert) UpdateNanoid() *TableColumnUpsert {
	u.SetExcluded(tablecolumn.FieldNanoid)
	return u
}

// ClearNanoid clears the value of the "nanoid" field.
func (u *TableColumnUpsert) ClearNanoid() *TableColumnUpsert {
	u.SetNull(tablecolumn.FieldNanoid)
	return u
}

// SetName sets the "name" field.
func (u *TableColumnUpsert) SetName(v string) *TableColumnUpsert {
	u.Set(tablecolumn.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TableColumnUpsert) UpdateName() *TableColumnUpsert {
	u.SetExcluded(tablecolumn.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *TableColumnUpsert) SetDescription(v string) *TableColumnUpsert {
	u.Set(tablecolumn.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TableColumnUpsert) UpdateDescription() *TableColumnUpsert {
	u.SetExcluded(tablecolumn.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *TableColumnUpsert) ClearDescription() *TableColumnUpsert {
	u.SetNull(tablecolumn.FieldDescription)
	return u
}

// SetType sets the "type" field.
func (u *TableColumnUpsert) SetType(v tablecolumn.Type) *TableColumnUpsert {
	u.Set(tablecolumn.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TableColumnUpsert) UpdateType() *TableColumnUpsert {
	u.SetExcluded(tablecolumn.FieldType)
	return u
}

// SetFillMode sets the "fill_mode" field.
func (u *TableColumnUpsert) SetFillMode(v tablecolumn.FillMode) *TableColumnUpsert {
	u.Set(tablecolumn.FieldFillMode, v)
	return u
}

// UpdateFillMode sets the "fill_mode" field to the value that was provided on create.
func (u *TableColumnUpsert) UpdateFillMode() *TableColumnUpsert {
	u.SetExcluded(tablecolumn.FieldFillMode)
	return u
}

// SetSource sets the "source" field.
func (u *TableColumnUpsert) SetSource(v json.RawMessage) *TableColumnUpsert {
	u.Set(tablecolumn.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *TableColumnUpsert) UpdateSource() *TableColumnUpsert {
	u.SetExcluded(tablecolumn.FieldSource)
	return u
}

// ClearSource clears the value of the "source" field.
func (u *TableColumnUpsert) ClearSource() *TableColumnUpsert {
	u.SetNull(tablecolumn.FieldSource)
	return u
}

// SetContextLength sets the "context_length" field.
func (u *TableColumnUpsert) SetContextLength(v int) *TableColumnUpsert {
	u.Set(tablecolumn.FieldContextLength, v)
	return u
}

// UpdateContextLength sets the "context_length" field to the value that was provided on create.
func (u *TableColumnUpsert) UpdateContextLength() *TableColumnUpsert {
	u.SetExcluded(tablecolumn.FieldContextLength)
	return u
}

// AddContextLength adds v to the "context_length" field.
func (u *TableColumnUpsert) AddContextLength(v int) *TableColumnUpsert {
	u.Add(tablecolumn.FieldContextLength, v)
	return u
}

// SetTableID sets the "table_id" field.
func (u *TableColumnUpsert) SetTableID(v int) *TableColumnUpsert {
	u.Set(tablecolumn.FieldTableID, v)
	return u
}

// UpdateTableID sets the "table_id" field to the value that was provided on create.
func (u *TableColumnUpsert) UpdateTableID() *TableColumnUpsert {
	u.SetExcluded(tablecolumn.FieldTableID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TableColumn.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TableColumnUpsertOne) UpdateNewValues() *TableColumnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(tablecolumn.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TableColumn.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TableColumnUpsertOne) Ignore() *TableColumnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TableColumnUpsertOne) DoNothing() *TableColumnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TableColumnCreate.OnConflict
// documentation for more info.
func (u *TableColumnUpsertOne) Update(set func(*TableColumnUpsert)) *TableColumnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TableColumnUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TableColumnUpsertOne) SetUpdatedAt(v time.Time) *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TableColumnUpsertOne) UpdateUpdatedAt() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TableColumnUpsertOne) ClearUpdatedAt() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetNanoid sets the "nanoid" field.
func (u *TableColumnUpsertOne) SetNanoid(v string) *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetNanoid(v)
	})
}

// UpdateNanoid sets the "nanoid" field to the value that was provided on create.
func (u *TableColumnUpsertOne) UpdateNanoid() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateNanoid()
	})
}

// ClearNanoid clears the value of the "nanoid" field.
func (u *TableColumnUpsertOne) ClearNanoid() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.ClearNanoid()
	})
}

// SetName sets the "name" field.
func (u *TableColumnUpsertOne) SetName(v string) *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TableColumnUpsertOne) UpdateName() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *TableColumnUpsertOne) SetDescription(v string) *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TableColumnUpsertOne) UpdateDescription() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TableColumnUpsertOne) ClearDescription() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.ClearDescription()
	})
}

// SetType sets the "type" field.
func (u *TableColumnUpsertOne) SetType(v tablecolumn.Type) *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TableColumnUpsertOne) UpdateType() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateType()
	})
}

// SetFillMode sets the "fill_mode" field.
func (u *TableColumnUpsertOne) SetFillMode(v tablecolumn.FillMode) *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetFillMode(v)
	})
}

// UpdateFillMode sets the "fill_mode" field to the value that was provided on create.
func (u *TableColumnUpsertOne) UpdateFillMode() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateFillMode()
	})
}

// SetSource sets the "source" field.
func (u *TableColumnUpsertOne) SetSource(v json.RawMessage) *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *TableColumnUpsertOne) UpdateSource() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *TableColumnUpsertOne) ClearSource() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.ClearSource()
	})
}

// SetContextLength sets the "context_length" field.
func (u *TableColumnUpsertOne) SetContextLength(v int) *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetContextLength(v)
	})
}

// AddContextLength adds v to the "context_length" field.
func (u *TableColumnUpsertOne) AddContextLength(v int) *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.AddContextLength(v)
	})
}

// UpdateContextLength sets the "context_length" field to the value that was provided on create.
func (u *TableColumnUpsertOne) UpdateContextLength() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateContextLength()
	})
}

// SetTableID sets the "table_id" field.
func (u *TableColumnUpsertOne) SetTableID(v int) *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetTableID(v)
	})
}

// UpdateTableID sets the "table_id" field to the value that was provided on create.
func (u *TableColumnUpsertOne) UpdateTableID() *TableColumnUpsertOne {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateTableID()
	})
}

// Exec executes the query.
func (u *TableColumnUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TableColumnCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TableColumnUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TableColumnUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TableColumnUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TableColumnCreateBulk is the builder for creating many TableColumn entities in bulk.
type TableColumnCreateBulk struct {
	config
	err      error
	builders []*TableColumnCreate
	conflict []sql.ConflictOption
}

// Save creates the TableColumn entities in the database.
func (tccb *TableColumnCreateBulk) Save(ctx context.Context) ([]*TableColumn, error) {
	if tccb.err != nil {
		return nil, tccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tccb.builders))
	nodes := make([]*TableColumn, len(tccb.builders))
	mutators := make([]Mutator, len(tccb.builders))
	for i := range tccb.builders {
		func(i int, root context.Context) {
			builder := tccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TableColumnMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tccb *TableColumnCreateBulk) SaveX(ctx context.Context) []*TableColumn {
	v, err := tccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tccb *TableColumnCreateBulk) Exec(ctx context.Context) error {
	_, err := tccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tccb *TableColumnCreateBulk) ExecX(ctx context.Context) {
	if err := tccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TableColumn.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TableColumnUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (tccb *TableColumnCreateBulk) OnConflict(opts ...sql.ConflictOption) *TableColumnUpsertBulk {
	tccb.conflict = opts
	return &TableColumnUpsertBulk{
		create: tccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TableColumn.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tccb *TableColumnCreateBulk) OnConflictColumns(columns ...string) *TableColumnUpsertBulk {
	tccb.conflict = append(tccb.conflict, sql.ConflictColumns(columns...))
	return &TableColumnUpsertBulk{
		create: tccb,
	}
}

// TableColumnUpsertBulk is the builder for "upsert"-ing
// a bulk of TableColumn nodes.
type TableColumnUpsertBulk struct {
	create *TableColumnCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TableColumn.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TableColumnUpsertBulk) UpdateNewValues() *TableColumnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(tablecolumn.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TableColumn.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TableColumnUpsertBulk) Ignore() *TableColumnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TableColumnUpsertBulk) DoNothing() *TableColumnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TableColumnCreateBulk.OnConflict
// documentation for more info.
func (u *TableColumnUpsertBulk) Update(set func(*TableColumnUpsert)) *TableColumnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TableColumnUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TableColumnUpsertBulk) SetUpdatedAt(v time.Time) *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TableColumnUpsertBulk) UpdateUpdatedAt() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TableColumnUpsertBulk) ClearUpdatedAt() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetNanoid sets the "nanoid" field.
func (u *TableColumnUpsertBulk) SetNanoid(v string) *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetNanoid(v)
	})
}

// UpdateNanoid sets the "nanoid" field to the value that was provided on create.
func (u *TableColumnUpsertBulk) UpdateNanoid() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateNanoid()
	})
}

// ClearNanoid clears the value of the "nanoid" field.
func (u *TableColumnUpsertBulk) ClearNanoid() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.ClearNanoid()
	})
}

// SetName sets the "name" field.
func (u *TableColumnUpsertBulk) SetName(v string) *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TableColumnUpsertBulk) UpdateName() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *TableColumnUpsertBulk) SetDescription(v string) *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TableColumnUpsertBulk) UpdateDescription() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TableColumnUpsertBulk) ClearDescription() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.ClearDescription()
	})
}

// SetType sets the "type" field.
func (u *TableColumnUpsertBulk) SetType(v tablecolumn.Type) *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TableColumnUpsertBulk) UpdateType() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateType()
	})
}

// SetFillMode sets the "fill_mode" field.
func (u *TableColumnUpsertBulk) SetFillMode(v tablecolumn.FillMode) *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetFillMode(v)
	})
}

// UpdateFillMode sets the "fill_mode" field to the value that was provided on create.
func (u *TableColumnUpsertBulk) UpdateFillMode() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateFillMode()
	})
}

// SetSource sets the "source" field.
func (u *TableColumnUpsertBulk) SetSource(v json.RawMessage) *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *TableColumnUpsertBulk) UpdateSource() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateSource()
	})
}

// ClearSource clears the value of the "source" field.
func (u *TableColumnUpsertBulk) ClearSource() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.ClearSource()
	})
}

// SetContextLength sets the "context_length" field.
func (u *TableColumnUpsertBulk) SetContextLength(v int) *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetContextLength(v)
	})
}

// AddContextLength adds v to the "context_length" field.
func (u *TableColumnUpsertBulk) AddContextLength(v int) *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.AddContextLength(v)
	})
}

// UpdateContextLength sets the "context_length" field to the value that was provided on create.
func (u *TableColumnUpsertBulk) UpdateContextLength() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateContextLength()
	})
}

// SetTableID sets the "table_id" field.
func (u *TableColumnUpsertBulk) SetTableID(v int) *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.SetTableID(v)
	})
}

// UpdateTableID sets the "table_id" field to the value that was provided on create.
func (u *TableColumnUpsertBulk) UpdateTableID() *TableColumnUpsertBulk {
	return u.Update(func(s *TableColumnUpsert) {
		s.UpdateTableID()
	})
}

// Exec executes the query.
func (u *TableColumnUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TableColumnCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TableColumnCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TableColumnUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
