// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Yiling-J/tablepilot/ent/schema"
	"github.com/Yiling-J/tablepilot/ent/workflow"
)

// WorkflowCreate is the builder for creating a Workflow entity.
type WorkflowCreate struct {
	config
	mutation *WorkflowMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (wc *WorkflowCreate) SetCreatedAt(t time.Time) *WorkflowCreate {
	wc.mutation.SetCreatedAt(t)
	return wc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wc *WorkflowCreate) SetNillableCreatedAt(t *time.Time) *WorkflowCreate {
	if t != nil {
		wc.SetCreatedAt(*t)
	}
	return wc
}

// SetUpdatedAt sets the "updated_at" field.
func (wc *WorkflowCreate) SetUpdatedAt(t time.Time) *WorkflowCreate {
	wc.mutation.SetUpdatedAt(t)
	return wc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wc *WorkflowCreate) SetNillableUpdatedAt(t *time.Time) *WorkflowCreate {
	if t != nil {
		wc.SetUpdatedAt(*t)
	}
	return wc
}

// SetNanoid sets the "nanoid" field.
func (wc *WorkflowCreate) SetNanoid(s string) *WorkflowCreate {
	wc.mutation.SetNanoid(s)
	return wc
}

// SetNillableNanoid sets the "nanoid" field if the given value is not nil.
func (wc *WorkflowCreate) SetNillableNanoid(s *string) *WorkflowCreate {
	if s != nil {
		wc.SetNanoid(*s)
	}
	return wc
}

// SetName sets the "name" field.
func (wc *WorkflowCreate) SetName(s string) *WorkflowCreate {
	wc.mutation.SetName(s)
	return wc
}

// SetVariables sets the "variables" field.
func (wc *WorkflowCreate) SetVariables(sv []schema.WorkflowVariable) *WorkflowCreate {
	wc.mutation.SetVariables(sv)
	return wc
}

// SetSteps sets the "steps" field.
func (wc *WorkflowCreate) SetSteps(ss []schema.WorkflowStep) *WorkflowCreate {
	wc.mutation.SetSteps(ss)
	return wc
}

// Mutation returns the WorkflowMutation object of the builder.
func (wc *WorkflowCreate) Mutation() *WorkflowMutation {
	return wc.mutation
}

// Save creates the Workflow in the database.
func (wc *WorkflowCreate) Save(ctx context.Context) (*Workflow, error) {
	wc.defaults()
	return withHooks(ctx, wc.sqlSave, wc.mutation, wc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wc *WorkflowCreate) SaveX(ctx context.Context) *Workflow {
	v, err := wc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wc *WorkflowCreate) Exec(ctx context.Context) error {
	_, err := wc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wc *WorkflowCreate) ExecX(ctx context.Context) {
	if err := wc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wc *WorkflowCreate) defaults() {
	if _, ok := wc.mutation.CreatedAt(); !ok {
		v := workflow.DefaultCreatedAt()
		wc.mutation.SetCreatedAt(v)
	}
	if _, ok := wc.mutation.UpdatedAt(); !ok {
		v := workflow.DefaultUpdatedAt()
		wc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wc *WorkflowCreate) check() error {
	if _, ok := wc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Workflow.name"`)}
	}
	if v, ok := wc.mutation.Name(); ok {
		if err := workflow.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workflow.name": %w`, err)}
		}
	}
	if _, ok := wc.mutation.Variables(); !ok {
		return &ValidationError{Name: "variables", err: errors.New(`ent: missing required field "Workflow.variables"`)}
	}
	if _, ok := wc.mutation.Steps(); !ok {
		return &ValidationError{Name: "steps", err: errors.New(`ent: missing required field "Workflow.steps"`)}
	}
	return nil
}

func (wc *WorkflowCreate) sqlSave(ctx context.Context) (*Workflow, error) {
	if err := wc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	wc.mutation.id = &_node.ID
	wc.mutation.done = true
	return _node, nil
}

func (wc *WorkflowCreate) createSpec() (*Workflow, *sqlgraph.CreateSpec) {
	var (
		_node = &Workflow{config: wc.config}
		_spec = sqlgraph.NewCreateSpec(workflow.Table, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeInt))
	)
	_spec.OnConflict = wc.conflict
	if value, ok := wc.mutation.CreatedAt(); ok {
		_spec.SetField(workflow.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := wc.mutation.UpdatedAt(); ok {
		_spec.SetField(workflow.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := wc.mutation.Nanoid(); ok {
		_spec.SetField(workflow.FieldNanoid, field.TypeString, value)
		_node.Nanoid = value
	}
	if value, ok := wc.mutation.Name(); ok {
		_spec.SetField(workflow.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := wc.mutation.Variables(); ok {
		_spec.SetField(workflow.FieldVariables, field.TypeJSON, value)
		_node.Variables = value
	}
	if value, ok := wc.mutation.Steps(); ok {
		_spec.SetField(workflow.FieldSteps, field.TypeJSON, value)
		_node.Steps = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Workflow.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkflowUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (wc *WorkflowCreate) OnConflict(opts ...sql.ConflictOption) *WorkflowUpsertOne {
	wc.conflict = opts
	return &WorkflowUpsertOne{
		create: wc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Workflow.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (wc *WorkflowCreate) OnConflictColumns(columns ...string) *WorkflowUpsertOne {
	wc.conflict = append(wc.conflict, sql.ConflictColumns(columns...))
	return &WorkflowUpsertOne{
		create: wc,
	}
}

type (
	// WorkflowUpsertOne is the builder for "upsert"-ing
	//  one Workflow node.
	WorkflowUpsertOne struct {
		create *WorkflowCreate
	}

	// WorkflowUpsert is the "OnConflict" setter.
	WorkflowUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkflowUpsert) SetUpdatedAt(v time.Time) *WorkflowUpsert {
	u.Set(workflow.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkflowUpsert) UpdateUpdatedAt() *WorkflowUpsert {
	u.SetExcluded(workflow.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *WorkflowUpsert) ClearUpdatedAt() *WorkflowUpsert {
	u.SetNull(workflow.FieldUpdatedAt)
	return u
}

// SetNanoid sets the "nanoid" field.
func (u *WorkflowUpsert) SetNanoid(v string) *WorkflowUpsert {
	u.Set(workflow.FieldNanoid, v)
	return u
}

// UpdateNanoid sets the "nanoid" field to the value that was provided on create.
func (u *WorkflowUpsert) UpdateNanoid() *WorkflowUpsert {
	u.SetExcluded(workflow.FieldNanoid)
	return u
}

// ClearNanoid clears the value of the "nanoid" field.
func (u *WorkflowUpsert) ClearNanoid() *WorkflowUpsert {
	u.SetNull(workflow.FieldNanoid)
	return u
}

// SetName sets the "name" field.
func (u *WorkflowUpsert) SetName(v string) *WorkflowUpsert {
	u.Set(workflow.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WorkflowUpsert) UpdateName() *WorkflowUpsert {
	u.SetExcluded(workflow.FieldName)
	return u
}

// SetVariables sets the "variables" field.
func (u *WorkflowUpsert) SetVariables(v []schema.WorkflowVariable) *WorkflowUpsert {
	u.Set(workflow.FieldVariables, v)
	return u
}

// UpdateVariables sets the "variables" field to the value that was provided on create.
func (u *WorkflowUpsert) UpdateVariables() *WorkflowUpsert {
	u.SetExcluded(workflow.FieldVariables)
	return u
}

// SetSteps sets the "steps" field.
func (u *WorkflowUpsert) SetSteps(v []schema.WorkflowStep) *WorkflowUpsert {
	u.Set(workflow.FieldSteps, v)
	return u
}

// UpdateSteps sets the "steps" field to the value that was provided on create.
func (u *WorkflowUpsert) UpdateSteps() *WorkflowUpsert {
	u.SetExcluded(workflow.FieldSteps)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Workflow.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WorkflowUpsertOne) UpdateNewValues() *WorkflowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(workflow.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Workflow.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WorkflowUpsertOne) Ignore() *WorkflowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkflowUpsertOne) DoNothing() *WorkflowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkflowCreate.OnConflict
// documentation for more info.
func (u *WorkflowUpsertOne) Update(set func(*WorkflowUpsert)) *WorkflowUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkflowUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkflowUpsertOne) SetUpdatedAt(v time.Time) *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkflowUpsertOne) UpdateUpdatedAt() *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *WorkflowUpsertOne) ClearUpdatedAt() *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetNanoid sets the "nanoid" field.
func (u *WorkflowUpsertOne) SetNanoid(v string) *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.SetNanoid(v)
	})
}

// UpdateNanoid sets the "nanoid" field to the value that was provided on create.
func (u *WorkflowUpsertOne) UpdateNanoid() *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.UpdateNanoid()
	})
}

// ClearNanoid clears the value of the "nanoid" field.
func (u *WorkflowUpsertOne) ClearNanoid() *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.ClearNanoid()
	})
}

// SetName sets the "name" field.
func (u *WorkflowUpsertOne) SetName(v string) *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WorkflowUpsertOne) UpdateName() *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.UpdateName()
	})
}

// SetVariables sets the "variables" field.
func (u *WorkflowUpsertOne) SetVariables(v []schema.WorkflowVariable) *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.SetVariables(v)
	})
}

// UpdateVariables sets the "variables" field to the value that was provided on create.
func (u *WorkflowUpsertOne) UpdateVariables() *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.UpdateVariables()
	})
}

// SetSteps sets the "steps" field.
func (u *WorkflowUpsertOne) SetSteps(v []schema.WorkflowStep) *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.SetSteps(v)
	})
}

// UpdateSteps sets the "steps" field to the value that was provided on create.
func (u *WorkflowUpsertOne) UpdateSteps() *WorkflowUpsertOne {
	return u.Update(func(s *WorkflowUpsert) {
		s.UpdateSteps()
	})
}

// Exec executes the query.
func (u *WorkflowUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkflowCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkflowUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WorkflowUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WorkflowUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WorkflowCreateBulk is the builder for creating many Workflow entities in bulk.
type WorkflowCreateBulk struct {
	config
	err      error
	builders []*WorkflowCreate
	conflict []sql.ConflictOption
}

// Save creates the Workflow entities in the database.
func (wcb *WorkflowCreateBulk) Save(ctx context.Context) ([]*Workflow, error) {
	if wcb.err != nil {
		return nil, wcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wcb.builders))
	nodes := make([]*Workflow, len(wcb.builders))
	mutators := make([]Mutator, len(wcb.builders))
	for i := range wcb.builders {
		func(i int, root context.Context) {
			builder := wcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkflowMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = wcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wcb *WorkflowCreateBulk) SaveX(ctx context.Context) []*Workflow {
	v, err := wcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wcb *WorkflowCreateBulk) Exec(ctx context.Context) error {
	_, err := wcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcb *WorkflowCreateBulk) ExecX(ctx context.Context) {
	if err := wcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Workflow.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkflowUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (wcb *WorkflowCreateBulk) OnConflict(opts ...sql.ConflictOption) *WorkflowUpsertBulk {
	wcb.conflict = opts
	return &WorkflowUpsertBulk{
		create: wcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Workflow.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (wcb *WorkflowCreateBulk) OnConflictColumns(columns ...string) *WorkflowUpsertBulk {
	wcb.conflict = append(wcb.conflict, sql.ConflictColumns(columns...))
	return &WorkflowUpsertBulk{
		create: wcb,
	}
}

// WorkflowUpsertBulk is the builder for "upsert"-ing
// a bulk of Workflow nodes.
type WorkflowUpsertBulk struct {
	create *WorkflowCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Workflow.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WorkflowUpsertBulk) UpdateNewValues() *WorkflowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(workflow.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Workflow.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WorkflowUpsertBulk) Ignore() *WorkflowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkflowUpsertBulk) DoNothing() *WorkflowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkflowCreateBulk.OnConflict
// documentation for more info.
func (u *WorkflowUpsertBulk) Update(set func(*WorkflowUpsert)) *WorkflowUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkflowUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *WorkflowUpsertBulk) SetUpdatedAt(v time.Time) *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *WorkflowUpsertBulk) UpdateUpdatedAt() *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *WorkflowUpsertBulk) ClearUpdatedAt() *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetNanoid sets the "nanoid" field.
func (u *WorkflowUpsertBulk) SetNanoid(v string) *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.SetNanoid(v)
	})
}

// UpdateNanoid sets the "nanoid" field to the value that was provided on create.
func (u *WorkflowUpsertBulk) UpdateNanoid() *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.UpdateNanoid()
	})
}

// ClearNanoid clears the value of the "nanoid" field.
func (u *WorkflowUpsertBulk) ClearNanoid() *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.ClearNanoid()
	})
}

// SetName sets the "name" field.
func (u *WorkflowUpsertBulk) SetName(v string) *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *WorkflowUpsertBulk) UpdateName() *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.UpdateName()
	})
}

// SetVariables sets the "variables" field.
func (u *WorkflowUpsertBulk) SetVariables(v []schema.WorkflowVariable) *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.SetVariables(v)
	})
}

// UpdateVariables sets the "variables" field to the value that was provided on create.
func (u *WorkflowUpsertBulk) UpdateVariables() *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.UpdateVariables()
	})
}

// SetSteps sets the "steps" field.
func (u *WorkflowUpsertBulk) SetSteps(v []schema.WorkflowStep) *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.SetSteps(v)
	})
}

// UpdateSteps sets the "steps" field to the value that was provided on create.
func (u *WorkflowUpsertBulk) UpdateSteps() *WorkflowUpsertBulk {
	return u.Update(func(s *WorkflowUpsert) {
		s.UpdateSteps()
	})
}

// Exec executes the query.
func (u *WorkflowUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WorkflowCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WorkflowCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkflowUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
