// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Yiling-J/tablepilot/ent/predicate"
	"github.com/Yiling-J/tablepilot/ent/schema"
	"github.com/Yiling-J/tablepilot/ent/workflow"
)

// WorkflowUpdate is the builder for updating Workflow entities.
type WorkflowUpdate struct {
	config
	hooks     []Hook
	mutation  *WorkflowMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the WorkflowUpdate builder.
func (wu *WorkflowUpdate) Where(ps ...predicate.Workflow) *WorkflowUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetUpdatedAt sets the "updated_at" field.
func (wu *WorkflowUpdate) SetUpdatedAt(t time.Time) *WorkflowUpdate {
	wu.mutation.SetUpdatedAt(t)
	return wu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (wu *WorkflowUpdate) ClearUpdatedAt() *WorkflowUpdate {
	wu.mutation.ClearUpdatedAt()
	return wu
}

// SetNanoid sets the "nanoid" field.
func (wu *WorkflowUpdate) SetNanoid(s string) *WorkflowUpdate {
	wu.mutation.SetNanoid(s)
	return wu
}

// SetNillableNanoid sets the "nanoid" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableNanoid(s *string) *WorkflowUpdate {
	if s != nil {
		wu.SetNanoid(*s)
	}
	return wu
}

// ClearNanoid clears the value of the "nanoid" field.
func (wu *WorkflowUpdate) ClearNanoid() *WorkflowUpdate {
	wu.mutation.ClearNanoid()
	return wu
}

// SetName sets the "name" field.
func (wu *WorkflowUpdate) SetName(s string) *WorkflowUpdate {
	wu.mutation.SetName(s)
	return wu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableName(s *string) *WorkflowUpdate {
	if s != nil {
		wu.SetName(*s)
	}
	return wu
}

// SetDescription sets the "description" field.
func (wu *WorkflowUpdate) SetDescription(s string) *WorkflowUpdate {
	wu.mutation.SetDescription(s)
	return wu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableDescription(s *string) *WorkflowUpdate {
	if s != nil {
		wu.SetDescription(*s)
	}
	return wu
}

// ClearDescription clears the value of the "description" field.
func (wu *WorkflowUpdate) ClearDescription() *WorkflowUpdate {
	wu.mutation.ClearDescription()
	return wu
}

// SetVariables sets the "variables" field.
func (wu *WorkflowUpdate) SetVariables(sv []schema.WorkflowVariable) *WorkflowUpdate {
	wu.mutation.SetVariables(sv)
	return wu
}

// AppendVariables appends sv to the "variables" field.
func (wu *WorkflowUpdate) AppendVariables(sv []schema.WorkflowVariable) *WorkflowUpdate {
	wu.mutation.AppendVariables(sv)
	return wu
}

// SetSteps sets the "steps" field.
func (wu *WorkflowUpdate) SetSteps(ss []schema.WorkflowStep) *WorkflowUpdate {
	wu.mutation.SetSteps(ss)
	return wu
}

// AppendSteps appends ss to the "steps" field.
func (wu *WorkflowUpdate) AppendSteps(ss []schema.WorkflowStep) *WorkflowUpdate {
	wu.mutation.AppendSteps(ss)
	return wu
}

// Mutation returns the WorkflowMutation object of the builder.
func (wu *WorkflowUpdate) Mutation() *WorkflowMutation {
	return wu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WorkflowUpdate) Save(ctx context.Context) (int, error) {
	wu.defaults()
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WorkflowUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WorkflowUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WorkflowUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wu *WorkflowUpdate) defaults() {
	if _, ok := wu.mutation.UpdatedAt(); !ok && !wu.mutation.UpdatedAtCleared() {
		v := workflow.UpdateDefaultUpdatedAt()
		wu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *WorkflowUpdate) check() error {
	if v, ok := wu.mutation.Name(); ok {
		if err := workflow.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workflow.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (wu *WorkflowUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WorkflowUpdate {
	wu.modifiers = append(wu.modifiers, modifiers...)
	return wu
}

func (wu *WorkflowUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflow.Table, workflow.Columns, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeInt))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if wu.mutation.CreatedAtCleared() {
		_spec.ClearField(workflow.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := wu.mutation.UpdatedAt(); ok {
		_spec.SetField(workflow.FieldUpdatedAt, field.TypeTime, value)
	}
	if wu.mutation.UpdatedAtCleared() {
		_spec.ClearField(workflow.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := wu.mutation.Nanoid(); ok {
		_spec.SetField(workflow.FieldNanoid, field.TypeString, value)
	}
	if wu.mutation.NanoidCleared() {
		_spec.ClearField(workflow.FieldNanoid, field.TypeString)
	}
	if value, ok := wu.mutation.Name(); ok {
		_spec.SetField(workflow.FieldName, field.TypeString, value)
	}
	if value, ok := wu.mutation.Description(); ok {
		_spec.SetField(workflow.FieldDescription, field.TypeString, value)
	}
	if wu.mutation.DescriptionCleared() {
		_spec.ClearField(workflow.FieldDescription, field.TypeString)
	}
	if value, ok := wu.mutation.Variables(); ok {
		_spec.SetField(workflow.FieldVariables, field.TypeJSON, value)
	}
	if value, ok := wu.mutation.AppendedVariables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workflow.FieldVariables, value)
		})
	}
	if value, ok := wu.mutation.Steps(); ok {
		_spec.SetField(workflow.FieldSteps, field.TypeJSON, value)
	}
	if value, ok := wu.mutation.AppendedSteps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workflow.FieldSteps, value)
		})
	}
	_spec.AddModifiers(wu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WorkflowUpdateOne is the builder for updating a single Workflow entity.
type WorkflowUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *WorkflowMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (wuo *WorkflowUpdateOne) SetUpdatedAt(t time.Time) *WorkflowUpdateOne {
	wuo.mutation.SetUpdatedAt(t)
	return wuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (wuo *WorkflowUpdateOne) ClearUpdatedAt() *WorkflowUpdateOne {
	wuo.mutation.ClearUpdatedAt()
	return wuo
}

// SetNanoid sets the "nanoid" field.
func (wuo *WorkflowUpdateOne) SetNanoid(s string) *WorkflowUpdateOne {
	wuo.mutation.SetNanoid(s)
	return wuo
}

// SetNillableNanoid sets the "nanoid" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableNanoid(s *string) *WorkflowUpdateOne {
	if s != nil {
		wuo.SetNanoid(*s)
	}
	return wuo
}

// ClearNanoid clears the value of the "nanoid" field.
func (wuo *WorkflowUpdateOne) ClearNanoid() *WorkflowUpdateOne {
	wuo.mutation.ClearNanoid()
	return wuo
}

// SetName sets the "name" field.
func (wuo *WorkflowUpdateOne) SetName(s string) *WorkflowUpdateOne {
	wuo.mutation.SetName(s)
	return wuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableName(s *string) *WorkflowUpdateOne {
	if s != nil {
		wuo.SetName(*s)
	}
	return wuo
}

// SetDescription sets the "description" field.
func (wuo *WorkflowUpdateOne) SetDescription(s string) *WorkflowUpdateOne {
	wuo.mutation.SetDescription(s)
	return wuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableDescription(s *string) *WorkflowUpdateOne {
	if s != nil {
		wuo.SetDescription(*s)
	}
	return wuo
}

// ClearDescription clears the value of the "description" field.
func (wuo *WorkflowUpdateOne) ClearDescription() *WorkflowUpdateOne {
	wuo.mutation.ClearDescription()
	return wuo
}

// SetVariables sets the "variables" field.
func (wuo *WorkflowUpdateOne) SetVariables(sv []schema.WorkflowVariable) *WorkflowUpdateOne {
	wuo.mutation.SetVariables(sv)
	return wuo
}

// AppendVariables appends sv to the "variables" field.
func (wuo *WorkflowUpdateOne) AppendVariables(sv []schema.WorkflowVariable) *WorkflowUpdateOne {
	wuo.mutation.AppendVariables(sv)
	return wuo
}

// SetSteps sets the "steps" field.
func (wuo *WorkflowUpdateOne) SetSteps(ss []schema.WorkflowStep) *WorkflowUpdateOne {
	wuo.mutation.SetSteps(ss)
	return wuo
}

// AppendSteps appends ss to the "steps" field.
func (wuo *WorkflowUpdateOne) AppendSteps(ss []schema.WorkflowStep) *WorkflowUpdateOne {
	wuo.mutation.AppendSteps(ss)
	return wuo
}

// Mutation returns the WorkflowMutation object of the builder.
func (wuo *WorkflowUpdateOne) Mutation() *WorkflowMutation {
	return wuo.mutation
}

// Where appends a list predicates to the WorkflowUpdate builder.
func (wuo *WorkflowUpdateOne) Where(ps ...predicate.Workflow) *WorkflowUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WorkflowUpdateOne) Select(field string, fields ...string) *WorkflowUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Workflow entity.
func (wuo *WorkflowUpdateOne) Save(ctx context.Context) (*Workflow, error) {
	wuo.defaults()
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WorkflowUpdateOne) SaveX(ctx context.Context) *Workflow {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WorkflowUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WorkflowUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wuo *WorkflowUpdateOne) defaults() {
	if _, ok := wuo.mutation.UpdatedAt(); !ok && !wuo.mutation.UpdatedAtCleared() {
		v := workflow.UpdateDefaultUpdatedAt()
		wuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WorkflowUpdateOne) check() error {
	if v, ok := wuo.mutation.Name(); ok {
		if err := workflow.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workflow.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (wuo *WorkflowUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WorkflowUpdateOne {
	wuo.modifiers = append(wuo.modifiers, modifiers...)
	return wuo
}

func (wuo *WorkflowUpdateOne) sqlSave(ctx context.Context) (_node *Workflow, err error) {
	if err := wuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflow.Table, workflow.Columns, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeInt))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workflow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflow.FieldID)
		for _, f := range fields {
			if !workflow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if wuo.mutation.CreatedAtCleared() {
		_spec.ClearField(workflow.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := wuo.mutation.UpdatedAt(); ok {
		_spec.SetField(workflow.FieldUpdatedAt, field.TypeTime, value)
	}
	if wuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(workflow.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := wuo.mutation.Nanoid(); ok {
		_spec.SetField(workflow.FieldNanoid, field.TypeString, value)
	}
	if wuo.mutation.NanoidCleared() {
		_spec.ClearField(workflow.FieldNanoid, field.TypeString)
	}
	if value, ok := wuo.mutation.Name(); ok {
		_spec.SetField(workflow.FieldName, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Description(); ok {
		_spec.SetField(workflow.FieldDescription, field.TypeString, value)
	}
	if wuo.mutation.DescriptionCleared() {
		_spec.ClearField(workflow.FieldDescription, field.TypeString)
	}
	if value, ok := wuo.mutation.Variables(); ok {
		_spec.SetField(workflow.FieldVariables, field.TypeJSON, value)
	}
	if value, ok := wuo.mutation.AppendedVariables(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workflow.FieldVariables, value)
		})
	}
	if value, ok := wuo.mutation.Steps(); ok {
		_spec.SetField(workflow.FieldSteps, field.TypeJSON, value)
	}
	if value, ok := wuo.mutation.AppendedSteps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workflow.FieldSteps, value)
		})
	}
	_spec.AddModifiers(wuo.modifiers...)
	_node = &Workflow{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
