// Code generated by ent, DO NOT EDIT.

package tablemeta

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tablemeta type in the database.
	Label = "table_meta"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldNanoid holds the string denoting the nanoid field in the database.
	FieldNanoid = "nanoid"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// EdgeColumns holds the string denoting the columns edge name in mutations.
	EdgeColumns = "columns"
	// EdgeRows holds the string denoting the rows edge name in mutations.
	EdgeRows = "rows"
	// EdgeDatasets holds the string denoting the datasets edge name in mutations.
	EdgeDatasets = "datasets"
	// Table holds the table name of the tablemeta in the database.
	Table = "table_meta"
	// ColumnsTable is the table that holds the columns relation/edge.
	ColumnsTable = "table_columns"
	// ColumnsInverseTable is the table name for the TableColumn entity.
	// It exists in this package in order to avoid circular dependency with the "tablecolumn" package.
	ColumnsInverseTable = "table_columns"
	// ColumnsColumn is the table column denoting the columns relation/edge.
	ColumnsColumn = "table_id"
	// RowsTable is the table that holds the rows relation/edge.
	RowsTable = "table_rows"
	// RowsInverseTable is the table name for the TableRow entity.
	// It exists in this package in order to avoid circular dependency with the "tablerow" package.
	RowsInverseTable = "table_rows"
	// RowsColumn is the table column denoting the rows relation/edge.
	RowsColumn = "table_meta_rows"
	// DatasetsTable is the table that holds the datasets relation/edge.
	DatasetsTable = "datasets"
	// DatasetsInverseTable is the table name for the Dataset entity.
	// It exists in this package in order to avoid circular dependency with the "dataset" package.
	DatasetsInverseTable = "datasets"
	// DatasetsColumn is the table column denoting the datasets relation/edge.
	DatasetsColumn = "table_meta_datasets"
)

// Columns holds all SQL columns for tablemeta fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldNanoid,
	FieldName,
	FieldDescription,
	FieldModel,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
)

// OrderOption defines the ordering options for the TableMeta queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNanoid orders the results by the nanoid field.
func ByNanoid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNanoid, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByColumnsCount orders the results by columns count.
func ByColumnsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newColumnsStep(), opts...)
	}
}

// ByColumns orders the results by columns terms.
func ByColumns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newColumnsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRowsCount orders the results by rows count.
func ByRowsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRowsStep(), opts...)
	}
}

// ByRows orders the results by rows terms.
func ByRows(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRowsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDatasetsCount orders the results by datasets count.
func ByDatasetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDatasetsStep(), opts...)
	}
}

// ByDatasets orders the results by datasets terms.
func ByDatasets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDatasetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newColumnsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ColumnsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ColumnsTable, ColumnsColumn),
	)
}
func newRowsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RowsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RowsTable, RowsColumn),
	)
}
func newDatasetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DatasetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DatasetsTable, DatasetsColumn),
	)
}
