// Code generated by ent, DO NOT EDIT.

package tablemeta

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tablemeta type in the database.
	Label = "table_meta"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldNanoid holds the string denoting the nanoid field in the database.
	FieldNanoid = "nanoid"
	// FieldMaxRows holds the string denoting the max_rows field in the database.
	FieldMaxRows = "max_rows"
	// FieldPromptRaw holds the string denoting the prompt_raw field in the database.
	FieldPromptRaw = "prompt_raw"
	// FieldPromptGen holds the string denoting the prompt_gen field in the database.
	FieldPromptGen = "prompt_gen"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldBuildStatus holds the string denoting the build_status field in the database.
	FieldBuildStatus = "build_status"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// EdgeColumns holds the string denoting the columns edge name in mutations.
	EdgeColumns = "columns"
	// EdgeRows holds the string denoting the rows edge name in mutations.
	EdgeRows = "rows"
	// Table holds the table name of the tablemeta in the database.
	Table = "table_meta"
	// ColumnsTable is the table that holds the columns relation/edge.
	ColumnsTable = "table_columns"
	// ColumnsInverseTable is the table name for the TableColumn entity.
	// It exists in this package in order to avoid circular dependency with the "tablecolumn" package.
	ColumnsInverseTable = "table_columns"
	// ColumnsColumn is the table column denoting the columns relation/edge.
	ColumnsColumn = "table_id"
	// RowsTable is the table that holds the rows relation/edge.
	RowsTable = "table_rows"
	// RowsInverseTable is the table name for the TableRow entity.
	// It exists in this package in order to avoid circular dependency with the "tablerow" package.
	RowsInverseTable = "table_rows"
	// RowsColumn is the table column denoting the rows relation/edge.
	RowsColumn = "table_meta_rows"
)

// Columns holds all SQL columns for tablemeta fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldNanoid,
	FieldMaxRows,
	FieldPromptRaw,
	FieldPromptGen,
	FieldName,
	FieldDescription,
	FieldBuildStatus,
	FieldModel,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultMaxRows holds the default value on creation for the "max_rows" field.
	DefaultMaxRows int
	// DefaultPromptRaw holds the default value on creation for the "prompt_raw" field.
	DefaultPromptRaw string
	// DefaultPromptGen holds the default value on creation for the "prompt_gen" field.
	DefaultPromptGen string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
)

// BuildStatus defines the type for the "build_status" enum field.
type BuildStatus string

// BuildStatusInit is the default value of the BuildStatus enum.
const DefaultBuildStatus = BuildStatusInit

// BuildStatus values.
const (
	BuildStatusInit    BuildStatus = "init"
	BuildStatusSuccess BuildStatus = "success"
	BuildStatusFailed  BuildStatus = "failed"
)

func (bs BuildStatus) String() string {
	return string(bs)
}

// BuildStatusValidator is a validator for the "build_status" field enum values. It is called by the builders before save.
func BuildStatusValidator(bs BuildStatus) error {
	switch bs {
	case BuildStatusInit, BuildStatusSuccess, BuildStatusFailed:
		return nil
	default:
		return fmt.Errorf("tablemeta: invalid enum value for build_status field: %q", bs)
	}
}

// OrderOption defines the ordering options for the TableMeta queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByNanoid orders the results by the nanoid field.
func ByNanoid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNanoid, opts...).ToFunc()
}

// ByMaxRows orders the results by the max_rows field.
func ByMaxRows(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxRows, opts...).ToFunc()
}

// ByPromptRaw orders the results by the prompt_raw field.
func ByPromptRaw(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptRaw, opts...).ToFunc()
}

// ByPromptGen orders the results by the prompt_gen field.
func ByPromptGen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptGen, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByBuildStatus orders the results by the build_status field.
func ByBuildStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuildStatus, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByColumnsCount orders the results by columns count.
func ByColumnsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newColumnsStep(), opts...)
	}
}

// ByColumns orders the results by columns terms.
func ByColumns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newColumnsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRowsCount orders the results by rows count.
func ByRowsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRowsStep(), opts...)
	}
}

// ByRows orders the results by rows terms.
func ByRows(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRowsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newColumnsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ColumnsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ColumnsTable, ColumnsColumn),
	)
}
func newRowsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RowsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RowsTable, RowsColumn),
	)
}
