// Code generated by ent, DO NOT EDIT.

package tablemeta

import (
	"tablepilot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldUpdatedAt, v))
}

// Nanoid applies equality check predicate on the "nanoid" field. It's identical to NanoidEQ.
func Nanoid(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldNanoid, v))
}

// MaxRows applies equality check predicate on the "max_rows" field. It's identical to MaxRowsEQ.
func MaxRows(v int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldMaxRows, v))
}

// PromptRaw applies equality check predicate on the "prompt_raw" field. It's identical to PromptRawEQ.
func PromptRaw(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldPromptRaw, v))
}

// PromptGen applies equality check predicate on the "prompt_gen" field. It's identical to PromptGenEQ.
func PromptGen(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldPromptGen, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldDescription, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldModel, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotNull(FieldUpdatedAt))
}

// NanoidEQ applies the EQ predicate on the "nanoid" field.
func NanoidEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldNanoid, v))
}

// NanoidNEQ applies the NEQ predicate on the "nanoid" field.
func NanoidNEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNEQ(FieldNanoid, v))
}

// NanoidIn applies the In predicate on the "nanoid" field.
func NanoidIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIn(FieldNanoid, vs...))
}

// NanoidNotIn applies the NotIn predicate on the "nanoid" field.
func NanoidNotIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotIn(FieldNanoid, vs...))
}

// NanoidGT applies the GT predicate on the "nanoid" field.
func NanoidGT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGT(FieldNanoid, v))
}

// NanoidGTE applies the GTE predicate on the "nanoid" field.
func NanoidGTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGTE(FieldNanoid, v))
}

// NanoidLT applies the LT predicate on the "nanoid" field.
func NanoidLT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLT(FieldNanoid, v))
}

// NanoidLTE applies the LTE predicate on the "nanoid" field.
func NanoidLTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLTE(FieldNanoid, v))
}

// NanoidContains applies the Contains predicate on the "nanoid" field.
func NanoidContains(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContains(FieldNanoid, v))
}

// NanoidHasPrefix applies the HasPrefix predicate on the "nanoid" field.
func NanoidHasPrefix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasPrefix(FieldNanoid, v))
}

// NanoidHasSuffix applies the HasSuffix predicate on the "nanoid" field.
func NanoidHasSuffix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasSuffix(FieldNanoid, v))
}

// NanoidIsNil applies the IsNil predicate on the "nanoid" field.
func NanoidIsNil() predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIsNull(FieldNanoid))
}

// NanoidNotNil applies the NotNil predicate on the "nanoid" field.
func NanoidNotNil() predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotNull(FieldNanoid))
}

// NanoidEqualFold applies the EqualFold predicate on the "nanoid" field.
func NanoidEqualFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEqualFold(FieldNanoid, v))
}

// NanoidContainsFold applies the ContainsFold predicate on the "nanoid" field.
func NanoidContainsFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContainsFold(FieldNanoid, v))
}

// MaxRowsEQ applies the EQ predicate on the "max_rows" field.
func MaxRowsEQ(v int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldMaxRows, v))
}

// MaxRowsNEQ applies the NEQ predicate on the "max_rows" field.
func MaxRowsNEQ(v int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNEQ(FieldMaxRows, v))
}

// MaxRowsIn applies the In predicate on the "max_rows" field.
func MaxRowsIn(vs ...int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIn(FieldMaxRows, vs...))
}

// MaxRowsNotIn applies the NotIn predicate on the "max_rows" field.
func MaxRowsNotIn(vs ...int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotIn(FieldMaxRows, vs...))
}

// MaxRowsGT applies the GT predicate on the "max_rows" field.
func MaxRowsGT(v int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGT(FieldMaxRows, v))
}

// MaxRowsGTE applies the GTE predicate on the "max_rows" field.
func MaxRowsGTE(v int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGTE(FieldMaxRows, v))
}

// MaxRowsLT applies the LT predicate on the "max_rows" field.
func MaxRowsLT(v int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLT(FieldMaxRows, v))
}

// MaxRowsLTE applies the LTE predicate on the "max_rows" field.
func MaxRowsLTE(v int) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLTE(FieldMaxRows, v))
}

// PromptRawEQ applies the EQ predicate on the "prompt_raw" field.
func PromptRawEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldPromptRaw, v))
}

// PromptRawNEQ applies the NEQ predicate on the "prompt_raw" field.
func PromptRawNEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNEQ(FieldPromptRaw, v))
}

// PromptRawIn applies the In predicate on the "prompt_raw" field.
func PromptRawIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIn(FieldPromptRaw, vs...))
}

// PromptRawNotIn applies the NotIn predicate on the "prompt_raw" field.
func PromptRawNotIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotIn(FieldPromptRaw, vs...))
}

// PromptRawGT applies the GT predicate on the "prompt_raw" field.
func PromptRawGT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGT(FieldPromptRaw, v))
}

// PromptRawGTE applies the GTE predicate on the "prompt_raw" field.
func PromptRawGTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGTE(FieldPromptRaw, v))
}

// PromptRawLT applies the LT predicate on the "prompt_raw" field.
func PromptRawLT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLT(FieldPromptRaw, v))
}

// PromptRawLTE applies the LTE predicate on the "prompt_raw" field.
func PromptRawLTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLTE(FieldPromptRaw, v))
}

// PromptRawContains applies the Contains predicate on the "prompt_raw" field.
func PromptRawContains(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContains(FieldPromptRaw, v))
}

// PromptRawHasPrefix applies the HasPrefix predicate on the "prompt_raw" field.
func PromptRawHasPrefix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasPrefix(FieldPromptRaw, v))
}

// PromptRawHasSuffix applies the HasSuffix predicate on the "prompt_raw" field.
func PromptRawHasSuffix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasSuffix(FieldPromptRaw, v))
}

// PromptRawEqualFold applies the EqualFold predicate on the "prompt_raw" field.
func PromptRawEqualFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEqualFold(FieldPromptRaw, v))
}

// PromptRawContainsFold applies the ContainsFold predicate on the "prompt_raw" field.
func PromptRawContainsFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContainsFold(FieldPromptRaw, v))
}

// PromptGenEQ applies the EQ predicate on the "prompt_gen" field.
func PromptGenEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldPromptGen, v))
}

// PromptGenNEQ applies the NEQ predicate on the "prompt_gen" field.
func PromptGenNEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNEQ(FieldPromptGen, v))
}

// PromptGenIn applies the In predicate on the "prompt_gen" field.
func PromptGenIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIn(FieldPromptGen, vs...))
}

// PromptGenNotIn applies the NotIn predicate on the "prompt_gen" field.
func PromptGenNotIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotIn(FieldPromptGen, vs...))
}

// PromptGenGT applies the GT predicate on the "prompt_gen" field.
func PromptGenGT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGT(FieldPromptGen, v))
}

// PromptGenGTE applies the GTE predicate on the "prompt_gen" field.
func PromptGenGTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGTE(FieldPromptGen, v))
}

// PromptGenLT applies the LT predicate on the "prompt_gen" field.
func PromptGenLT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLT(FieldPromptGen, v))
}

// PromptGenLTE applies the LTE predicate on the "prompt_gen" field.
func PromptGenLTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLTE(FieldPromptGen, v))
}

// PromptGenContains applies the Contains predicate on the "prompt_gen" field.
func PromptGenContains(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContains(FieldPromptGen, v))
}

// PromptGenHasPrefix applies the HasPrefix predicate on the "prompt_gen" field.
func PromptGenHasPrefix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasPrefix(FieldPromptGen, v))
}

// PromptGenHasSuffix applies the HasSuffix predicate on the "prompt_gen" field.
func PromptGenHasSuffix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasSuffix(FieldPromptGen, v))
}

// PromptGenEqualFold applies the EqualFold predicate on the "prompt_gen" field.
func PromptGenEqualFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEqualFold(FieldPromptGen, v))
}

// PromptGenContainsFold applies the ContainsFold predicate on the "prompt_gen" field.
func PromptGenContainsFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContainsFold(FieldPromptGen, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContainsFold(FieldDescription, v))
}

// BuildStatusEQ applies the EQ predicate on the "build_status" field.
func BuildStatusEQ(v BuildStatus) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldBuildStatus, v))
}

// BuildStatusNEQ applies the NEQ predicate on the "build_status" field.
func BuildStatusNEQ(v BuildStatus) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNEQ(FieldBuildStatus, v))
}

// BuildStatusIn applies the In predicate on the "build_status" field.
func BuildStatusIn(vs ...BuildStatus) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIn(FieldBuildStatus, vs...))
}

// BuildStatusNotIn applies the NotIn predicate on the "build_status" field.
func BuildStatusNotIn(vs ...BuildStatus) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotIn(FieldBuildStatus, vs...))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.TableMeta {
	return predicate.TableMeta(sql.FieldContainsFold(FieldModel, v))
}

// HasColumns applies the HasEdge predicate on the "columns" edge.
func HasColumns() predicate.TableMeta {
	return predicate.TableMeta(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ColumnsTable, ColumnsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasColumnsWith applies the HasEdge predicate on the "columns" edge with a given conditions (other predicates).
func HasColumnsWith(preds ...predicate.TableColumn) predicate.TableMeta {
	return predicate.TableMeta(func(s *sql.Selector) {
		step := newColumnsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRows applies the HasEdge predicate on the "rows" edge.
func HasRows() predicate.TableMeta {
	return predicate.TableMeta(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RowsTable, RowsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRowsWith applies the HasEdge predicate on the "rows" edge with a given conditions (other predicates).
func HasRowsWith(preds ...predicate.TableRow) predicate.TableMeta {
	return predicate.TableMeta(func(s *sql.Selector) {
		step := newRowsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TableMeta) predicate.TableMeta {
	return predicate.TableMeta(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TableMeta) predicate.TableMeta {
	return predicate.TableMeta(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TableMeta) predicate.TableMeta {
	return predicate.TableMeta(sql.NotPredicates(p))
}
