// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tableprinter

import (
	"sync"
)

// Ensure, that TablePrinterMock does implement TablePrinter.
// If this is not the case, regenerate this file with moq.
var _ TablePrinter = &TablePrinterMock{}

// TablePrinterMock is a mock implementation of TablePrinter.
//
//	func TestSomethingThatUsesTablePrinter(t *testing.T) {
//
//		// make and configure a mocked TablePrinter
//		mockedTablePrinter := &TablePrinterMock{
//			AddFieldFunc: func(s string, fieldOptions ...FieldOption)  {
//				panic("mock out the AddField method")
//			},
//			AddHeaderFunc: func(strings []string, fieldOptions ...FieldOption)  {
//				panic("mock out the AddHeader method")
//			},
//			EndRowFunc: func()  {
//				panic("mock out the EndRow method")
//			},
//			RenderFunc: func() error {
//				panic("mock out the Render method")
//			},
//		}
//
//		// use mockedTablePrinter in code that requires TablePrinter
//		// and then make assertions.
//
//	}
type TablePrinterMock struct {
	// AddFieldFunc mocks the AddField method.
	AddFieldFunc func(s string, fieldOptions ...FieldOption)

	// AddHeaderFunc mocks the AddHeader method.
	AddHeaderFunc func(strings []string, fieldOptions ...FieldOption)

	// EndRowFunc mocks the EndRow method.
	EndRowFunc func()

	// RenderFunc mocks the Render method.
	RenderFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// AddField holds details about calls to the AddField method.
		AddField []struct {
			// S is the s argument value.
			S string
			// FieldOptions is the fieldOptions argument value.
			FieldOptions []FieldOption
		}
		// AddHeader holds details about calls to the AddHeader method.
		AddHeader []struct {
			// Strings is the strings argument value.
			Strings []string
			// FieldOptions is the fieldOptions argument value.
			FieldOptions []FieldOption
		}
		// EndRow holds details about calls to the EndRow method.
		EndRow []struct {
		}
		// Render holds details about calls to the Render method.
		Render []struct {
		}
	}
	lockAddField  sync.RWMutex
	lockAddHeader sync.RWMutex
	lockEndRow    sync.RWMutex
	lockRender    sync.RWMutex
}

// AddField calls AddFieldFunc.
func (mock *TablePrinterMock) AddField(s string, fieldOptions ...FieldOption) {
	if mock.AddFieldFunc == nil {
		panic("TablePrinterMock.AddFieldFunc: method is nil but TablePrinter.AddField was just called")
	}
	callInfo := struct {
		S            string
		FieldOptions []FieldOption
	}{
		S:            s,
		FieldOptions: fieldOptions,
	}
	mock.lockAddField.Lock()
	mock.calls.AddField = append(mock.calls.AddField, callInfo)
	mock.lockAddField.Unlock()
	mock.AddFieldFunc(s, fieldOptions...)
}

// AddFieldCalls gets all the calls that were made to AddField.
// Check the length with:
//
//	len(mockedTablePrinter.AddFieldCalls())
func (mock *TablePrinterMock) AddFieldCalls() []struct {
	S            string
	FieldOptions []FieldOption
} {
	var calls []struct {
		S            string
		FieldOptions []FieldOption
	}
	mock.lockAddField.RLock()
	calls = mock.calls.AddField
	mock.lockAddField.RUnlock()
	return calls
}

// AddHeader calls AddHeaderFunc.
func (mock *TablePrinterMock) AddHeader(strings []string, fieldOptions ...FieldOption) {
	if mock.AddHeaderFunc == nil {
		panic("TablePrinterMock.AddHeaderFunc: method is nil but TablePrinter.AddHeader was just called")
	}
	callInfo := struct {
		Strings      []string
		FieldOptions []FieldOption
	}{
		Strings:      strings,
		FieldOptions: fieldOptions,
	}
	mock.lockAddHeader.Lock()
	mock.calls.AddHeader = append(mock.calls.AddHeader, callInfo)
	mock.lockAddHeader.Unlock()
	mock.AddHeaderFunc(strings, fieldOptions...)
}

// AddHeaderCalls gets all the calls that were made to AddHeader.
// Check the length with:
//
//	len(mockedTablePrinter.AddHeaderCalls())
func (mock *TablePrinterMock) AddHeaderCalls() []struct {
	Strings      []string
	FieldOptions []FieldOption
} {
	var calls []struct {
		Strings      []string
		FieldOptions []FieldOption
	}
	mock.lockAddHeader.RLock()
	calls = mock.calls.AddHeader
	mock.lockAddHeader.RUnlock()
	return calls
}

// EndRow calls EndRowFunc.
func (mock *TablePrinterMock) EndRow() {
	if mock.EndRowFunc == nil {
		panic("TablePrinterMock.EndRowFunc: method is nil but TablePrinter.EndRow was just called")
	}
	callInfo := struct {
	}{}
	mock.lockEndRow.Lock()
	mock.calls.EndRow = append(mock.calls.EndRow, callInfo)
	mock.lockEndRow.Unlock()
	mock.EndRowFunc()
}

// EndRowCalls gets all the calls that were made to EndRow.
// Check the length with:
//
//	len(mockedTablePrinter.EndRowCalls())
func (mock *TablePrinterMock) EndRowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockEndRow.RLock()
	calls = mock.calls.EndRow
	mock.lockEndRow.RUnlock()
	return calls
}

// Render calls RenderFunc.
func (mock *TablePrinterMock) Render() error {
	if mock.RenderFunc == nil {
		panic("TablePrinterMock.RenderFunc: method is nil but TablePrinter.Render was just called")
	}
	callInfo := struct {
	}{}
	mock.lockRender.Lock()
	mock.calls.Render = append(mock.calls.Render, callInfo)
	mock.lockRender.Unlock()
	return mock.RenderFunc()
}

// RenderCalls gets all the calls that were made to Render.
// Check the length with:
//
//	len(mockedTablePrinter.RenderCalls())
func (mock *TablePrinterMock) RenderCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRender.RLock()
	calls = mock.calls.Render
	mock.lockRender.RUnlock()
	return calls
}
