// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package workflow

import (
	"context"
	"github.com/Yiling-J/tablepilot/ent"
	"sync"
)

// Ensure, that WorkflowServiceMock does implement WorkflowService.
// If this is not the case, regenerate this file with moq.
var _ WorkflowService = &WorkflowServiceMock{}

// WorkflowServiceMock is a mock implementation of WorkflowService.
//
//	func TestSomethingThatUsesWorkflowService(t *testing.T) {
//
//		// make and configure a mocked WorkflowService
//		mockedWorkflowService := &WorkflowServiceMock{
//			CreateFunc: func(ctx context.Context, wf *Workflow) (string, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, wf string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, wf string) (*ent.Workflow, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context) ([]*ent.Workflow, error) {
//				panic("mock out the List method")
//			},
//			StartFunc: func(ctx context.Context, workflow string, vars map[string]any, model string, temperature float64) (Runner, error) {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedWorkflowService in code that requires WorkflowService
//		// and then make assertions.
//
//	}
type WorkflowServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, wf *Workflow) (string, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, wf string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, wf string) (*ent.Workflow, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]*ent.Workflow, error)

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, workflow string, vars map[string]any, model string, temperature float64) (Runner, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Wf is the wf argument value.
			Wf *Workflow
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Wf is the wf argument value.
			Wf string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Wf is the wf argument value.
			Wf string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workflow is the workflow argument value.
			Workflow string
			// Vars is the vars argument value.
			Vars map[string]any
			// Model is the model argument value.
			Model string
			// Temperature is the temperature argument value.
			Temperature float64
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockList   sync.RWMutex
	lockStart  sync.RWMutex
}

// Create calls CreateFunc.
func (mock *WorkflowServiceMock) Create(ctx context.Context, wf *Workflow) (string, error) {
	if mock.CreateFunc == nil {
		panic("WorkflowServiceMock.CreateFunc: method is nil but WorkflowService.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Wf  *Workflow
	}{
		Ctx: ctx,
		Wf:  wf,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, wf)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedWorkflowService.CreateCalls())
func (mock *WorkflowServiceMock) CreateCalls() []struct {
	Ctx context.Context
	Wf  *Workflow
} {
	var calls []struct {
		Ctx context.Context
		Wf  *Workflow
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *WorkflowServiceMock) Delete(ctx context.Context, wf string) error {
	if mock.DeleteFunc == nil {
		panic("WorkflowServiceMock.DeleteFunc: method is nil but WorkflowService.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Wf  string
	}{
		Ctx: ctx,
		Wf:  wf,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, wf)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedWorkflowService.DeleteCalls())
func (mock *WorkflowServiceMock) DeleteCalls() []struct {
	Ctx context.Context
	Wf  string
} {
	var calls []struct {
		Ctx context.Context
		Wf  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *WorkflowServiceMock) Get(ctx context.Context, wf string) (*ent.Workflow, error) {
	if mock.GetFunc == nil {
		panic("WorkflowServiceMock.GetFunc: method is nil but WorkflowService.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Wf  string
	}{
		Ctx: ctx,
		Wf:  wf,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, wf)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedWorkflowService.GetCalls())
func (mock *WorkflowServiceMock) GetCalls() []struct {
	Ctx context.Context
	Wf  string
} {
	var calls []struct {
		Ctx context.Context
		Wf  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *WorkflowServiceMock) List(ctx context.Context) ([]*ent.Workflow, error) {
	if mock.ListFunc == nil {
		panic("WorkflowServiceMock.ListFunc: method is nil but WorkflowService.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedWorkflowService.ListCalls())
func (mock *WorkflowServiceMock) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *WorkflowServiceMock) Start(ctx context.Context, workflow string, vars map[string]any, model string, temperature float64) (Runner, error) {
	if mock.StartFunc == nil {
		panic("WorkflowServiceMock.StartFunc: method is nil but WorkflowService.Start was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Workflow    string
		Vars        map[string]any
		Model       string
		Temperature float64
	}{
		Ctx:         ctx,
		Workflow:    workflow,
		Vars:        vars,
		Model:       model,
		Temperature: temperature,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx, workflow, vars, model, temperature)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedWorkflowService.StartCalls())
func (mock *WorkflowServiceMock) StartCalls() []struct {
	Ctx         context.Context
	Workflow    string
	Vars        map[string]any
	Model       string
	Temperature float64
} {
	var calls []struct {
		Ctx         context.Context
		Workflow    string
		Vars        map[string]any
		Model       string
		Temperature float64
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Ensure, that RunnerMock does implement Runner.
// If this is not the case, regenerate this file with moq.
var _ Runner = &RunnerMock{}

// RunnerMock is a mock implementation of Runner.
//
//	func TestSomethingThatUsesRunner(t *testing.T) {
//
//		// make and configure a mocked Runner
//		mockedRunner := &RunnerMock{
//			NextFunc: func(ctx context.Context) (*WorkflowStepResult, error) {
//				panic("mock out the Next method")
//			},
//		}
//
//		// use mockedRunner in code that requires Runner
//		// and then make assertions.
//
//	}
type RunnerMock struct {
	// NextFunc mocks the Next method.
	NextFunc func(ctx context.Context) (*WorkflowStepResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Next holds details about calls to the Next method.
		Next []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockNext sync.RWMutex
}

// Next calls NextFunc.
func (mock *RunnerMock) Next(ctx context.Context) (*WorkflowStepResult, error) {
	if mock.NextFunc == nil {
		panic("RunnerMock.NextFunc: method is nil but Runner.Next was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc(ctx)
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedRunner.NextCalls())
func (mock *RunnerMock) NextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}
