package table

import (
	"context"
	"encoding/json"

	"github.com/Yiling-J/tablepilot/services/ai/client"
	"github.com/Yiling-J/tablepilot/services/ai/promptbuilder"
	"github.com/Yiling-J/tablepilot/services/table/util"
)

type BuilderTable struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Depends     []string `json:"depends"`
}

func (t *TableServiceImpl) GenerateBuilderTables(ctx context.Context, prompt string) ([]BuilderTable, error) {
	pm := promptbuilder.NewTablesBuilder(prompt)
	message, err := pm.Prompt()
	if err != nil {
		return nil, err
	}
	resp, err := t.ai.Chat(ctx, &client.ChatRequest{
		Messages:        []*client.Message{client.UserMessage(message)},
		Schema:          reflector.Reflect([]BuilderTable{}),
		Temperature:     0.8,
		MaxOutputTokens: 6000,
	})
	if err != nil {
		return nil, err
	}
	tables, err := util.TryDecodeJsonArray[BuilderTable](resp.Content)
	if err != nil && len(tables) == 0 {
		return nil, err
	}
	return tables, nil
}

func (t *TableServiceImpl) PolishBuilderTables(ctx context.Context, tables []BuilderTable, prompt string) ([]BuilderTable, error) {
	tr, err := json.Marshal(map[string]any{"data": tables})
	if err != nil {
		return nil, err
	}
	pm := promptbuilder.NewTablesPolishBuilder(string(tr), prompt)
	message, err := pm.Prompt()
	if err != nil {
		return nil, err
	}
	resp, err := t.ai.Chat(ctx, &client.ChatRequest{
		Messages:        []*client.Message{client.UserMessage(message)},
		Schema:          reflector.Reflect([]BuilderTable{}),
		Temperature:     0.8,
		MaxOutputTokens: 6000,
	})
	if err != nil {
		return nil, err
	}
	tables, err = util.TryDecodeJsonArray[BuilderTable](resp.Content)
	if err != nil && len(tables) == 0 {
		return nil, err
	}
	return tables, nil
}

func getTools(polish bool) []client.ChatTool {
	tools := []client.ChatTool{}
	tools = append(tools, []client.ChatTool{
		{
			Name:        "AddAiColumn",
			Description: "Add a new AI-generated column to the current table.",
			Parameters: []client.ChatToolParam{
				{Name: "name", Type: "string", Description: "Name of the column"},
				{Name: "description", Type: "string", Description: "Description of the column"},
				{Name: "contextLength", Type: "integer", Description: "Defines how many previous values in this column will be sent to the LLM when generating a new batch of rows. This helps provide context for the generation."},
				{
					Name:        "type",
					Type:        "string",
					Description: "Type of the column (e.g., string, number)",
					Enum: []string{
						"string", "integer", "number", "boolean", "array", "image",
					},
				},
			},
		},
		{
			Name:        "AddPickColumn",
			Description: "Add a column that picks values from a source.",
			Parameters: []client.ChatToolParam{
				{Name: "name", Type: "string", Description: "Name of the column"},
				{Name: "description", Type: "string", Description: "Description of the column"},
				{
					Name:        "type",
					Type:        "string",
					Description: "Type of the column (e.g., string, number)",
					Enum: []string{
						"string", "integer", "number", "boolean", "array", "image",
					},
				},
				{Name: "random", Type: "boolean", Description: "Whether to randomly pick values"},
				{Name: "repeat", Type: "integer", Description: "Number of times values can repeat (0 means at least once)"},
				{Name: "contextLength", Type: "integer", Description: "Defines how many previous values in this column will be sent to the LLM when generating a new batch of rows. This helps provide context for the generation."},
				{Name: "source", Type: "string", Description: "Name of the source"},
				{Name: "linkedColumn", Type: "string", Description: "Name of the display column this one depends on"},
				{Name: "linkedContextColumns", Type: "[]string", Description: "Columns used as context when sending linked data to AI."},
			},
		},
		{
			Name:        "AddListSource",
			Description: "Add a source of values from a fixed list.",
			Parameters: []client.ChatToolParam{
				{Name: "name", Type: "string", Description: "Name of the source"},
				{Name: "options", Type: "[]string", Description: "List of options"},
			},
		},
		{
			Name:        "AddAiSource",
			Description: "Add a source of values generated by AI.",
			Parameters: []client.ChatToolParam{
				{Name: "name", Type: "string", Description: "Name of the source"},
				{Name: "prompt", Type: "string", Description: "Prompt to generate the source values"},
			},
		},
		{
			Name:        "AddLinkedSource",
			Description: "Add a source of values that links to another table.",
			Parameters: []client.ChatToolParam{
				{Name: "name", Type: "string", Description: "Name of the source"},
				{Name: "table", Type: "string", Description: "Name of the linked table"},
			},
		},
		{
			Name:        "RemoveColumn",
			Description: "Remove column from table by name.",
			Parameters: []client.ChatToolParam{
				{Name: "name", Type: "string", Description: "Name of the column"},
			},
		},
		{
			Name:        "RemoveSource",
			Description: "Remove source from table by name.",
			Parameters: []client.ChatToolParam{
				{Name: "name", Type: "string", Description: "Name of the source"},
			},
		},
	}...)
	if polish {
		tools = append(tools, []client.ChatTool{
			{
				Name:        "RemoveColumn",
				Description: "Remove column from table by name.",
				Parameters: []client.ChatToolParam{
					{Name: "name", Type: "string", Description: "Name of the column"},
				},
			},
			{
				Name:        "RemoveSource",
				Description: "Remove source from table by name.",
				Parameters: []client.ChatToolParam{
					{Name: "name", Type: "string", Description: "Name of the source"},
				},
			},
		}...)
	}
	return tools
}

func (t *TableServiceImpl) BuildTable(ctx context.Context, name, description string, depends []string, exists []*TableInfo) (*TableGenRequest, error) {
	tbs := []promptbuilder.TableInfoSimple{}
	for _, tb := range exists {
		info := promptbuilder.TableInfoSimple{
			Name:        tb.Name,
			Description: tb.Description,
			Columns:     []promptbuilder.TableColumnSimple{},
		}
		for _, col := range tb.Columns {
			info.Columns = append(info.Columns, promptbuilder.TableColumnSimple{
				Name:        col.Name,
				Description: col.Description,
			})
		}
		tbs = append(tbs, info)
	}
	pm := promptbuilder.NewTableGenBuilder(name, description, depends, tbs)
	message, err := pm.Prompt()
	if err != nil {
		return nil, err
	}
	resp, err := t.ai.FunctionCall(ctx, &client.ChatRequest{
		Messages:        []*client.Message{client.UserMessage(message)},
		Temperature:     0.6,
		Tools:           getTools(false),
		MaxOutputTokens: 6000,
	})
	if err != nil {
		return nil, err
	}
	builder := &tableBuilder{
		table: &TableGenRequest{
			Name:        name,
			Description: description,
		},
	}
	for _, fc := range resp.FunctionCalls {
		err := builder.run(ctx, fc.Name, fc.Arguments)
		if err != nil {
			return nil, err
		}
	}
	err = builder.validate()
	if err != nil {
		return nil, err
	}
	return builder.table, nil
}

func (t *TableServiceImpl) PolishBuilderTable(ctx context.Context, table *TableGenRequest, prompt string) (*TableGenRequest, error) {
	cb, err := json.Marshal(table.Columns)
	if err != nil {
		return nil, err
	}
	sb, err := json.Marshal(table.Sources)
	if err != nil {
		return nil, err
	}
	pm := promptbuilder.NewTablePolishBuilder(prompt, table.Name, table.Description, string(sb), string(cb))
	message, err := pm.Prompt()
	if err != nil {
		return nil, err
	}
	resp, err := t.ai.FunctionCall(ctx, &client.ChatRequest{
		Messages:        []*client.Message{client.UserMessage(message)},
		Temperature:     0.2,
		Tools:           getTools(true),
		MaxOutputTokens: 6000,
	})
	if err != nil {
		return nil, err
	}
	builder := &tableBuilder{
		table: table,
	}
	for _, fc := range resp.FunctionCalls {
		err := builder.run(ctx, fc.Name, fc.Arguments)
		if err != nil {
			return nil, err
		}
	}
	err = builder.validate()
	if err != nil {
		return nil, err
	}
	return builder.table, nil
}
