// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package table

import (
	"context"
	"github.com/Yiling-J/tablepilot/ent"
	"github.com/Yiling-J/tablepilot/ent/schema"
	"io"
	"sync"
)

// Ensure, that TableServiceMock does implement TableService.
// If this is not the case, regenerate this file with moq.
var _ TableService = &TableServiceMock{}

// TableServiceMock is a mock implementation of TableService.
//
//	func TestSomethingThatUsesTableService(t *testing.T) {
//
//		// make and configure a mocked TableService
//		mockedTableService := &TableServiceMock{
//			CreateFunc: func(ctx context.Context, req *TableGenRequest) (string, error) {
//				panic("mock out the Create method")
//			},
//			CreateRowsFunc: func(ctx context.Context, table string, rows []map[string]any) error {
//				panic("mock out the CreateRows method")
//			},
//			DeleteFunc: func(ctx context.Context, table string) (int, error) {
//				panic("mock out the Delete method")
//			},
//			GenetateFunc: func(ctx context.Context, params GenerateRowsRequest) (RowsGenerator, error) {
//				panic("mock out the Genetate method")
//			},
//			GetTableDetailFunc: func(ctx context.Context, table string) (*TableInfo, error) {
//				panic("mock out the GetTableDetail method")
//			},
//			ImportFunc: func(ctx context.Context, table string, reader io.Reader) (string, error) {
//				panic("mock out the Import method")
//			},
//			ListTablesFunc: func(ctx context.Context) (*ListTablesResponse, error) {
//				panic("mock out the ListTables method")
//			},
//			RowsFunc: func(ctx context.Context, table string) (*Rows, error) {
//				panic("mock out the Rows method")
//			},
//			SharedSourcesFunc: func(ctx context.Context) []*SharedSource {
//				panic("mock out the SharedSources method")
//			},
//			TruncateFunc: func(ctx context.Context, table string) (int, error) {
//				panic("mock out the Truncate method")
//			},
//			UpdateFunc: func(ctx context.Context, table string, req *TableGenRequest) (string, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedTableService in code that requires TableService
//		// and then make assertions.
//
//	}
type TableServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, req *TableGenRequest) (string, error)

	// CreateRowsFunc mocks the CreateRows method.
	CreateRowsFunc func(ctx context.Context, table string, rows []map[string]any) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, table string) (int, error)

	// GenetateFunc mocks the Genetate method.
	GenetateFunc func(ctx context.Context, params GenerateRowsRequest) (RowsGenerator, error)

	// GetTableDetailFunc mocks the GetTableDetail method.
	GetTableDetailFunc func(ctx context.Context, table string) (*TableInfo, error)

	// ImportFunc mocks the Import method.
	ImportFunc func(ctx context.Context, table string, reader io.Reader) (string, error)

	// ListTablesFunc mocks the ListTables method.
	ListTablesFunc func(ctx context.Context) (*ListTablesResponse, error)

	// RowsFunc mocks the Rows method.
	RowsFunc func(ctx context.Context, table string) (*Rows, error)

	// SharedSourcesFunc mocks the SharedSources method.
	SharedSourcesFunc func(ctx context.Context) []*SharedSource

	// TruncateFunc mocks the Truncate method.
	TruncateFunc func(ctx context.Context, table string) (int, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, table string, req *TableGenRequest) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *TableGenRequest
		}
		// CreateRows holds details about calls to the CreateRows method.
		CreateRows []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Table is the table argument value.
			Table string
			// Rows is the rows argument value.
			Rows []map[string]any
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Table is the table argument value.
			Table string
		}
		// Genetate holds details about calls to the Genetate method.
		Genetate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params GenerateRowsRequest
		}
		// GetTableDetail holds details about calls to the GetTableDetail method.
		GetTableDetail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Table is the table argument value.
			Table string
		}
		// Import holds details about calls to the Import method.
		Import []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Table is the table argument value.
			Table string
			// Reader is the reader argument value.
			Reader io.Reader
		}
		// ListTables holds details about calls to the ListTables method.
		ListTables []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Rows holds details about calls to the Rows method.
		Rows []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Table is the table argument value.
			Table string
		}
		// SharedSources holds details about calls to the SharedSources method.
		SharedSources []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Truncate holds details about calls to the Truncate method.
		Truncate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Table is the table argument value.
			Table string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Table is the table argument value.
			Table string
			// Req is the req argument value.
			Req *TableGenRequest
		}
	}
	lockCreate         sync.RWMutex
	lockCreateRows     sync.RWMutex
	lockDelete         sync.RWMutex
	lockGenetate       sync.RWMutex
	lockGetTableDetail sync.RWMutex
	lockImport         sync.RWMutex
	lockListTables     sync.RWMutex
	lockRows           sync.RWMutex
	lockSharedSources  sync.RWMutex
	lockTruncate       sync.RWMutex
	lockUpdate         sync.RWMutex
}

// Create calls CreateFunc.
func (mock *TableServiceMock) Create(ctx context.Context, req *TableGenRequest) (string, error) {
	if mock.CreateFunc == nil {
		panic("TableServiceMock.CreateFunc: method is nil but TableService.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *TableGenRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, req)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedTableService.CreateCalls())
func (mock *TableServiceMock) CreateCalls() []struct {
	Ctx context.Context
	Req *TableGenRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *TableGenRequest
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// CreateRows calls CreateRowsFunc.
func (mock *TableServiceMock) CreateRows(ctx context.Context, table string, rows []map[string]any) error {
	if mock.CreateRowsFunc == nil {
		panic("TableServiceMock.CreateRowsFunc: method is nil but TableService.CreateRows was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Table string
		Rows  []map[string]any
	}{
		Ctx:   ctx,
		Table: table,
		Rows:  rows,
	}
	mock.lockCreateRows.Lock()
	mock.calls.CreateRows = append(mock.calls.CreateRows, callInfo)
	mock.lockCreateRows.Unlock()
	return mock.CreateRowsFunc(ctx, table, rows)
}

// CreateRowsCalls gets all the calls that were made to CreateRows.
// Check the length with:
//
//	len(mockedTableService.CreateRowsCalls())
func (mock *TableServiceMock) CreateRowsCalls() []struct {
	Ctx   context.Context
	Table string
	Rows  []map[string]any
} {
	var calls []struct {
		Ctx   context.Context
		Table string
		Rows  []map[string]any
	}
	mock.lockCreateRows.RLock()
	calls = mock.calls.CreateRows
	mock.lockCreateRows.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *TableServiceMock) Delete(ctx context.Context, table string) (int, error) {
	if mock.DeleteFunc == nil {
		panic("TableServiceMock.DeleteFunc: method is nil but TableService.Delete was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Table string
	}{
		Ctx:   ctx,
		Table: table,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, table)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedTableService.DeleteCalls())
func (mock *TableServiceMock) DeleteCalls() []struct {
	Ctx   context.Context
	Table string
} {
	var calls []struct {
		Ctx   context.Context
		Table string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Genetate calls GenetateFunc.
func (mock *TableServiceMock) Genetate(ctx context.Context, params GenerateRowsRequest) (RowsGenerator, error) {
	if mock.GenetateFunc == nil {
		panic("TableServiceMock.GenetateFunc: method is nil but TableService.Genetate was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params GenerateRowsRequest
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockGenetate.Lock()
	mock.calls.Genetate = append(mock.calls.Genetate, callInfo)
	mock.lockGenetate.Unlock()
	return mock.GenetateFunc(ctx, params)
}

// GenetateCalls gets all the calls that were made to Genetate.
// Check the length with:
//
//	len(mockedTableService.GenetateCalls())
func (mock *TableServiceMock) GenetateCalls() []struct {
	Ctx    context.Context
	Params GenerateRowsRequest
} {
	var calls []struct {
		Ctx    context.Context
		Params GenerateRowsRequest
	}
	mock.lockGenetate.RLock()
	calls = mock.calls.Genetate
	mock.lockGenetate.RUnlock()
	return calls
}

// GetTableDetail calls GetTableDetailFunc.
func (mock *TableServiceMock) GetTableDetail(ctx context.Context, table string) (*TableInfo, error) {
	if mock.GetTableDetailFunc == nil {
		panic("TableServiceMock.GetTableDetailFunc: method is nil but TableService.GetTableDetail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Table string
	}{
		Ctx:   ctx,
		Table: table,
	}
	mock.lockGetTableDetail.Lock()
	mock.calls.GetTableDetail = append(mock.calls.GetTableDetail, callInfo)
	mock.lockGetTableDetail.Unlock()
	return mock.GetTableDetailFunc(ctx, table)
}

// GetTableDetailCalls gets all the calls that were made to GetTableDetail.
// Check the length with:
//
//	len(mockedTableService.GetTableDetailCalls())
func (mock *TableServiceMock) GetTableDetailCalls() []struct {
	Ctx   context.Context
	Table string
} {
	var calls []struct {
		Ctx   context.Context
		Table string
	}
	mock.lockGetTableDetail.RLock()
	calls = mock.calls.GetTableDetail
	mock.lockGetTableDetail.RUnlock()
	return calls
}

// Import calls ImportFunc.
func (mock *TableServiceMock) Import(ctx context.Context, table string, reader io.Reader) (string, error) {
	if mock.ImportFunc == nil {
		panic("TableServiceMock.ImportFunc: method is nil but TableService.Import was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Table  string
		Reader io.Reader
	}{
		Ctx:    ctx,
		Table:  table,
		Reader: reader,
	}
	mock.lockImport.Lock()
	mock.calls.Import = append(mock.calls.Import, callInfo)
	mock.lockImport.Unlock()
	return mock.ImportFunc(ctx, table, reader)
}

// ImportCalls gets all the calls that were made to Import.
// Check the length with:
//
//	len(mockedTableService.ImportCalls())
func (mock *TableServiceMock) ImportCalls() []struct {
	Ctx    context.Context
	Table  string
	Reader io.Reader
} {
	var calls []struct {
		Ctx    context.Context
		Table  string
		Reader io.Reader
	}
	mock.lockImport.RLock()
	calls = mock.calls.Import
	mock.lockImport.RUnlock()
	return calls
}

// ListTables calls ListTablesFunc.
func (mock *TableServiceMock) ListTables(ctx context.Context) (*ListTablesResponse, error) {
	if mock.ListTablesFunc == nil {
		panic("TableServiceMock.ListTablesFunc: method is nil but TableService.ListTables was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListTables.Lock()
	mock.calls.ListTables = append(mock.calls.ListTables, callInfo)
	mock.lockListTables.Unlock()
	return mock.ListTablesFunc(ctx)
}

// ListTablesCalls gets all the calls that were made to ListTables.
// Check the length with:
//
//	len(mockedTableService.ListTablesCalls())
func (mock *TableServiceMock) ListTablesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListTables.RLock()
	calls = mock.calls.ListTables
	mock.lockListTables.RUnlock()
	return calls
}

// Rows calls RowsFunc.
func (mock *TableServiceMock) Rows(ctx context.Context, table string) (*Rows, error) {
	if mock.RowsFunc == nil {
		panic("TableServiceMock.RowsFunc: method is nil but TableService.Rows was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Table string
	}{
		Ctx:   ctx,
		Table: table,
	}
	mock.lockRows.Lock()
	mock.calls.Rows = append(mock.calls.Rows, callInfo)
	mock.lockRows.Unlock()
	return mock.RowsFunc(ctx, table)
}

// RowsCalls gets all the calls that were made to Rows.
// Check the length with:
//
//	len(mockedTableService.RowsCalls())
func (mock *TableServiceMock) RowsCalls() []struct {
	Ctx   context.Context
	Table string
} {
	var calls []struct {
		Ctx   context.Context
		Table string
	}
	mock.lockRows.RLock()
	calls = mock.calls.Rows
	mock.lockRows.RUnlock()
	return calls
}

// SharedSources calls SharedSourcesFunc.
func (mock *TableServiceMock) SharedSources(ctx context.Context) []*SharedSource {
	if mock.SharedSourcesFunc == nil {
		panic("TableServiceMock.SharedSourcesFunc: method is nil but TableService.SharedSources was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSharedSources.Lock()
	mock.calls.SharedSources = append(mock.calls.SharedSources, callInfo)
	mock.lockSharedSources.Unlock()
	return mock.SharedSourcesFunc(ctx)
}

// SharedSourcesCalls gets all the calls that were made to SharedSources.
// Check the length with:
//
//	len(mockedTableService.SharedSourcesCalls())
func (mock *TableServiceMock) SharedSourcesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSharedSources.RLock()
	calls = mock.calls.SharedSources
	mock.lockSharedSources.RUnlock()
	return calls
}

// Truncate calls TruncateFunc.
func (mock *TableServiceMock) Truncate(ctx context.Context, table string) (int, error) {
	if mock.TruncateFunc == nil {
		panic("TableServiceMock.TruncateFunc: method is nil but TableService.Truncate was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Table string
	}{
		Ctx:   ctx,
		Table: table,
	}
	mock.lockTruncate.Lock()
	mock.calls.Truncate = append(mock.calls.Truncate, callInfo)
	mock.lockTruncate.Unlock()
	return mock.TruncateFunc(ctx, table)
}

// TruncateCalls gets all the calls that were made to Truncate.
// Check the length with:
//
//	len(mockedTableService.TruncateCalls())
func (mock *TableServiceMock) TruncateCalls() []struct {
	Ctx   context.Context
	Table string
} {
	var calls []struct {
		Ctx   context.Context
		Table string
	}
	mock.lockTruncate.RLock()
	calls = mock.calls.Truncate
	mock.lockTruncate.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *TableServiceMock) Update(ctx context.Context, table string, req *TableGenRequest) (string, error) {
	if mock.UpdateFunc == nil {
		panic("TableServiceMock.UpdateFunc: method is nil but TableService.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Table string
		Req   *TableGenRequest
	}{
		Ctx:   ctx,
		Table: table,
		Req:   req,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, table, req)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedTableService.UpdateCalls())
func (mock *TableServiceMock) UpdateCalls() []struct {
	Ctx   context.Context
	Table string
	Req   *TableGenRequest
} {
	var calls []struct {
		Ctx   context.Context
		Table string
		Req   *TableGenRequest
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// Ensure, that RowsGeneratorMock does implement RowsGenerator.
// If this is not the case, regenerate this file with moq.
var _ RowsGenerator = &RowsGeneratorMock{}

// RowsGeneratorMock is a mock implementation of RowsGenerator.
//
//	func TestSomethingThatUsesRowsGenerator(t *testing.T) {
//
//		// make and configure a mocked RowsGenerator
//		mockedRowsGenerator := &RowsGeneratorMock{
//			NextFunc: func(ctx context.Context) ([]map[string]*schema.CellValue, error) {
//				panic("mock out the Next method")
//			},
//			TableFunc: func() *ent.TableMeta {
//				panic("mock out the Table method")
//			},
//		}
//
//		// use mockedRowsGenerator in code that requires RowsGenerator
//		// and then make assertions.
//
//	}
type RowsGeneratorMock struct {
	// NextFunc mocks the Next method.
	NextFunc func(ctx context.Context) ([]map[string]*schema.CellValue, error)

	// TableFunc mocks the Table method.
	TableFunc func() *ent.TableMeta

	// calls tracks calls to the methods.
	calls struct {
		// Next holds details about calls to the Next method.
		Next []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Table holds details about calls to the Table method.
		Table []struct {
		}
	}
	lockNext  sync.RWMutex
	lockTable sync.RWMutex
}

// Next calls NextFunc.
func (mock *RowsGeneratorMock) Next(ctx context.Context) ([]map[string]*schema.CellValue, error) {
	if mock.NextFunc == nil {
		panic("RowsGeneratorMock.NextFunc: method is nil but RowsGenerator.Next was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc(ctx)
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedRowsGenerator.NextCalls())
func (mock *RowsGeneratorMock) NextCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}

// Table calls TableFunc.
func (mock *RowsGeneratorMock) Table() *ent.TableMeta {
	if mock.TableFunc == nil {
		panic("RowsGeneratorMock.TableFunc: method is nil but RowsGenerator.Table was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTable.Lock()
	mock.calls.Table = append(mock.calls.Table, callInfo)
	mock.lockTable.Unlock()
	return mock.TableFunc()
}

// TableCalls gets all the calls that were made to Table.
// Check the length with:
//
//	len(mockedRowsGenerator.TableCalls())
func (mock *RowsGeneratorMock) TableCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTable.RLock()
	calls = mock.calls.Table
	mock.lockTable.RUnlock()
	return calls
}
