// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ai

import (
	"context"
	"github.com/Yiling-J/tablepilot/services/ai/client"
	"sync"
)

// Ensure, that AiServiceMock does implement AiService.
// If this is not the case, regenerate this file with moq.
var _ AiService = &AiServiceMock{}

// AiServiceMock is a mock implementation of AiService.
//
//	func TestSomethingThatUsesAiService(t *testing.T) {
//
//		// make and configure a mocked AiService
//		mockedAiService := &AiServiceMock{
//			ChatFunc: func(ctx context.Context, request *client.ChatRequest) (*client.ChatResponse, error) {
//				panic("mock out the Chat method")
//			},
//			ListModelsFunc: func(ctx context.Context) *ModelList {
//				panic("mock out the ListModels method")
//			},
//		}
//
//		// use mockedAiService in code that requires AiService
//		// and then make assertions.
//
//	}
type AiServiceMock struct {
	// ChatFunc mocks the Chat method.
	ChatFunc func(ctx context.Context, request *client.ChatRequest) (*client.ChatResponse, error)

	// ListModelsFunc mocks the ListModels method.
	ListModelsFunc func(ctx context.Context) *ModelList

	// calls tracks calls to the methods.
	calls struct {
		// Chat holds details about calls to the Chat method.
		Chat []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Request is the request argument value.
			Request *client.ChatRequest
		}
		// ListModels holds details about calls to the ListModels method.
		ListModels []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockChat       sync.RWMutex
	lockListModels sync.RWMutex
}

// Chat calls ChatFunc.
func (mock *AiServiceMock) Chat(ctx context.Context, request *client.ChatRequest) (*client.ChatResponse, error) {
	if mock.ChatFunc == nil {
		panic("AiServiceMock.ChatFunc: method is nil but AiService.Chat was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Request *client.ChatRequest
	}{
		Ctx:     ctx,
		Request: request,
	}
	mock.lockChat.Lock()
	mock.calls.Chat = append(mock.calls.Chat, callInfo)
	mock.lockChat.Unlock()
	return mock.ChatFunc(ctx, request)
}

// ChatCalls gets all the calls that were made to Chat.
// Check the length with:
//
//	len(mockedAiService.ChatCalls())
func (mock *AiServiceMock) ChatCalls() []struct {
	Ctx     context.Context
	Request *client.ChatRequest
} {
	var calls []struct {
		Ctx     context.Context
		Request *client.ChatRequest
	}
	mock.lockChat.RLock()
	calls = mock.calls.Chat
	mock.lockChat.RUnlock()
	return calls
}

// ListModels calls ListModelsFunc.
func (mock *AiServiceMock) ListModels(ctx context.Context) *ModelList {
	if mock.ListModelsFunc == nil {
		panic("AiServiceMock.ListModelsFunc: method is nil but AiService.ListModels was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListModels.Lock()
	mock.calls.ListModels = append(mock.calls.ListModels, callInfo)
	mock.lockListModels.Unlock()
	return mock.ListModelsFunc(ctx)
}

// ListModelsCalls gets all the calls that were made to ListModels.
// Check the length with:
//
//	len(mockedAiService.ListModelsCalls())
func (mock *AiServiceMock) ListModelsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListModels.RLock()
	calls = mock.calls.ListModels
	mock.lockListModels.RUnlock()
	return calls
}
