// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TableColumn is the predicate function for tablecolumn builders.
type TableColumn func(*sql.Selector)

// TableMeta is the predicate function for tablemeta builders.
type TableMeta func(*sql.Selector)

// TableRow is the predicate function for tablerow builders.
type TableRow func(*sql.Selector)
