// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)

// TableColumn is the predicate function for tablecolumn builders.
type TableColumn func(*sql.Selector)

// TableMeta is the predicate function for tablemeta builders.
type TableMeta func(*sql.Selector)

// TableRow is the predicate function for tablerow builders.
type TableRow func(*sql.Selector)

// Workflow is the predicate function for workflow builders.
type Workflow func(*sql.Selector)
